# Orbital-resolved quantum geometric tensor: 2D Haldane, benzene and coronene ($t'=0.15\,t$)

This is `Quantum_Metric_Wannier.ipynb`, adapted to run on the PythTB models of `bond_index_benzene_chern.ipynb` instead of a Wannier90 model. It keeps the original workflow: hopping table, then `ham_func`, then `TBLR.TBLinearResponse`, then the orbital-resolved QGT.

**Outputs, written to `OUT/<system>/`:**
* `qgt_xx.npy`, `qgt_xy.npy`, `qgt_yx.npy`, `qgt_yy.npy`: the four-index tensors of the original `calc_QM`, with index order `Q[a,b,c,d] = <o|v_ad|u><u|v_bc|o>/(E_u-E_o)^2`, normalized per electron.
* `fluctuation_quantum_metric.csv` and `fluctuation_berry_curvature.csv`: the last cells of `Quantum_Metric_Wannier.ipynb`, with CSV in place of the xlsx. Metric: `qgtxx + qgtyy`. Berry curvature: `i(qgtxy - qgtyx)`, whose total is $-2\,\mathrm{Im}\,\mathcal Q^{xy}$. Patterns label the `qgt[a,b,c,d]` indices, and the real part is kept, as in the original `np.float64` cast.
* `berry_loops.csv` and `berry_loop_families.csv`: the orbital-resolved Berry curvature as three-centre bond loops, as in `bond_index_benzene_chern.ipynb`, with the `einsum` index fix.
* `summary.csv`: totals and cross-checks.

**Changes from the original notebook**
1. 2D only: 2-component k, 2×2 lattice, 2-component hopping vectors, and `Nkp=[nk, nk]`. Molecules use `Nkp=[1, 1]`.
2. `calc_QM` also returns `qgtxy` and `qgtyx`, and uses a central difference for $\partial H/\partial k$, which is still built from `tb.ham`.
3. Fixed the save cell, which wrote `qgtxx` into the `qgtyx` file, and the missing `/` in the file paths.
4. The loops take $\rho(\mathbf R)$ from `tb.solve_1pRDM_kresolved`. The geometry factor uses $(\mathbf r_a-\mathbf r_b)\times(\mathbf r_a-\mathbf r_c)$; the old `einsum("ba,ca->abc", x_ba, …)` read `x_ba` transposed.
5. Loop prefactor: $C$ contribution $=(2\pi/A_{\rm cell})\,(\mathbf r_a-\mathbf r_b)\times(\mathbf r_a-\mathbf r_c)\,\mathrm{Im}\,b_{abc}$, using the honeycomb cell for the molecules too. The old prefactor $2\pi N_{\rm occ}/A_{\rm supercell}$ rescaled molecule loops by 3/4.

**Supercell.** `haldane_4x4` is the same Haldane model on a 4×4 supercell with 32 sites, built with `make_supercell`. Each site is then its own orbital index in the four-index tensor and the fluctuation tables; hops that cross the supercell boundary are still folded onto the 32 indices. Its k mesh is `NK/4`, the same k-point density as the primitive cell, so the totals must agree to mesh accuracy. Its loop table uses `rmax = ceil(RMAX/4)` supercells and writes only loops with |(r_a−r_b)×(r_a−r_c) Im b| > `LOOP_TOL_SC`. This cuts the table from 7.8 million to about 0.12 million rows, which keep C = 0.9987 of 0.99999; `summary.csv` reports the sum both before and after the cut.

**Conventions.** Lengths are in units of the nearest-neighbour bond $a$; energies are in $|t|$. `PHI = -pi/2` is the manuscript convention ($C=+1$); `+pi/2` is the original notebook ($C=-1$). For the 2-orbital Haldane cell, an "orbital" is a sublattice summed over all its lattice images, as in the Wannier workflow. The loop table resolves the images explicitly.

**Note on `TBLR.solve_QGT_kresolved_offD`.** It sums `pref*|Jx|*|Jy|`, which is neither the real nor the imaginary part of $\mathcal Q^{xy}$. It cannot give the Berry curvature, so this notebook does not use it.

In [1]:
#Import everything
import numpy as np, pandas as pd, os, json, itertools
import matplotlib.pyplot as plt
from tqdm import tqdm
from pythtb import Lattice, TBModel
import TBLR2 as TBLR
try:
    import opt_einsum as oe
    contract = oe.contract
except ImportError:                                   # opt_einsum is optional
    contract = lambda *a: np.einsum(*a, optimize=True)

# ---------------- parameters
T1      = -1.0          # nearest-neighbour hopping
T2_MAG  = 0.15          # |t'|/|t|
PHI     = -np.pi/2      # -pi/2: manuscript convention (C=+1); +pi/2: original notebook (C=-1)
DELTA   = 0.0           # sublattice mass
NK      = 100           # periodic model: NK x NK k mesh
RMAX    = 6             # periodic model: lattice-image box for the three-centre loops
MU      = 0.0           # chemical potential (half filling)
BETA    = 1.e2          # Fermi smearing, as in the original notebook
K_STEP  = 1.e-4         # finite-difference step for dH/dk (central difference)
ACC     = 1/np.sqrt(3)  # NN bond in PythTB lattice units -> lengths are reported in units of a
SC      = 4             # Haldane supercell size (SC x SC); its k mesh is NK//SC so it samples the same k-points
LOOP_TOL_SC = 1e-6      # supercell loop table: keep loops with |(r_a-r_b)x(r_a-r_c) Im b| > tol (7.8M -> 0.12M rows; full sum still reported)
OUT     = "qgt_orbital_resolved_tprime_0p15"

In [2]:
#Models: same hoppings as bond_index_benzene_chern.ipynb
def build_models(t2mag=T2_MAG, phi=PHI, delta=DELTA, t=T1):
    lat = Lattice([[1, 0], [0.5, np.sqrt(3)/2]], [[1/3, 1/3], [2/3, 2/3]], periodic_dirs=...)
    h = TBModel(lat)
    t2 = t2mag*np.exp(1j*phi); t2c = np.conj(t2)
    h.set_onsite([-delta, delta])
    h.set_hop(t, 0, 1, [0, 0]); h.set_hop(t, 1, 0, [1, 0]); h.set_hop(t, 1, 0, [0, 1])
    h.set_hop(t2, 0, 0, [1, 0]); h.set_hop(t2, 1, 1, [1, -1]); h.set_hop(t2, 1, 1, [0, 1])
    h.set_hop(t2c, 1, 1, [1, 0]); h.set_hop(t2c, 0, 0, [1, -1]); h.set_hop(t2c, 0, 0, [0, 1])
    s1 = h.make_supercell(np.array([[2, 0], [0, 2]]))
    bz = s1.cut_piece(1, 1, glue_edges=False).cut_piece(1, 0, glue_edges=False)
    bz.remove_orb(7); bz.remove_orb(0)
    s2 = h.make_supercell(np.array([[4, 0], [0, 4]]))
    co = s2.cut_piece(1, 1, glue_edges=False).cut_piece(1, 0, glue_edges=False)
    for o in [31, 30, 29, 23, 8, 2, 1, 0]: co.remove_orb(o)
    hsc = h.make_supercell(np.array([[SC, 0], [0, SC]]))          # SC x SC supercell of the periodic model
    return {"haldane": h, f"haldane_{SC}x{SC}": hsc, "benzene": bz, "coronene": co}

def is_molecule(model):
    return not any(np.any(np.asarray(hp.get("lattice_vector", [0, 0])) != 0) for hp in model.hoppings)

In [3]:
#Create array with all hopping information (2D)
def hopping_table(my_model):
    norb = my_model.norb
    H = np.empty((norb, norb), dtype=object)
    for i in range(norb):
        for j in range(norb):
            H[i, j] = []
    orb_pos = np.asarray(my_model.orb_vecs)
    lat = np.asarray(my_model.get_lat_vecs())/ACC          # lengths in units of a
    for hop in my_model.hoppings:
        t = hop['amplitude']
        i = hop['from_orbital']
        j = hop['to_orbital']
        j_image = np.asarray(hop.get('lattice_vector', [0, 0]))
        dist = ((orb_pos[j]+j_image)-orb_pos[i]) @ lat
        H[i, j].append([t, dist[0], dist[1]])
    return H, lat, orb_pos @ lat

#Function that finds hamiltonian from hopping array at specific k-point (2D)
def make_ham_func(H, my_model):
    norb = my_model.norb
    onsite = np.asarray(my_model._site_energies, float)
    def ham_func(k):
        kx, ky = k
        H_res = np.zeros((norb, norb), dtype=complex)
        for i in range(norb):
            for j in range(norb):
                for item in H[i][j]:
                    v = np.round(complex(item[0]), 10)*np.exp(1j*kx*item[1]+1j*ky*item[2])
                    H_res[i][j] += v
                    H_res[j][i] += np.conj(v)
        for i, e in enumerate(onsite):
            H_res[i, i] += np.round(e, 10)
        return H_res
    return ham_func

In [4]:
#Orbital-resolved QGT (original calc_QM, 2D, now with xy and yx), per electron
def Fermi(beta_const, x):
    return 1.0/(1.0 + np.exp(beta_const*x))

def FNM(em, en, beta_const=BETA, delta=1.e-3):
    emn = em - en
    fnm = Fermi(beta_const, en)*(1.0 - Fermi(beta_const, em))
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(np.abs(emn) < delta, 0.0, fnm/(emn**2))

def calc_QM(tb, occ, mu=MU, k_step=K_STEP):
    dkx, dky = np.array([1, 0]), np.array([0, 1])
    e = tb.enUM[:, :, 0].real - mu
    pref = FNM(e[:, np.newaxis, :], e[:, :, np.newaxis])     # pref[k,i,j] = f_i(1-f_j)/(E_j-E_i)^2
    n = tb.norb
    Q = {c: np.zeros((n, n, n, n), complex) for c in ("xx", "xy", "yx", "yy")}
    for i, k in enumerate(tqdm(tb.kSpan, disable=len(tb.kSpan) < 2)):
        um = tb.enUM[i, :, 1:]
        uH = um.conj().T
        dH = {"x": (tb.ham(k + k_step*dkx) - tb.ham(k - k_step*dkx))/(2*k_step),
              "y": (tb.ham(k + k_step*dky) - tb.ham(k - k_step*dky))/(2*k_step)}
        Jv1 = {c: contract("ia,ad,dj->adij", uH, dH[c], um) for c in "xy"}             # <i|v_ad|j>
        Jv2c = {c: np.conj(contract("ic,cb,bj->bcij", uH, dH[c], um)) for c in "xy"}   # <j|v_bc|i>
        for c in Q:
            Q[c] += contract("ij,adij,bcij->abcd", pref[i], Jv1[c[0]], Jv2c[c[1]])
    denom = len(tb.kSpan)*occ
    return {c: Q[c]/denom for c in Q}

In [5]:
#Fluctuation-resolved quantum metric and Berry curvature (last cells of Quantum_Metric_Wannier.ipynb)
import itertools

def canonicalize(combo):
    mapping = {}
    next_label = ord('a')
    result = []
    for x in combo:
        if x not in mapping:
            mapping[x] = chr(next_label)
            next_label += 1
        result.append(mapping[x])
    return ''.join(result)

def find_combo_list(orb_list, num_un):
    patterns = set()
    for combo in itertools.product(orb_list, repeat=4):
        if len(set(combo)) >= num_un:
            patterns.add(canonicalize(combo))
    return sorted(patterns)

def find_atom_metric(atomic_metric, num_un, atoms):
    atomic_metric_ab = atomic_metric.copy()
    for a in range(len(atoms)):
        for b in range(len(atoms)):
            for c in range(len(atoms)):
                indices = [a, b, c][:num_un]
                direct_indices = np.asarray(list(itertools.product(indices, repeat=4)))
                for ind in direct_indices:
                    atomic_metric_ab[ind[0], ind[1], ind[2], ind[3]] = 0
    return atomic_metric_ab

combo_a = find_combo_list(["a"], 1)
combo_ab = find_combo_list(["a", "b"], 2)
combo_abc = find_combo_list(["a", "b", "c"], 3)
combo_abcd = find_combo_list(["a", "b", "c", "d"], 4)

def fluctuation_table(tensor, atoms, label, denom=1):
    """tensor[a,b,c,d] in the qgt index order; returns the 1orb/2orb/3orb/4orb table of the original notebook."""
    atomic = np.zeros((len(atoms),)*4, dtype=complex)
    for i, m in enumerate(atoms):
        for j, n in enumerate(atoms):
            for k, o in enumerate(atoms):
                for l, p in enumerate(atoms):
                    atomic[i, j, k, l] = np.sum(tensor[np.ix_(m, n, o, p)])
    atom_metric_ab = find_atom_metric(atomic, 1, atoms)
    atom_metric_abc = find_atom_metric(atomic, 2, atoms)
    atom_metric_abcd = find_atom_metric(atomic, 3, atoms)
    data = [[], [], [], []]; dropped_imag = 0.0
    sets = [(combo_a, atomic), (np.setdiff1d(combo_ab, combo_a), atom_metric_ab),
            (np.setdiff1d(combo_abc, combo_ab), atom_metric_abc), (np.setdiff1d(combo_abcd, combo_abc), atom_metric_abcd)]
    for n, (combos, arr) in enumerate(sets):
        for combo in combos:
            v = np.einsum(str(combo)+"->", arr)/denom
            dropped_imag = max(dropped_imag, abs(v.imag))
            data[n].append([str(combo), np.float64(v.real)])     # the original keeps the real part (np.float64 cast)
    dfs = [pd.DataFrame(data=np.array(d, dtype=object), columns=[f"{n+1}orb", f"{label}{n+1}orb"]) for n, d in enumerate(data)]
    df = pd.concat(dfs, axis=1)
    for n in range(4):
        df[f"{label}{n+1}orb"] = pd.to_numeric(df[f"{label}{n+1}orb"])
    total = np.real(np.sum(tensor))/denom
    return df, total, dropped_imag

In [6]:
#Three-centre bond loops = orbital-resolved Berry curvature (bond_index_benzene_chern, index fix)
def bond_element_factory(tb, pos, lat, mu=MU):
    """rho_ab(R) = <a,0|P|b,R> from TBLR's k-resolved 1pRDM."""
    Pk = tb.solve_1pRDM_kresolved(mu)
    r0 = pos[np.newaxis, :] - pos[:, np.newaxis]                # r0[a,b] = r_b - r_a
    cache = {}
    def bond_element(R):
        key = (int(R[0]), int(R[1]))
        if key not in cache:
            r = r0 + np.asarray(R) @ lat
            ph = np.exp(-1j*np.einsum("kx,abx->kab", tb.kSpan, r))
            cache[key] = ((Pk*ph).mean(0), r)
        return cache[key]
    return bond_element

def loop_table(tb, model, pos, lat, occ, rmax=RMAX, mu=MU, tol=1e-14):
    mol = is_molecule(model)
    A_cell = 3*np.sqrt(3)/2 if mol else abs(np.linalg.det(lat))    # honeycomb cell in a^2
    bond_element = bond_element_factory(tb, pos, lat, mu)
    R_list = [[0, 0]] if mol else [[i, j] for i in range(-rmax, rmax+1) for j in range(-rmax, rmax+1)]
    chunks = []; W_total = 0.0
    for R1 in tqdm(R_list, disable=mol):
        for R2 in R_list:
            R1, R2 = np.asarray(R1), np.asarray(R2)
            rho_ab, dist_ab = bond_element(R1)            # dist_ab[a,b] = r_b - r_a  (b in cell R1)
            rho_bc, _ = bond_element(R2)
            rho_ca, dist_ca = bond_element(-R1-R2)        # dist_ca[c,a] = r_a - r_c  (c in cell R1+R2)
            BI = np.einsum("ab,bc,ca->abc", rho_ab, rho_bc, rho_ca)
            x_ab, y_ab = -dist_ab[:, :, 0], -dist_ab[:, :, 1]      # [a,b]: r_a - r_b
            x_ac, y_ac = dist_ca[:, :, 0].T, dist_ca[:, :, 1].T    # [a,c]: r_a - r_c
            dist_part = np.einsum("ab,ac->abc", x_ab, y_ac) - np.einsum("ab,ac->abc", y_ab, x_ac)
            W = dist_part*BI.imag
            W_total += W.sum()
            m = np.abs(W) > tol
            if not m.any():
                continue
            ai, bi, ci = np.where(m)
            chunks.append(pd.DataFrame({
                "a": ai, "b": bi, "c": ci, "R1x": R1[0], "R1y": R1[1], "R2x": R2[0], "R2y": R2[1],
                "dist_ab_x": x_ab[ai, bi], "dist_ab_y": y_ab[ai, bi],
                "dist_ca_x": x_ac[ai, ci], "dist_ca_y": y_ac[ai, ci],
                "oriented_area": 0.5*dist_part[m], "dist_part": dist_part[m],
                "BI_real": BI.real[m], "BI_imag": BI.imag[m], "BI_abs": np.abs(BI[m]),
                "Omega_per_e": W[m]/occ,                  # contribution to Omega^xy per electron (a^2)
                "C_imag": 2*np.pi/A_cell*W[m]}))          # contribution to C (bulk) / Fig. 4 loop weight (molecules)
    cols = ["a", "b", "c", "R1x", "R1y", "R2x", "R2y", "dist_ab_x", "dist_ab_y", "dist_ca_x", "dist_ca_y",
            "oriented_area", "dist_part", "BI_real", "BI_imag", "BI_abs", "Omega_per_e", "C_imag"]
    df = pd.concat(chunks, ignore_index=True) if chunks else pd.DataFrame(columns=cols)
    df.attrs["C_all_loops"] = float(2*np.pi/A_cell*W_total)      # before the tol cut
    return df, A_cell, bond_element

def loop_families(dfl):
    if not len(dfl):
        return pd.DataFrame(columns=["sides_over_a", "n_loops", "Omega_per_e", "C_imag", "sum_abs_C", "fraction_of_total"])
    ab = np.hypot(dfl.dist_ab_x, dfl.dist_ab_y); ca = np.hypot(dfl.dist_ca_x, dfl.dist_ca_y)
    bc = np.hypot(dfl.dist_ab_x-dfl.dist_ca_x, dfl.dist_ab_y-dfl.dist_ca_y)
    key = [", ".join(f"{x:.3f}" for x in sorted(t)) for t in zip(ab, bc, ca)]
    g = dfl.assign(sides_over_a=key).groupby("sides_over_a").agg(
        n_loops=("C_imag", "size"), Omega_per_e=("Omega_per_e", "sum"),
        C_imag=("C_imag", "sum"), sum_abs_C=("C_imag", lambda s: s.abs().sum()))
    tot = dfl.C_imag.sum()
    g["fraction_of_total"] = g.C_imag/tot if abs(tot) > 1e-8 else np.nan
    return g.reindex(g.sum_abs_C.sort_values(ascending=False).index).reset_index()

def g_bond(bond_element, pos, lat, occ, mol, rmax=RMAX):
    """two-centre check, Eq. 1: Tr g = 1/(2 Ne) sum |rho_ab(R)|^2 |r_b + R - r_a|^2"""
    Rs = [[0, 0]] if mol else [[i, j] for i in range(-2*rmax, 2*rmax+1) for j in range(-2*rmax, 2*rmax+1)]
    return sum((np.abs(r)**2*(d**2).sum(-1)).sum() for r, d in (bond_element(R) for R in Rs))/(2*occ)

In [7]:
#Run: TBLR object per model, QGT tensors, loops, and write everything
summary = []
import time
for name, my_model in build_models().items():
    t0 = time.time()
    mol = is_molecule(my_model)
    H, lat, pos = hopping_table(my_model)
    ham_func = make_ham_func(H, my_model)
    sc = name.startswith("haldane_")
    nk = 1 if mol else (NK//SC if sc else NK)
    rmax = int(np.ceil(RMAX/SC)) if sc else RMAX
    tb = TBLR.TBLinearResponse(ham_func, Lar=np.array(lat),
                               Nkp=[nk, nk],
                               prestr=f"{name}_tp{T2_MAG}",
                               save_all=False,
                               kpath=['G', 'X', 'M', 'G', 'Y', 'M'])
    occ = int(np.sum(tb.enUM[0, :, 0].real <= MU))
    print(f"{name}: norb={tb.norb}  occ={occ}  k-points={len(tb.kSpan)}")

    qgt = calc_QM(tb, occ)
    atoms = [[i] for i in range(tb.norb)]       # one orbital per site (Haldane cell: the two sublattices)
    QM_tensor = qgt["xx"] + qgt["yy"]            # metric trace, as in the original cell
    BC_tensor = 1j*(qgt["xy"] - qgt["yx"])       # Berry curvature Omega^xy; its total is -2 Im Q^xy
    df_qm, tot_qm, im_qm = fluctuation_table(QM_tensor, atoms, "QM")
    df_bc, tot_bc, im_bc = fluctuation_table(BC_tensor, atoms, "BC")
    dfl, A_cell, bond_element = loop_table(tb, my_model, pos, lat, occ, rmax=rmax, tol=LOOP_TOL_SC if sc else 1e-14)

    d = os.path.join(OUT, name); os.makedirs(d, exist_ok=True)
    for c in qgt:
        np.save(os.path.join(d, f"qgt_{c}.npy"), qgt[c])
    df_qm.to_csv(os.path.join(d, "fluctuation_quantum_metric.csv"), index=False)
    df_bc.to_csv(os.path.join(d, "fluctuation_berry_curvature.csv"), index=False)
    dfl.to_csv(os.path.join(d, "berry_loops.csv"), index=False)
    loop_families(dfl).to_csv(os.path.join(d, "berry_loop_families.csv"), index=False)

    # cross-checks: TBLR's own k-resolved metric, the two-centre bond formula, and the two Berry partitions
    gxx_tblr = np.sum(tb.solve_QGT_kresolved(mu=MU, dkx=np.array([1, 0]), k_step=K_STEP)).real/(len(tb.kSpan)*occ)
    gyy_tblr = np.sum(tb.solve_QGT_kresolved(mu=MU, dkx=np.array([0, 1]), k_step=K_STEP)).real/(len(tb.kSpan)*occ)
    Om4 = tot_bc
    print(f"   {name} done in {time.time()-t0:.0f} s", flush=True)
    summary.append(dict(system=name, norb=tb.norb, N_e=occ, k_points=len(tb.kSpan), molecule=mol,
        Tr_g_4index=tot_qm, QM_fluct_sum=sum(df_qm[f"QM{n}orb"].sum() for n in range(1, 5)),
        BC_fluct_sum=sum(df_bc[f"BC{n}orb"].sum() for n in range(1, 5)), max_dropped_imag=max(im_qm, im_bc), Tr_g_TBLR=gxx_tblr+gyy_tblr,
        Tr_g_bond_Eq1=g_bond(bond_element, pos, lat, occ, mol, rmax=rmax),
        Omega_4index=Om4, Omega_loops=float(dfl.Omega_per_e.sum()) if len(dfl) else 0.0,
        C_4index=0.0 if mol else 2*np.pi*occ/A_cell*Om4,
        C_loops=float(dfl.C_imag.sum()) if len(dfl) else 0.0, C_loops_before_cut=dfl.attrs.get("C_all_loops", 0.0),
        sum_abs_C_loops=float(dfl.C_imag.abs().sum()) if len(dfl) else 0.0,
        n_loop_rows=len(dfl), rmax=None if mol else rmax))
summary = pd.DataFrame(summary)
summary.to_csv(os.path.join(OUT, "summary.csv"), index=False)
json.dump(dict(T1=T1, T2_MAG=T2_MAG, PHI=PHI, DELTA=DELTA, NK=NK, RMAX=RMAX, MU=MU, BETA=BETA, K_STEP=K_STEP,
               length_unit="a (NN bond)", energy_unit="|t|",
               qgt_index_order="Q[a,b,c,d] = <o|v_ad|u><u|v_bc|o>/(E_u-E_o)^2, per electron"),
          open(os.path.join(OUT, "parameters.json"), "w"), indent=2)
pd.set_option("display.float_format", lambda x: f"{x:.6g}")
summary

haldane: norb=2  occ=1  k-points=10000

  0%|          | 0/10000 [00:00<?, ?it/s]

  1%|          | 78/10000 [00:00<00:12, 773.61it/s]

  2%|▏         | 156/10000 [00:00<00:15, 633.85it/s]

  2%|▏         | 233/10000 [00:00<00:14, 687.91it/s]

  3%|▎         | 307/10000 [00:00<00:13, 703.79it/s]

  4%|▍         | 381/10000 [00:00<00:13, 715.35it/s]

  5%|▍         | 455/10000 [00:00<00:13, 722.76it/s]

  5%|▌         | 530/10000 [00:00<00:13, 728.31it/s]

  6%|▌         | 604/10000 [00:00<00:13, 717.00it/s]

  7%|▋         | 679/10000 [00:00<00:12, 726.70it/s]

  8%|▊         | 755/10000 [00:01<00:12, 734.56it/s]

  8%|▊         | 829/10000 [00:01<00:12, 733.21it/s]

  9%|▉         | 903/10000 [00:01<00:12, 728.99it/s]

 10%|▉         | 979/10000 [00:01<00:12, 737.20it/s]

 11%|█         | 1058/10000 [00:01<00:11, 752.21it/s]

 11%|█▏        | 1134/10000 [00:01<00:11, 751.85it/s]

 12%|█▏        | 1212/10000 [00:01<00:11, 756.74it/s]

 13%|█▎        | 1288/10000 [00:01<00:11, 748.78it/s]

 14%|█▎        | 1363/10000 [00:01<00:11, 740.19it/s]

 14%|█▍        | 1438/10000 [00:01<00:11, 728.84it/s]

 15%|█▌        | 1511/10000 [00:02<00:11, 710.04it/s]

 16%|█▌        | 1583/10000 [00:02<00:12, 685.81it/s]

 17%|█▋        | 1658/10000 [00:02<00:11, 701.85it/s]

 17%|█▋        | 1735/10000 [00:02<00:11, 720.76it/s]

 18%|█▊        | 1808/10000 [00:02<00:11, 716.02it/s]

 19%|█▉        | 1880/10000 [00:02<00:11, 699.89it/s]

 20%|█▉        | 1951/10000 [00:02<00:12, 665.99it/s]

 20%|██        | 2018/10000 [00:02<00:12, 646.24it/s]

 21%|██        | 2085/10000 [00:02<00:12, 650.96it/s]

 22%|██▏       | 2151/10000 [00:03<00:12, 637.06it/s]

 22%|██▏       | 2221/10000 [00:03<00:11, 649.22it/s]

 23%|██▎       | 2287/10000 [00:03<00:12, 614.07it/s]

 24%|██▎       | 2358/10000 [00:03<00:11, 638.87it/s]

 24%|██▍       | 2428/10000 [00:03<00:11, 655.97it/s]

 25%|██▍       | 2497/10000 [00:03<00:11, 665.60it/s]

 26%|██▌       | 2565/10000 [00:03<00:11, 668.94it/s]

 26%|██▋       | 2636/10000 [00:03<00:10, 680.41it/s]

 27%|██▋       | 2707/10000 [00:03<00:10, 686.96it/s]

 28%|██▊       | 2779/10000 [00:03<00:10, 694.79it/s]

 28%|██▊       | 2850/10000 [00:04<00:10, 699.04it/s]

 29%|██▉       | 2923/10000 [00:04<00:09, 707.72it/s]

 30%|██▉       | 2994/10000 [00:04<00:09, 701.73it/s]

 31%|███       | 3067/10000 [00:04<00:09, 708.02it/s]

 31%|███▏      | 3140/10000 [00:04<00:09, 712.54it/s]

 32%|███▏      | 3212/10000 [00:04<00:09, 711.41it/s]

 33%|███▎      | 3284/10000 [00:04<00:09, 711.12it/s]

 34%|███▎      | 3358/10000 [00:04<00:09, 718.01it/s]

 34%|███▍      | 3430/10000 [00:04<00:09, 700.63it/s]

 35%|███▌      | 3501/10000 [00:05<00:09, 690.16it/s]

 36%|███▌      | 3572/10000 [00:05<00:09, 695.05it/s]

 36%|███▋      | 3642/10000 [00:05<00:09, 690.71it/s]

 37%|███▋      | 3712/10000 [00:05<00:09, 693.19it/s]

 38%|███▊      | 3782/10000 [00:05<00:09, 690.09it/s]

 39%|███▊      | 3852/10000 [00:05<00:08, 687.72it/s]

 39%|███▉      | 3923/10000 [00:05<00:08, 693.58it/s]

 40%|███▉      | 3993/10000 [00:05<00:08, 678.47it/s]

 41%|████      | 4061/10000 [00:05<00:08, 678.46it/s]

 41%|████▏     | 4136/10000 [00:05<00:08, 698.55it/s]

 42%|████▏     | 4208/10000 [00:06<00:08, 704.51it/s]

 43%|████▎     | 4280/10000 [00:06<00:08, 707.80it/s]

 44%|████▎     | 4353/10000 [00:06<00:07, 713.36it/s]

 44%|████▍     | 4426/10000 [00:06<00:07, 715.61it/s]

 45%|████▌     | 4501/10000 [00:06<00:07, 723.24it/s]

 46%|████▌     | 4576/10000 [00:06<00:07, 730.80it/s]

 46%|████▋     | 4650/10000 [00:06<00:07, 724.40it/s]

 47%|████▋     | 4724/10000 [00:06<00:07, 726.94it/s]

 48%|████▊     | 4799/10000 [00:06<00:07, 731.49it/s]

 49%|████▊     | 4873/10000 [00:06<00:06, 733.99it/s]

 49%|████▉     | 4947/10000 [00:07<00:06, 732.95it/s]

 50%|█████     | 5022/10000 [00:07<00:06, 737.19it/s]

 51%|█████     | 5096/10000 [00:07<00:06, 737.38it/s]

 52%|█████▏    | 5172/10000 [00:07<00:06, 743.93it/s]

 52%|█████▏    | 5249/10000 [00:07<00:06, 749.55it/s]

 53%|█████▎    | 5325/10000 [00:07<00:06, 751.42it/s]

 54%|█████▍    | 5402/10000 [00:07<00:06, 756.52it/s]

 55%|█████▍    | 5478/10000 [00:07<00:05, 757.09it/s]

 56%|█████▌    | 5557/10000 [00:07<00:05, 766.81it/s]

 56%|█████▋    | 5635/10000 [00:07<00:05, 769.16it/s]

 57%|█████▋    | 5712/10000 [00:08<00:05, 767.07it/s]

 58%|█████▊    | 5791/10000 [00:08<00:05, 772.29it/s]

 59%|█████▊    | 5869/10000 [00:08<00:05, 773.58it/s]

 59%|█████▉    | 5948/10000 [00:08<00:05, 776.13it/s]

 60%|██████    | 6026/10000 [00:08<00:05, 775.23it/s]

 61%|██████    | 6104/10000 [00:08<00:05, 764.63it/s]

 62%|██████▏   | 6181/10000 [00:08<00:05, 758.17it/s]

 63%|██████▎   | 6257/10000 [00:08<00:04, 757.80it/s]

 63%|██████▎   | 6333/10000 [00:08<00:04, 753.76it/s]

 64%|██████▍   | 6411/10000 [00:08<00:04, 759.02it/s]

 65%|██████▍   | 6487/10000 [00:09<00:04, 745.14it/s]

 66%|██████▌   | 6564/10000 [00:09<00:04, 750.19it/s]

 66%|██████▋   | 6640/10000 [00:09<00:04, 751.29it/s]

 67%|██████▋   | 6719/10000 [00:09<00:04, 762.08it/s]

 68%|██████▊   | 6796/10000 [00:09<00:04, 760.53it/s]

 69%|██████▊   | 6873/10000 [00:09<00:04, 757.41it/s]

 69%|██████▉   | 6949/10000 [00:09<00:04, 754.02it/s]

 70%|███████   | 7025/10000 [00:09<00:03, 755.72it/s]

 71%|███████   | 7101/10000 [00:09<00:03, 752.39it/s]

 72%|███████▏  | 7177/10000 [00:09<00:03, 746.04it/s]

 73%|███████▎  | 7252/10000 [00:10<00:03, 738.39it/s]

 73%|███████▎  | 7326/10000 [00:10<00:03, 734.74it/s]

 74%|███████▍  | 7400/10000 [00:10<00:03, 729.86it/s]

 75%|███████▍  | 7473/10000 [00:10<00:03, 729.71it/s]

 75%|███████▌  | 7548/10000 [00:10<00:03, 735.44it/s]

 76%|███████▋  | 7625/10000 [00:10<00:03, 744.85it/s]

 77%|███████▋  | 7701/10000 [00:10<00:03, 746.58it/s]

 78%|███████▊  | 7776/10000 [00:10<00:02, 742.70it/s]

 79%|███████▊  | 7851/10000 [00:10<00:02, 741.79it/s]

 79%|███████▉  | 7927/10000 [00:10<00:02, 744.34it/s]

 80%|████████  | 8003/10000 [00:11<00:02, 748.88it/s]

 81%|████████  | 8079/10000 [00:11<00:02, 749.65it/s]

 82%|████████▏ | 8156/10000 [00:11<00:02, 753.77it/s]

 82%|████████▏ | 8234/10000 [00:11<00:02, 759.04it/s]

 83%|████████▎ | 8312/10000 [00:11<00:02, 764.72it/s]

 84%|████████▍ | 8389/10000 [00:11<00:02, 759.99it/s]

 85%|████████▍ | 8466/10000 [00:11<00:02, 753.86it/s]

 85%|████████▌ | 8542/10000 [00:11<00:01, 751.82it/s]

 86%|████████▌ | 8619/10000 [00:11<00:01, 755.32it/s]

 87%|████████▋ | 8696/10000 [00:12<00:01, 757.70it/s]

 88%|████████▊ | 8773/10000 [00:12<00:01, 759.19it/s]

 88%|████████▊ | 8850/10000 [00:12<00:01, 762.31it/s]

 89%|████████▉ | 8927/10000 [00:12<00:01, 764.31it/s]

 90%|█████████ | 9005/10000 [00:12<00:01, 767.66it/s]

 91%|█████████ | 9082/10000 [00:12<00:01, 767.48it/s]

 92%|█████████▏| 9159/10000 [00:12<00:01, 760.29it/s]

 92%|█████████▏| 9236/10000 [00:12<00:01, 758.07it/s]

 93%|█████████▎| 9313/10000 [00:12<00:00, 758.97it/s]

 94%|█████████▍| 9391/10000 [00:12<00:00, 764.33it/s]

 95%|█████████▍| 9470/10000 [00:13<00:00, 769.07it/s]

 95%|█████████▌| 9548/10000 [00:13<00:00, 770.44it/s]

 96%|█████████▋| 9626/10000 [00:13<00:00, 768.21it/s]

 97%|█████████▋| 9703/10000 [00:13<00:00, 768.63it/s]

 98%|█████████▊| 9780/10000 [00:13<00:00, 765.61it/s]

 99%|█████████▊| 9857/10000 [00:13<00:00, 754.11it/s]

 99%|█████████▉| 9933/10000 [00:13<00:00, 746.73it/s]

100%|██████████| 10000/10000 [00:13<00:00, 728.79it/s]

  0%|          | 0/169 [00:00<?, ?it/s]

  1%|          | 1/169 [00:00<01:21,  2.06it/s]

  2%|▏         | 4/169 [00:00<00:21,  7.77it/s]

  4%|▍         | 7/169 [00:00<00:13, 11.76it/s]

  5%|▌         | 9/169 [00:00<00:13, 11.89it/s]

  7%|▋         | 11/169 [00:01<00:12, 12.71it/s]

  8%|▊         | 13/169 [00:01<00:11, 13.65it/s]

  9%|▉         | 16/169 [00:01<00:08, 17.20it/s]

 11%|█         | 19/169 [00:01<00:07, 20.05it/s]

 13%|█▎        | 22/169 [00:01<00:07, 20.62it/s]

 15%|█▍        | 25/169 [00:01<00:06, 21.22it/s]

 17%|█▋        | 28/169 [00:01<00:07, 19.20it/s]

 18%|█▊        | 31/169 [00:01<00:06, 20.79it/s]

 20%|██        | 34/169 [00:02<00:06, 21.46it/s]

 22%|██▏       | 37/169 [00:02<00:06, 21.46it/s]

 24%|██▎       | 40/169 [00:02<00:05, 21.75it/s]

 25%|██▌       | 43/169 [00:02<00:06, 19.49it/s]

 27%|██▋       | 46/169 [00:02<00:05, 20.72it/s]

 29%|██▉       | 49/169 [00:02<00:05, 21.30it/s]

 31%|███       | 52/169 [00:02<00:05, 22.33it/s]

 33%|███▎      | 55/169 [00:03<00:04, 23.10it/s]

 34%|███▍      | 58/169 [00:03<00:04, 23.98it/s]

 36%|███▌      | 61/169 [00:03<00:04, 24.10it/s]

 38%|███▊      | 64/169 [00:03<00:05, 19.23it/s]

 40%|███▉      | 67/169 [00:03<00:05, 20.30it/s]

 41%|████▏     | 70/169 [00:03<00:04, 21.47it/s]

 43%|████▎     | 73/169 [00:03<00:04, 22.41it/s]

 45%|████▍     | 76/169 [00:04<00:04, 22.76it/s]

 47%|████▋     | 79/169 [00:04<00:04, 22.44it/s]

 49%|████▊     | 82/169 [00:04<00:03, 22.71it/s]

 50%|█████     | 85/169 [00:04<00:03, 23.51it/s]

 52%|█████▏    | 88/169 [00:04<00:04, 18.51it/s]

 54%|█████▍    | 91/169 [00:04<00:03, 20.36it/s]

 56%|█████▌    | 94/169 [00:04<00:03, 20.62it/s]

 57%|█████▋    | 97/169 [00:05<00:03, 21.99it/s]

 59%|█████▉    | 100/169 [00:05<00:03, 22.80it/s]

 61%|██████    | 103/169 [00:05<00:02, 22.39it/s]

 63%|██████▎   | 106/169 [00:05<00:02, 21.68it/s]

 64%|██████▍   | 109/169 [00:05<00:02, 22.50it/s]

 66%|██████▋   | 112/169 [00:05<00:02, 22.97it/s]

 68%|██████▊   | 115/169 [00:05<00:02, 23.35it/s]

 70%|██████▉   | 118/169 [00:06<00:03, 16.87it/s]

 72%|███████▏  | 121/169 [00:06<00:02, 18.55it/s]

 73%|███████▎  | 124/169 [00:06<00:02, 19.92it/s]

 75%|███████▌  | 127/169 [00:06<00:01, 21.26it/s]

 77%|███████▋  | 130/169 [00:06<00:01, 22.42it/s]

 79%|███████▊  | 133/169 [00:06<00:01, 22.05it/s]

 80%|████████  | 136/169 [00:06<00:01, 22.61it/s]

 82%|████████▏ | 139/169 [00:06<00:01, 23.21it/s]

 84%|████████▍ | 142/169 [00:07<00:01, 23.94it/s]

 86%|████████▌ | 145/169 [00:07<00:01, 23.29it/s]

 88%|████████▊ | 148/169 [00:07<00:00, 23.61it/s]

 89%|████████▉ | 151/169 [00:07<00:00, 24.06it/s]

 91%|█████████ | 154/169 [00:07<00:00, 24.65it/s]

 93%|█████████▎| 157/169 [00:07<00:00, 15.97it/s]

 95%|█████████▍| 160/169 [00:08<00:00, 17.85it/s]

 96%|█████████▋| 163/169 [00:08<00:00, 19.59it/s]

 98%|█████████▊| 166/169 [00:08<00:00, 21.18it/s]

100%|██████████| 169/169 [00:08<00:00, 20.18it/s]

/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: divide by zero encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))
/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: invalid value encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))

   haldane done in 34 s

haldane_4x4: norb=32  occ=16  k-points=625

  0%|          | 0/625 [00:00<?, ?it/s]

  0%|          | 1/625 [00:00<06:29,  1.60it/s]

  0%|          | 2/625 [00:01<06:08,  1.69it/s]

  0%|          | 3/625 [00:01<06:03,  1.71it/s]

  1%|          | 4/625 [00:02<06:01,  1.72it/s]

  1%|          | 5/625 [00:02<05:58,  1.73it/s]

  1%|          | 6/625 [00:03<05:57,  1.73it/s]

  1%|          | 7/625 [00:04<05:53,  1.75it/s]

  1%|▏         | 8/625 [00:04<05:56,  1.73it/s]

  1%|▏         | 9/625 [00:05<05:59,  1.71it/s]

  2%|▏         | 10/625 [00:05<05:52,  1.75it/s]

  2%|▏         | 11/625 [00:06<05:47,  1.77it/s]

  2%|▏         | 12/625 [00:06<05:46,  1.77it/s]

  2%|▏         | 13/625 [00:07<05:43,  1.78it/s]

  2%|▏         | 14/625 [00:08<05:44,  1.77it/s]

  2%|▏         | 15/625 [00:08<05:47,  1.75it/s]

  3%|▎         | 16/625 [00:09<05:50,  1.74it/s]

  3%|▎         | 17/625 [00:09<05:42,  1.77it/s]

  3%|▎         | 18/625 [00:10<05:38,  1.79it/s]

  3%|▎         | 19/625 [00:10<05:36,  1.80it/s]

  3%|▎         | 20/625 [00:11<05:42,  1.77it/s]

  3%|▎         | 21/625 [00:12<05:45,  1.75it/s]

  4%|▎         | 22/625 [00:12<05:44,  1.75it/s]

  4%|▎         | 23/625 [00:13<05:45,  1.74it/s]

  4%|▍         | 24/625 [00:13<05:52,  1.71it/s]

  4%|▍         | 25/625 [00:14<05:50,  1.71it/s]

  4%|▍         | 26/625 [00:14<05:49,  1.72it/s]

  4%|▍         | 27/625 [00:15<05:43,  1.74it/s]

  4%|▍         | 28/625 [00:16<05:44,  1.73it/s]

  5%|▍         | 29/625 [00:16<05:44,  1.73it/s]

  5%|▍         | 30/625 [00:17<05:45,  1.72it/s]

  5%|▍         | 31/625 [00:17<05:37,  1.76it/s]

  5%|▌         | 32/625 [00:18<05:36,  1.76it/s]

  5%|▌         | 33/625 [00:18<05:32,  1.78it/s]

  5%|▌         | 34/625 [00:19<05:30,  1.79it/s]

  6%|▌         | 35/625 [00:20<05:32,  1.77it/s]

  6%|▌         | 36/625 [00:20<05:42,  1.72it/s]

  6%|▌         | 37/625 [00:21<05:39,  1.73it/s]

  6%|▌         | 38/625 [00:21<05:40,  1.73it/s]

  6%|▌         | 39/625 [00:22<05:42,  1.71it/s]

  6%|▋         | 40/625 [00:22<05:45,  1.69it/s]

  7%|▋         | 41/625 [00:23<05:41,  1.71it/s]

  7%|▋         | 42/625 [00:24<05:37,  1.72it/s]

  7%|▋         | 43/625 [00:24<05:35,  1.73it/s]

  7%|▋         | 44/625 [00:25<05:40,  1.71it/s]

  7%|▋         | 45/625 [00:25<05:37,  1.72it/s]

  7%|▋         | 46/625 [00:26<05:30,  1.75it/s]

  8%|▊         | 47/625 [00:26<05:27,  1.76it/s]

  8%|▊         | 48/625 [00:27<05:29,  1.75it/s]

  8%|▊         | 49/625 [00:28<05:28,  1.75it/s]

  8%|▊         | 50/625 [00:28<05:28,  1.75it/s]

  8%|▊         | 51/625 [00:29<05:27,  1.75it/s]

  8%|▊         | 52/625 [00:29<05:33,  1.72it/s]

  8%|▊         | 53/625 [00:30<05:31,  1.72it/s]

  9%|▊         | 54/625 [00:31<05:31,  1.72it/s]

  9%|▉         | 55/625 [00:31<05:28,  1.73it/s]

  9%|▉         | 56/625 [00:32<05:29,  1.73it/s]

  9%|▉         | 57/625 [00:32<05:24,  1.75it/s]

  9%|▉         | 58/625 [00:33<05:19,  1.77it/s]

  9%|▉         | 59/625 [00:33<05:18,  1.78it/s]

 10%|▉         | 60/625 [00:34<05:22,  1.75it/s]

 10%|▉         | 61/625 [00:35<05:19,  1.76it/s]

 10%|▉         | 62/625 [00:35<05:24,  1.73it/s]

 10%|█         | 63/625 [00:36<05:22,  1.74it/s]

 10%|█         | 64/625 [00:36<05:27,  1.71it/s]

 10%|█         | 65/625 [00:37<05:23,  1.73it/s]

 11%|█         | 66/625 [00:37<05:22,  1.73it/s]

 11%|█         | 67/625 [00:38<05:20,  1.74it/s]

 11%|█         | 68/625 [00:39<05:26,  1.70it/s]

 11%|█         | 69/625 [00:39<05:27,  1.70it/s]

 11%|█         | 70/625 [00:40<05:22,  1.72it/s]

 11%|█▏        | 71/625 [00:40<05:22,  1.72it/s]

 12%|█▏        | 72/625 [00:41<05:23,  1.71it/s]

 12%|█▏        | 73/625 [00:42<05:19,  1.73it/s]

 12%|█▏        | 74/625 [00:42<05:20,  1.72it/s]

 12%|█▏        | 75/625 [00:43<05:19,  1.72it/s]

 12%|█▏        | 76/625 [00:43<05:23,  1.70it/s]

 12%|█▏        | 77/625 [00:44<05:20,  1.71it/s]

 12%|█▏        | 78/625 [00:44<05:18,  1.72it/s]

 13%|█▎        | 79/625 [00:45<05:17,  1.72it/s]

 13%|█▎        | 80/625 [00:46<05:20,  1.70it/s]

 13%|█▎        | 81/625 [00:46<05:20,  1.70it/s]

 13%|█▎        | 82/625 [00:47<05:14,  1.73it/s]

 13%|█▎        | 83/625 [00:47<05:13,  1.73it/s]

 13%|█▎        | 84/625 [00:48<05:14,  1.72it/s]

 14%|█▎        | 85/625 [00:49<05:21,  1.68it/s]

 14%|█▍        | 86/625 [00:49<05:18,  1.69it/s]

 14%|█▍        | 87/625 [00:50<05:14,  1.71it/s]

 14%|█▍        | 88/625 [00:50<05:16,  1.69it/s]

 14%|█▍        | 89/625 [00:51<05:11,  1.72it/s]

 14%|█▍        | 90/625 [00:51<05:10,  1.72it/s]

 15%|█▍        | 91/625 [00:52<05:06,  1.74it/s]

 15%|█▍        | 92/625 [00:53<05:09,  1.72it/s]

 15%|█▍        | 93/625 [00:53<05:08,  1.73it/s]

 15%|█▌        | 94/625 [00:54<05:02,  1.76it/s]

 15%|█▌        | 95/625 [00:54<05:02,  1.75it/s]

 15%|█▌        | 96/625 [00:55<05:05,  1.73it/s]

 16%|█▌        | 97/625 [00:55<05:02,  1.74it/s]

 16%|█▌        | 98/625 [00:56<05:03,  1.74it/s]

 16%|█▌        | 99/625 [00:57<05:02,  1.74it/s]

 16%|█▌        | 100/625 [00:57<05:04,  1.72it/s]

 16%|█▌        | 101/625 [00:58<04:59,  1.75it/s]

 16%|█▋        | 102/625 [00:58<04:58,  1.75it/s]

 16%|█▋        | 103/625 [00:59<04:54,  1.77it/s]

 17%|█▋        | 104/625 [00:59<04:57,  1.75it/s]

 17%|█▋        | 105/625 [01:00<04:59,  1.74it/s]

 17%|█▋        | 106/625 [01:01<04:55,  1.76it/s]

 17%|█▋        | 107/625 [01:01<05:05,  1.69it/s]

 17%|█▋        | 108/625 [01:02<05:07,  1.68it/s]

 17%|█▋        | 109/625 [01:02<05:04,  1.69it/s]

 18%|█▊        | 110/625 [01:03<05:07,  1.67it/s]

 18%|█▊        | 111/625 [01:04<05:08,  1.67it/s]

 18%|█▊        | 112/625 [01:04<05:11,  1.65it/s]

 18%|█▊        | 113/625 [01:05<05:04,  1.68it/s]

 18%|█▊        | 114/625 [01:05<04:58,  1.71it/s]

 18%|█▊        | 115/625 [01:06<04:56,  1.72it/s]

 19%|█▊        | 116/625 [01:07<04:55,  1.72it/s]

 19%|█▊        | 117/625 [01:07<04:52,  1.74it/s]

 19%|█▉        | 118/625 [01:08<04:52,  1.73it/s]

 19%|█▉        | 119/625 [01:08<04:52,  1.73it/s]

 19%|█▉        | 120/625 [01:09<04:54,  1.72it/s]

 19%|█▉        | 121/625 [01:09<04:53,  1.72it/s]

 20%|█▉        | 122/625 [01:10<04:54,  1.71it/s]

 20%|█▉        | 123/625 [01:11<04:47,  1.74it/s]

 20%|█▉        | 124/625 [01:11<04:46,  1.75it/s]

 20%|██        | 125/625 [01:12<04:44,  1.76it/s]

 20%|██        | 126/625 [01:12<04:45,  1.75it/s]

 20%|██        | 127/625 [01:13<04:44,  1.75it/s]

 20%|██        | 128/625 [01:13<04:45,  1.74it/s]

 21%|██        | 129/625 [01:14<04:43,  1.75it/s]

 21%|██        | 130/625 [01:15<04:39,  1.77it/s]

 21%|██        | 131/625 [01:15<04:37,  1.78it/s]

 21%|██        | 132/625 [01:16<04:51,  1.69it/s]

 21%|██▏       | 133/625 [01:16<04:48,  1.71it/s]

 21%|██▏       | 134/625 [01:17<04:46,  1.71it/s]

 22%|██▏       | 135/625 [01:17<04:42,  1.73it/s]

 22%|██▏       | 136/625 [01:18<04:47,  1.70it/s]

 22%|██▏       | 137/625 [01:19<04:48,  1.69it/s]

 22%|██▏       | 138/625 [01:19<04:48,  1.69it/s]

 22%|██▏       | 139/625 [01:20<04:42,  1.72it/s]

 22%|██▏       | 140/625 [01:20<04:45,  1.70it/s]

 23%|██▎       | 141/625 [01:21<04:44,  1.70it/s]

 23%|██▎       | 142/625 [01:22<04:37,  1.74it/s]

 23%|██▎       | 143/625 [01:22<04:38,  1.73it/s]

 23%|██▎       | 144/625 [01:23<04:38,  1.73it/s]

 23%|██▎       | 145/625 [01:23<04:37,  1.73it/s]

 23%|██▎       | 146/625 [01:24<04:39,  1.71it/s]

 24%|██▎       | 147/625 [01:25<04:39,  1.71it/s]

 24%|██▎       | 148/625 [01:25<04:41,  1.69it/s]

 24%|██▍       | 149/625 [01:26<04:36,  1.72it/s]

 24%|██▍       | 150/625 [01:26<04:37,  1.71it/s]

 24%|██▍       | 151/625 [01:27<04:32,  1.74it/s]

 24%|██▍       | 152/625 [01:27<04:33,  1.73it/s]

 24%|██▍       | 153/625 [01:28<04:33,  1.73it/s]

 25%|██▍       | 154/625 [01:29<04:29,  1.75it/s]

 25%|██▍       | 155/625 [01:29<04:30,  1.74it/s]

 25%|██▍       | 156/625 [01:30<04:33,  1.72it/s]

 25%|██▌       | 157/625 [01:30<04:34,  1.70it/s]

 25%|██▌       | 158/625 [01:31<04:35,  1.69it/s]

 25%|██▌       | 159/625 [01:32<04:34,  1.70it/s]

 26%|██▌       | 160/625 [01:32<04:35,  1.69it/s]

 26%|██▌       | 161/625 [01:33<04:30,  1.72it/s]

 26%|██▌       | 162/625 [01:33<04:26,  1.74it/s]

 26%|██▌       | 163/625 [01:34<04:20,  1.77it/s]

 26%|██▌       | 164/625 [01:34<04:21,  1.76it/s]

 26%|██▋       | 165/625 [01:35<04:21,  1.76it/s]

 27%|██▋       | 166/625 [01:35<04:19,  1.77it/s]

 27%|██▋       | 167/625 [01:36<04:21,  1.75it/s]

 27%|██▋       | 168/625 [01:37<04:24,  1.73it/s]

 27%|██▋       | 169/625 [01:37<04:22,  1.74it/s]

 27%|██▋       | 170/625 [01:38<04:23,  1.73it/s]

 27%|██▋       | 171/625 [01:38<04:21,  1.74it/s]

 28%|██▊       | 172/625 [01:39<04:26,  1.70it/s]

 28%|██▊       | 173/625 [01:40<04:31,  1.66it/s]

 28%|██▊       | 174/625 [01:40<04:27,  1.69it/s]

 28%|██▊       | 175/625 [01:41<04:27,  1.68it/s]

 28%|██▊       | 176/625 [01:41<04:29,  1.67it/s]

 28%|██▊       | 177/625 [01:42<04:29,  1.66it/s]

 28%|██▊       | 178/625 [01:43<04:23,  1.69it/s]

 29%|██▊       | 179/625 [01:43<04:23,  1.69it/s]

 29%|██▉       | 180/625 [01:44<04:27,  1.66it/s]

 29%|██▉       | 181/625 [01:44<04:22,  1.69it/s]

 29%|██▉       | 182/625 [01:45<04:20,  1.70it/s]

 29%|██▉       | 183/625 [01:46<04:15,  1.73it/s]

 29%|██▉       | 184/625 [01:46<04:16,  1.72it/s]

 30%|██▉       | 185/625 [01:47<04:11,  1.75it/s]

 30%|██▉       | 186/625 [01:47<04:10,  1.76it/s]

 30%|██▉       | 187/625 [01:48<04:06,  1.77it/s]

 30%|███       | 188/625 [01:48<04:12,  1.73it/s]

 30%|███       | 189/625 [01:49<04:10,  1.74it/s]

 30%|███       | 190/625 [01:49<04:06,  1.76it/s]

 31%|███       | 191/625 [01:50<04:06,  1.76it/s]

 31%|███       | 192/625 [01:51<04:08,  1.74it/s]

 31%|███       | 193/625 [01:51<04:11,  1.72it/s]

 31%|███       | 194/625 [01:52<04:12,  1.71it/s]

 31%|███       | 195/625 [01:52<04:12,  1.71it/s]

 31%|███▏      | 196/625 [01:53<04:11,  1.71it/s]

 32%|███▏      | 197/625 [01:54<04:07,  1.73it/s]

 32%|███▏      | 198/625 [01:54<04:07,  1.72it/s]

 32%|███▏      | 199/625 [01:55<04:05,  1.73it/s]

 32%|███▏      | 200/625 [01:55<04:08,  1.71it/s]

 32%|███▏      | 201/625 [01:56<04:05,  1.73it/s]

 32%|███▏      | 202/625 [01:56<04:00,  1.76it/s]

 32%|███▏      | 203/625 [01:57<04:01,  1.75it/s]

 33%|███▎      | 204/625 [01:58<04:02,  1.74it/s]

 33%|███▎      | 205/625 [01:58<03:59,  1.75it/s]

 33%|███▎      | 206/625 [01:59<03:59,  1.75it/s]

 33%|███▎      | 207/625 [01:59<03:58,  1.75it/s]

 33%|███▎      | 208/625 [02:00<04:01,  1.73it/s]

 33%|███▎      | 209/625 [02:00<03:59,  1.74it/s]

 34%|███▎      | 210/625 [02:01<03:59,  1.73it/s]

 34%|███▍      | 211/625 [02:02<03:56,  1.75it/s]

 34%|███▍      | 212/625 [02:02<03:56,  1.75it/s]

 34%|███▍      | 213/625 [02:03<03:54,  1.76it/s]

 34%|███▍      | 214/625 [02:03<03:52,  1.77it/s]

 34%|███▍      | 215/625 [02:04<03:53,  1.76it/s]

 35%|███▍      | 216/625 [02:04<03:53,  1.75it/s]

 35%|███▍      | 217/625 [02:05<03:51,  1.76it/s]

 35%|███▍      | 218/625 [02:06<03:51,  1.76it/s]

 35%|███▌      | 219/625 [02:06<03:49,  1.77it/s]

 35%|███▌      | 220/625 [02:07<03:51,  1.75it/s]

 35%|███▌      | 221/625 [02:07<03:46,  1.78it/s]

 36%|███▌      | 222/625 [02:08<03:45,  1.79it/s]

 36%|███▌      | 223/625 [02:08<03:43,  1.80it/s]

 36%|███▌      | 224/625 [02:09<03:45,  1.78it/s]

 36%|███▌      | 225/625 [02:09<03:42,  1.80it/s]

 36%|███▌      | 226/625 [02:10<03:40,  1.81it/s]

 36%|███▋      | 227/625 [02:11<03:40,  1.81it/s]

 36%|███▋      | 228/625 [02:11<03:43,  1.78it/s]

 37%|███▋      | 229/625 [02:12<03:40,  1.79it/s]

 37%|███▋      | 230/625 [02:12<03:41,  1.78it/s]

 37%|███▋      | 231/625 [02:13<03:41,  1.78it/s]

 37%|███▋      | 232/625 [02:13<03:45,  1.74it/s]

 37%|███▋      | 233/625 [02:14<03:42,  1.76it/s]

 37%|███▋      | 234/625 [02:15<03:41,  1.77it/s]

 38%|███▊      | 235/625 [02:15<03:40,  1.77it/s]

 38%|███▊      | 236/625 [02:16<03:45,  1.72it/s]

 38%|███▊      | 237/625 [02:16<03:49,  1.69it/s]

 38%|███▊      | 238/625 [02:17<03:46,  1.71it/s]

 38%|███▊      | 239/625 [02:17<03:43,  1.73it/s]

 38%|███▊      | 240/625 [02:18<03:42,  1.73it/s]

 39%|███▊      | 241/625 [02:19<03:40,  1.74it/s]

 39%|███▊      | 242/625 [02:19<03:46,  1.69it/s]

 39%|███▉      | 243/625 [02:20<03:46,  1.68it/s]

 39%|███▉      | 244/625 [02:20<03:47,  1.68it/s]

 39%|███▉      | 245/625 [02:21<03:42,  1.71it/s]

 39%|███▉      | 246/625 [02:22<03:38,  1.73it/s]

 40%|███▉      | 247/625 [02:22<03:37,  1.74it/s]

 40%|███▉      | 248/625 [02:23<03:38,  1.72it/s]

 40%|███▉      | 249/625 [02:23<03:36,  1.73it/s]

 40%|████      | 250/625 [02:24<03:31,  1.77it/s]

 40%|████      | 251/625 [02:24<03:31,  1.77it/s]

 40%|████      | 252/625 [02:25<03:32,  1.75it/s]

 40%|████      | 253/625 [02:26<03:30,  1.76it/s]

 41%|████      | 254/625 [02:26<03:30,  1.76it/s]

 41%|████      | 255/625 [02:27<03:29,  1.77it/s]

 41%|████      | 256/625 [02:27<03:29,  1.76it/s]

 41%|████      | 257/625 [02:28<03:24,  1.80it/s]

 41%|████▏     | 258/625 [02:28<03:20,  1.83it/s]

 41%|████▏     | 259/625 [02:29<03:19,  1.83it/s]

 42%|████▏     | 260/625 [02:29<03:24,  1.79it/s]

 42%|████▏     | 261/625 [02:30<03:29,  1.74it/s]

 42%|████▏     | 262/625 [02:31<03:28,  1.74it/s]

 42%|████▏     | 263/625 [02:31<03:27,  1.74it/s]

 42%|████▏     | 264/625 [02:32<03:27,  1.74it/s]

 42%|████▏     | 265/625 [02:32<03:24,  1.76it/s]

 43%|████▎     | 266/625 [02:33<03:24,  1.75it/s]

 43%|████▎     | 267/625 [02:33<03:22,  1.77it/s]

 43%|████▎     | 268/625 [02:34<03:21,  1.77it/s]

 43%|████▎     | 269/625 [02:35<03:17,  1.80it/s]

 43%|████▎     | 270/625 [02:35<03:16,  1.81it/s]

 43%|████▎     | 271/625 [02:36<03:14,  1.82it/s]

 44%|████▎     | 272/625 [02:36<03:15,  1.80it/s]

 44%|████▎     | 273/625 [02:37<03:14,  1.81it/s]

 44%|████▍     | 274/625 [02:37<03:09,  1.85it/s]

 44%|████▍     | 275/625 [02:38<03:09,  1.85it/s]

 44%|████▍     | 276/625 [02:38<03:10,  1.84it/s]

 44%|████▍     | 277/625 [02:39<03:10,  1.83it/s]

 44%|████▍     | 278/625 [02:39<03:11,  1.81it/s]

 45%|████▍     | 279/625 [02:40<03:12,  1.80it/s]

 45%|████▍     | 280/625 [02:41<03:14,  1.77it/s]

 45%|████▍     | 281/625 [02:41<03:12,  1.79it/s]

 45%|████▌     | 282/625 [02:42<03:10,  1.80it/s]

 45%|████▌     | 283/625 [02:42<03:08,  1.81it/s]

 45%|████▌     | 284/625 [02:43<03:14,  1.76it/s]

 46%|████▌     | 285/625 [02:43<03:12,  1.77it/s]

 46%|████▌     | 286/625 [02:44<03:10,  1.78it/s]

 46%|████▌     | 287/625 [02:45<03:08,  1.79it/s]

 46%|████▌     | 288/625 [02:45<03:10,  1.77it/s]

 46%|████▌     | 289/625 [02:46<03:07,  1.79it/s]

 46%|████▋     | 290/625 [02:46<03:09,  1.77it/s]

 47%|████▋     | 291/625 [02:47<03:12,  1.73it/s]

 47%|████▋     | 292/625 [02:47<03:11,  1.74it/s]

 47%|████▋     | 293/625 [02:48<03:07,  1.77it/s]

 47%|████▋     | 294/625 [02:49<03:05,  1.78it/s]

 47%|████▋     | 295/625 [02:49<03:03,  1.80it/s]

 47%|████▋     | 296/625 [02:50<03:05,  1.77it/s]

 48%|████▊     | 297/625 [02:50<03:04,  1.78it/s]

 48%|████▊     | 298/625 [02:51<03:01,  1.80it/s]

 48%|████▊     | 299/625 [02:51<03:03,  1.78it/s]

 48%|████▊     | 300/625 [02:52<03:04,  1.76it/s]

 48%|████▊     | 301/625 [02:52<03:02,  1.77it/s]

 48%|████▊     | 302/625 [02:53<03:04,  1.75it/s]

 48%|████▊     | 303/625 [02:54<03:02,  1.77it/s]

 49%|████▊     | 304/625 [02:54<03:04,  1.74it/s]

 49%|████▉     | 305/625 [02:55<03:01,  1.77it/s]

 49%|████▉     | 306/625 [02:55<03:00,  1.77it/s]

 49%|████▉     | 307/625 [02:56<02:57,  1.80it/s]

 49%|████▉     | 308/625 [02:56<02:56,  1.80it/s]

 49%|████▉     | 309/625 [02:57<02:56,  1.79it/s]

 50%|████▉     | 310/625 [02:58<02:54,  1.81it/s]

 50%|████▉     | 311/625 [02:58<02:54,  1.80it/s]

 50%|████▉     | 312/625 [02:59<02:56,  1.78it/s]

 50%|█████     | 313/625 [02:59<02:56,  1.77it/s]

 50%|█████     | 314/625 [03:00<03:00,  1.73it/s]

 50%|█████     | 315/625 [03:00<03:00,  1.72it/s]

 51%|█████     | 316/625 [03:01<03:01,  1.70it/s]

 51%|█████     | 317/625 [03:02<03:00,  1.71it/s]

 51%|█████     | 318/625 [03:02<02:57,  1.73it/s]

 51%|█████     | 319/625 [03:03<02:52,  1.77it/s]

 51%|█████     | 320/625 [03:03<02:54,  1.75it/s]

 51%|█████▏    | 321/625 [03:04<02:52,  1.76it/s]

 52%|█████▏    | 322/625 [03:04<02:49,  1.79it/s]

 52%|█████▏    | 323/625 [03:05<02:49,  1.79it/s]

 52%|█████▏    | 324/625 [03:05<02:47,  1.79it/s]

 52%|█████▏    | 325/625 [03:06<02:47,  1.79it/s]

 52%|█████▏    | 326/625 [03:07<02:47,  1.78it/s]

 52%|█████▏    | 327/625 [03:07<02:46,  1.79it/s]

 52%|█████▏    | 328/625 [03:08<02:48,  1.77it/s]

 53%|█████▎    | 329/625 [03:08<02:44,  1.80it/s]

 53%|█████▎    | 330/625 [03:09<02:42,  1.82it/s]

 53%|█████▎    | 331/625 [03:09<02:39,  1.84it/s]

 53%|█████▎    | 332/625 [03:10<02:40,  1.82it/s]

 53%|█████▎    | 333/625 [03:10<02:41,  1.81it/s]

 53%|█████▎    | 334/625 [03:11<02:38,  1.84it/s]

 54%|█████▎    | 335/625 [03:12<02:38,  1.83it/s]

 54%|█████▍    | 336/625 [03:12<02:39,  1.81it/s]

 54%|█████▍    | 337/625 [03:13<02:38,  1.82it/s]

 54%|█████▍    | 338/625 [03:13<02:40,  1.79it/s]

 54%|█████▍    | 339/625 [03:14<02:40,  1.79it/s]

 54%|█████▍    | 340/625 [03:14<02:44,  1.73it/s]

 55%|█████▍    | 341/625 [03:15<02:43,  1.74it/s]

 55%|█████▍    | 342/625 [03:16<02:43,  1.73it/s]

 55%|█████▍    | 343/625 [03:16<02:40,  1.75it/s]

 55%|█████▌    | 344/625 [03:17<02:41,  1.74it/s]

 55%|█████▌    | 345/625 [03:17<02:39,  1.76it/s]

 55%|█████▌    | 346/625 [03:18<02:36,  1.78it/s]

 56%|█████▌    | 347/625 [03:18<02:35,  1.78it/s]

 56%|█████▌    | 348/625 [03:19<02:36,  1.77it/s]

 56%|█████▌    | 349/625 [03:20<02:35,  1.78it/s]

 56%|█████▌    | 350/625 [03:20<02:34,  1.78it/s]

 56%|█████▌    | 351/625 [03:21<02:31,  1.81it/s]

 56%|█████▋    | 352/625 [03:21<02:31,  1.81it/s]

 56%|█████▋    | 353/625 [03:22<02:28,  1.83it/s]

 57%|█████▋    | 354/625 [03:22<02:28,  1.83it/s]

 57%|█████▋    | 355/625 [03:23<02:30,  1.79it/s]

 57%|█████▋    | 356/625 [03:23<02:31,  1.78it/s]

 57%|█████▋    | 357/625 [03:24<02:30,  1.78it/s]

 57%|█████▋    | 358/625 [03:24<02:26,  1.82it/s]

 57%|█████▋    | 359/625 [03:25<02:28,  1.79it/s]

 58%|█████▊    | 360/625 [03:26<02:27,  1.80it/s]

 58%|█████▊    | 361/625 [03:26<02:23,  1.84it/s]

 58%|█████▊    | 362/625 [03:27<02:28,  1.77it/s]

 58%|█████▊    | 363/625 [03:27<02:26,  1.79it/s]

 58%|█████▊    | 364/625 [03:28<02:25,  1.79it/s]

 58%|█████▊    | 365/625 [03:28<02:24,  1.80it/s]

 59%|█████▊    | 366/625 [03:29<02:22,  1.81it/s]

 59%|█████▊    | 367/625 [03:29<02:21,  1.82it/s]

 59%|█████▉    | 368/625 [03:30<02:24,  1.77it/s]

 59%|█████▉    | 369/625 [03:31<02:25,  1.77it/s]

 59%|█████▉    | 370/625 [03:31<02:24,  1.77it/s]

 59%|█████▉    | 371/625 [03:32<02:23,  1.77it/s]

 60%|█████▉    | 372/625 [03:32<02:23,  1.77it/s]

 60%|█████▉    | 373/625 [03:33<02:22,  1.76it/s]

 60%|█████▉    | 374/625 [03:33<02:22,  1.76it/s]

 60%|██████    | 375/625 [03:34<02:25,  1.72it/s]

 60%|██████    | 376/625 [03:35<02:26,  1.70it/s]

 60%|██████    | 377/625 [03:35<02:24,  1.72it/s]

 60%|██████    | 378/625 [03:36<02:22,  1.73it/s]

 61%|██████    | 379/625 [03:36<02:19,  1.76it/s]

 61%|██████    | 380/625 [03:37<02:20,  1.74it/s]

 61%|██████    | 381/625 [03:38<02:19,  1.74it/s]

 61%|██████    | 382/625 [03:38<02:17,  1.77it/s]

 61%|██████▏   | 383/625 [03:39<02:16,  1.77it/s]

 61%|██████▏   | 384/625 [03:39<02:18,  1.73it/s]

 62%|██████▏   | 385/625 [03:40<02:17,  1.74it/s]

 62%|██████▏   | 386/625 [03:40<02:16,  1.75it/s]

 62%|██████▏   | 387/625 [03:41<02:13,  1.78it/s]

 62%|██████▏   | 388/625 [03:41<02:14,  1.76it/s]

 62%|██████▏   | 389/625 [03:42<02:11,  1.79it/s]

 62%|██████▏   | 390/625 [03:43<02:11,  1.79it/s]

 63%|██████▎   | 391/625 [03:43<02:09,  1.80it/s]

 63%|██████▎   | 392/625 [03:44<02:09,  1.79it/s]

 63%|██████▎   | 393/625 [03:44<02:11,  1.77it/s]

 63%|██████▎   | 394/625 [03:45<02:09,  1.79it/s]

 63%|██████▎   | 395/625 [03:45<02:07,  1.80it/s]

 63%|██████▎   | 396/625 [03:46<02:11,  1.74it/s]

 64%|██████▎   | 397/625 [03:47<02:10,  1.75it/s]

 64%|██████▎   | 398/625 [03:47<02:09,  1.75it/s]

 64%|██████▍   | 399/625 [03:48<02:08,  1.76it/s]

 64%|██████▍   | 400/625 [03:48<02:09,  1.74it/s]

 64%|██████▍   | 401/625 [03:49<02:06,  1.77it/s]

 64%|██████▍   | 402/625 [03:49<02:05,  1.78it/s]

 64%|██████▍   | 403/625 [03:50<02:02,  1.81it/s]

 65%|██████▍   | 404/625 [03:50<02:03,  1.79it/s]

 65%|██████▍   | 405/625 [03:51<02:01,  1.80it/s]

 65%|██████▍   | 406/625 [03:52<02:00,  1.82it/s]

 65%|██████▌   | 407/625 [03:52<02:01,  1.80it/s]

 65%|██████▌   | 408/625 [03:53<02:02,  1.77it/s]

 65%|██████▌   | 409/625 [03:53<02:01,  1.77it/s]

 66%|██████▌   | 410/625 [03:54<02:00,  1.78it/s]

 66%|██████▌   | 411/625 [03:54<02:00,  1.78it/s]

 66%|██████▌   | 412/625 [03:55<02:01,  1.75it/s]

 66%|██████▌   | 413/625 [03:56<01:58,  1.79it/s]

 66%|██████▌   | 414/625 [03:56<01:57,  1.79it/s]

 66%|██████▋   | 415/625 [03:57<01:57,  1.79it/s]

 67%|██████▋   | 416/625 [03:57<01:57,  1.78it/s]

 67%|██████▋   | 417/625 [03:58<01:55,  1.81it/s]

 67%|██████▋   | 418/625 [03:58<01:53,  1.82it/s]

 67%|██████▋   | 419/625 [03:59<01:54,  1.80it/s]

 67%|██████▋   | 420/625 [03:59<01:54,  1.79it/s]

 67%|██████▋   | 421/625 [04:00<01:54,  1.78it/s]

 68%|██████▊   | 422/625 [04:01<01:55,  1.76it/s]

 68%|██████▊   | 423/625 [04:01<01:54,  1.76it/s]

 68%|██████▊   | 424/625 [04:02<01:54,  1.75it/s]

 68%|██████▊   | 425/625 [04:02<01:51,  1.79it/s]

 68%|██████▊   | 426/625 [04:03<01:49,  1.81it/s]

 68%|██████▊   | 427/625 [04:03<01:47,  1.84it/s]

 68%|██████▊   | 428/625 [04:04<01:47,  1.83it/s]

 69%|██████▊   | 429/625 [04:04<01:46,  1.84it/s]

 69%|██████▉   | 430/625 [04:05<01:45,  1.85it/s]

 69%|██████▉   | 431/625 [04:05<01:46,  1.83it/s]

 69%|██████▉   | 432/625 [04:06<01:47,  1.80it/s]

 69%|██████▉   | 433/625 [04:07<01:45,  1.81it/s]

 69%|██████▉   | 434/625 [04:07<01:45,  1.81it/s]

 70%|██████▉   | 435/625 [04:08<01:44,  1.81it/s]

 70%|██████▉   | 436/625 [04:08<01:47,  1.76it/s]

 70%|██████▉   | 437/625 [04:09<01:46,  1.77it/s]

 70%|███████   | 438/625 [04:09<01:46,  1.76it/s]

 70%|███████   | 439/625 [04:10<01:45,  1.76it/s]

 70%|███████   | 440/625 [04:11<01:46,  1.73it/s]

 71%|███████   | 441/625 [04:11<01:46,  1.72it/s]

 71%|███████   | 442/625 [04:12<01:46,  1.71it/s]

 71%|███████   | 443/625 [04:12<01:47,  1.69it/s]

 71%|███████   | 444/625 [04:13<01:48,  1.67it/s]

 71%|███████   | 445/625 [04:14<01:46,  1.69it/s]

 71%|███████▏  | 446/625 [04:14<01:46,  1.68it/s]

 72%|███████▏  | 447/625 [04:15<01:45,  1.69it/s]

 72%|███████▏  | 448/625 [04:15<01:44,  1.69it/s]

 72%|███████▏  | 449/625 [04:16<01:44,  1.69it/s]

 72%|███████▏  | 450/625 [04:17<01:43,  1.69it/s]

 72%|███████▏  | 451/625 [04:17<01:43,  1.68it/s]

 72%|███████▏  | 452/625 [04:18<01:45,  1.65it/s]

 72%|███████▏  | 453/625 [04:18<01:44,  1.64it/s]

 73%|███████▎  | 454/625 [04:19<01:42,  1.67it/s]

 73%|███████▎  | 455/625 [04:20<01:39,  1.71it/s]

 73%|███████▎  | 456/625 [04:20<01:40,  1.69it/s]

 73%|███████▎  | 457/625 [04:21<01:38,  1.71it/s]

 73%|███████▎  | 458/625 [04:21<01:37,  1.72it/s]

 73%|███████▎  | 459/625 [04:22<01:34,  1.75it/s]

 74%|███████▎  | 460/625 [04:22<01:35,  1.74it/s]

 74%|███████▍  | 461/625 [04:23<01:32,  1.76it/s]

 74%|███████▍  | 462/625 [04:24<01:33,  1.75it/s]

 74%|███████▍  | 463/625 [04:24<01:31,  1.77it/s]

 74%|███████▍  | 464/625 [04:25<01:32,  1.74it/s]

 74%|███████▍  | 465/625 [04:25<01:32,  1.74it/s]

 75%|███████▍  | 466/625 [04:26<01:31,  1.74it/s]

 75%|███████▍  | 467/625 [04:26<01:29,  1.77it/s]

 75%|███████▍  | 468/625 [04:27<01:30,  1.73it/s]

 75%|███████▌  | 469/625 [04:28<01:31,  1.71it/s]

 75%|███████▌  | 470/625 [04:28<01:31,  1.69it/s]

 75%|███████▌  | 471/625 [04:29<01:29,  1.71it/s]

 76%|███████▌  | 472/625 [04:29<01:29,  1.71it/s]

 76%|███████▌  | 473/625 [04:30<01:27,  1.73it/s]

 76%|███████▌  | 474/625 [04:31<01:27,  1.73it/s]

 76%|███████▌  | 475/625 [04:31<01:26,  1.73it/s]

 76%|███████▌  | 476/625 [04:32<01:28,  1.69it/s]

 76%|███████▋  | 477/625 [04:32<01:27,  1.70it/s]

 76%|███████▋  | 478/625 [04:33<01:25,  1.73it/s]

 77%|███████▋  | 479/625 [04:33<01:23,  1.74it/s]

 77%|███████▋  | 480/625 [04:34<01:23,  1.74it/s]

 77%|███████▋  | 481/625 [04:35<01:21,  1.76it/s]

 77%|███████▋  | 482/625 [04:35<01:21,  1.76it/s]

 77%|███████▋  | 483/625 [04:36<01:19,  1.78it/s]

 77%|███████▋  | 484/625 [04:36<01:19,  1.77it/s]

 78%|███████▊  | 485/625 [04:37<01:18,  1.78it/s]

 78%|███████▊  | 486/625 [04:37<01:17,  1.79it/s]

 78%|███████▊  | 487/625 [04:38<01:15,  1.82it/s]

 78%|███████▊  | 488/625 [04:38<01:15,  1.81it/s]

 78%|███████▊  | 489/625 [04:39<01:15,  1.81it/s]

 78%|███████▊  | 490/625 [04:39<01:13,  1.83it/s]

 79%|███████▊  | 491/625 [04:40<01:13,  1.83it/s]

 79%|███████▊  | 492/625 [04:41<01:13,  1.80it/s]

 79%|███████▉  | 493/625 [04:41<01:13,  1.80it/s]

 79%|███████▉  | 494/625 [04:42<01:13,  1.79it/s]

 79%|███████▉  | 495/625 [04:42<01:13,  1.77it/s]

 79%|███████▉  | 496/625 [04:43<01:13,  1.77it/s]

 80%|███████▉  | 497/625 [04:43<01:11,  1.79it/s]

 80%|███████▉  | 498/625 [04:44<01:10,  1.80it/s]

 80%|███████▉  | 499/625 [04:45<01:09,  1.81it/s]

 80%|████████  | 500/625 [04:45<01:09,  1.79it/s]

 80%|████████  | 501/625 [04:46<01:10,  1.76it/s]

 80%|████████  | 502/625 [04:46<01:09,  1.77it/s]

 80%|████████  | 503/625 [04:47<01:10,  1.74it/s]

 81%|████████  | 504/625 [04:47<01:10,  1.71it/s]

 81%|████████  | 505/625 [04:48<01:09,  1.72it/s]

 81%|████████  | 506/625 [04:49<01:09,  1.72it/s]

 81%|████████  | 507/625 [04:49<01:09,  1.71it/s]

 81%|████████▏ | 508/625 [04:50<01:08,  1.70it/s]

 81%|████████▏ | 509/625 [04:50<01:06,  1.74it/s]

 82%|████████▏ | 510/625 [04:51<01:05,  1.75it/s]

 82%|████████▏ | 511/625 [04:51<01:03,  1.80it/s]

 82%|████████▏ | 512/625 [04:52<01:03,  1.78it/s]

 82%|████████▏ | 513/625 [04:53<01:02,  1.80it/s]

 82%|████████▏ | 514/625 [04:53<01:01,  1.81it/s]

 82%|████████▏ | 515/625 [04:54<01:00,  1.82it/s]

 83%|████████▎ | 516/625 [04:54<01:00,  1.79it/s]

 83%|████████▎ | 517/625 [04:55<00:59,  1.80it/s]

 83%|████████▎ | 518/625 [04:55<00:59,  1.80it/s]

 83%|████████▎ | 519/625 [04:56<00:58,  1.82it/s]

 83%|████████▎ | 520/625 [04:56<00:58,  1.80it/s]

 83%|████████▎ | 521/625 [04:57<00:57,  1.80it/s]

 84%|████████▎ | 522/625 [04:58<00:57,  1.78it/s]

 84%|████████▎ | 523/625 [04:58<00:57,  1.78it/s]

 84%|████████▍ | 524/625 [04:59<00:57,  1.75it/s]

 84%|████████▍ | 525/625 [04:59<00:56,  1.76it/s]

 84%|████████▍ | 526/625 [05:00<00:56,  1.74it/s]

 84%|████████▍ | 527/625 [05:00<00:56,  1.73it/s]

 84%|████████▍ | 528/625 [05:01<00:56,  1.71it/s]

 85%|████████▍ | 529/625 [05:02<00:55,  1.72it/s]

 85%|████████▍ | 530/625 [05:02<00:55,  1.71it/s]

 85%|████████▍ | 531/625 [05:03<00:54,  1.73it/s]

 85%|████████▌ | 532/625 [05:03<00:54,  1.72it/s]

 85%|████████▌ | 533/625 [05:04<00:52,  1.76it/s]

 85%|████████▌ | 534/625 [05:04<00:51,  1.77it/s]

 86%|████████▌ | 535/625 [05:05<00:51,  1.76it/s]

 86%|████████▌ | 536/625 [05:06<00:51,  1.71it/s]

 86%|████████▌ | 537/625 [05:06<00:51,  1.69it/s]

 86%|████████▌ | 538/625 [05:07<00:50,  1.72it/s]

 86%|████████▌ | 539/625 [05:07<00:49,  1.73it/s]

 86%|████████▋ | 540/625 [05:08<00:49,  1.73it/s]

 87%|████████▋ | 541/625 [05:09<00:48,  1.73it/s]

 87%|████████▋ | 542/625 [05:09<00:47,  1.74it/s]

 87%|████████▋ | 543/625 [05:10<00:46,  1.76it/s]

 87%|████████▋ | 544/625 [05:10<00:46,  1.74it/s]

 87%|████████▋ | 545/625 [05:11<00:45,  1.77it/s]

 87%|████████▋ | 546/625 [05:11<00:44,  1.77it/s]

 88%|████████▊ | 547/625 [05:12<00:44,  1.77it/s]

 88%|████████▊ | 548/625 [05:13<00:44,  1.75it/s]

 88%|████████▊ | 549/625 [05:13<00:43,  1.75it/s]

 88%|████████▊ | 550/625 [05:14<00:42,  1.77it/s]

 88%|████████▊ | 551/625 [05:14<00:41,  1.77it/s]

 88%|████████▊ | 552/625 [05:15<00:41,  1.75it/s]

 88%|████████▊ | 553/625 [05:15<00:40,  1.76it/s]

 89%|████████▊ | 554/625 [05:16<00:41,  1.73it/s]

 89%|████████▉ | 555/625 [05:17<00:41,  1.69it/s]

 89%|████████▉ | 556/625 [05:17<00:41,  1.64it/s]

 89%|████████▉ | 557/625 [05:18<00:40,  1.67it/s]

 89%|████████▉ | 558/625 [05:18<00:39,  1.68it/s]

 89%|████████▉ | 559/625 [05:19<00:39,  1.68it/s]

 90%|████████▉ | 560/625 [05:20<00:38,  1.67it/s]

 90%|████████▉ | 561/625 [05:20<00:37,  1.71it/s]

 90%|████████▉ | 562/625 [05:21<00:36,  1.75it/s]

 90%|█████████ | 563/625 [05:21<00:35,  1.76it/s]

 90%|█████████ | 564/625 [05:22<00:34,  1.77it/s]

 90%|█████████ | 565/625 [05:22<00:33,  1.78it/s]

 91%|█████████ | 566/625 [05:23<00:33,  1.75it/s]

 91%|█████████ | 567/625 [05:24<00:32,  1.76it/s]

 91%|█████████ | 568/625 [05:24<00:32,  1.75it/s]

 91%|█████████ | 569/625 [05:25<00:31,  1.77it/s]

 91%|█████████ | 570/625 [05:25<00:30,  1.79it/s]

 91%|█████████▏| 571/625 [05:26<00:30,  1.77it/s]

 92%|█████████▏| 572/625 [05:26<00:30,  1.76it/s]

 92%|█████████▏| 573/625 [05:27<00:29,  1.77it/s]

 92%|█████████▏| 574/625 [05:27<00:28,  1.79it/s]

 92%|█████████▏| 575/625 [05:28<00:27,  1.79it/s]

 92%|█████████▏| 576/625 [05:29<00:27,  1.77it/s]

 92%|█████████▏| 577/625 [05:29<00:27,  1.77it/s]

 92%|█████████▏| 578/625 [05:30<00:26,  1.76it/s]

 93%|█████████▎| 579/625 [05:30<00:26,  1.74it/s]

 93%|█████████▎| 580/625 [05:31<00:26,  1.71it/s]

 93%|█████████▎| 581/625 [05:31<00:25,  1.73it/s]

 93%|█████████▎| 582/625 [05:32<00:25,  1.71it/s]

 93%|█████████▎| 583/625 [05:33<00:24,  1.70it/s]

 93%|█████████▎| 584/625 [05:33<00:23,  1.71it/s]

 94%|█████████▎| 585/625 [05:34<00:22,  1.74it/s]

 94%|█████████▍| 586/625 [05:34<00:21,  1.77it/s]

 94%|█████████▍| 587/625 [05:35<00:21,  1.77it/s]

 94%|█████████▍| 588/625 [05:36<00:21,  1.74it/s]

 94%|█████████▍| 589/625 [05:36<00:20,  1.76it/s]

 94%|█████████▍| 590/625 [05:37<00:19,  1.75it/s]

 95%|█████████▍| 591/625 [05:37<00:19,  1.75it/s]

 95%|█████████▍| 592/625 [05:38<00:19,  1.73it/s]

 95%|█████████▍| 593/625 [05:38<00:18,  1.76it/s]

 95%|█████████▌| 594/625 [05:39<00:17,  1.77it/s]

 95%|█████████▌| 595/625 [05:39<00:16,  1.79it/s]

 95%|█████████▌| 596/625 [05:40<00:16,  1.77it/s]

 96%|█████████▌| 597/625 [05:41<00:15,  1.77it/s]

 96%|█████████▌| 598/625 [05:41<00:15,  1.79it/s]

 96%|█████████▌| 599/625 [05:42<00:14,  1.80it/s]

 96%|█████████▌| 600/625 [05:42<00:14,  1.78it/s]

 96%|█████████▌| 601/625 [05:43<00:13,  1.78it/s]

 96%|█████████▋| 602/625 [05:43<00:13,  1.77it/s]

 96%|█████████▋| 603/625 [05:44<00:12,  1.77it/s]

 97%|█████████▋| 604/625 [05:45<00:12,  1.74it/s]

 97%|█████████▋| 605/625 [05:45<00:11,  1.75it/s]

 97%|█████████▋| 606/625 [05:46<00:10,  1.77it/s]

 97%|█████████▋| 607/625 [05:46<00:10,  1.78it/s]

 97%|█████████▋| 608/625 [05:47<00:09,  1.78it/s]

 97%|█████████▋| 609/625 [05:47<00:08,  1.78it/s]

 98%|█████████▊| 610/625 [05:48<00:08,  1.80it/s]

 98%|█████████▊| 611/625 [05:48<00:07,  1.78it/s]

 98%|█████████▊| 612/625 [05:49<00:07,  1.76it/s]

 98%|█████████▊| 613/625 [05:50<00:06,  1.77it/s]

 98%|█████████▊| 614/625 [05:50<00:06,  1.76it/s]

 98%|█████████▊| 615/625 [05:51<00:05,  1.76it/s]

 99%|█████████▊| 616/625 [05:51<00:05,  1.74it/s]

 99%|█████████▊| 617/625 [05:52<00:04,  1.76it/s]

 99%|█████████▉| 618/625 [05:52<00:03,  1.76it/s]

 99%|█████████▉| 619/625 [05:53<00:03,  1.75it/s]

 99%|█████████▉| 620/625 [05:54<00:02,  1.74it/s]

 99%|█████████▉| 621/625 [05:54<00:02,  1.71it/s]

100%|█████████▉| 622/625 [05:55<00:01,  1.73it/s]

100%|█████████▉| 623/625 [05:55<00:01,  1.73it/s]

100%|█████████▉| 624/625 [05:56<00:00,  1.72it/s]

100%|██████████| 625/625 [05:57<00:00,  1.72it/s]

100%|██████████| 625/625 [05:57<00:00,  1.75it/s]

  0%|          | 0/25 [00:00<?, ?it/s]

  4%|▍         | 1/25 [00:00<00:18,  1.28it/s]

 16%|█▌        | 4/25 [00:00<00:04,  4.91it/s]

 20%|██        | 5/25 [00:01<00:03,  5.67it/s]

 36%|███▌      | 9/25 [00:01<00:01, 11.77it/s]

 52%|█████▏    | 13/25 [00:01<00:00, 16.96it/s]

 64%|██████▍   | 16/25 [00:01<00:00, 17.14it/s]

 80%|████████  | 20/25 [00:01<00:00, 20.96it/s]

 92%|█████████▏| 23/25 [00:01<00:00, 20.05it/s]

100%|██████████| 25/25 [00:01<00:00, 13.59it/s]

/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: divide by zero encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))
/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: invalid value encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))

   haldane_4x4 done in 396 s

benzene: norb=6  occ=3  k-points=1
   benzene done in 0 s

coronene: norb=24  occ=12  k-points=1

/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: divide by zero encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))
/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: invalid value encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))

   coronene done in 9 s

/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: divide by zero encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))
/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: invalid value encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))

,system,norb,N_e,k_points,molecule,Tr_g_4index,QM_fluct_sum,BC_fluct_sum,max_dropped_imag,Tr_g_TBLR,Tr_g_bond_Eq1,Omega_4index,Omega_loops,C_4index,C_loops,C_loops_before_cut,sum_abs_C_loops,n_loop_rows,rmax
0,haldane,2,1,10000,False,0.451355,0.451355,0.413497,1.28867e-14,0.451355,0.451355,0.413497,0.413442,1,0.999867,0.999867,1.3088,170744,6
1,haldane_4x4,32,16,625,False,0.451355,0.451355,0.413497,1.29734e-18,0.451355,0.451355,0.413497,0.412945,1,0.998666,0.999997,1.29717,124608,2
2,benzene,6,3,1,True,0.333333,0.333333,-4.64366e-10,5.91042e-15,0.333333,0.333333,-4.64366e-10,0,0,0,5.81311e-16,0,0,NaN
3,coronene,24,12,1,True,0.535519,0.535519,-4.45543e-10,1.28775e-16,0.535519,0.535519,-4.45543e-10,6.45317e-16,0,1.84297e-14,1.82577e-14,15.713,10848,NaN

## Fluctuation-resolved quantum metric and Berry curvature

In [8]:
for name in summary.system:
    for f in ("fluctuation_quantum_metric.csv", "fluctuation_berry_curvature.csv"):
        print(f"--- {name}: {f}")
        display(pd.read_csv(os.path.join(OUT, name, f)))

--- haldane: fluctuation_quantum_metric.csv

   1orb    QM1orb  2orb     QM2orb  3orb  QM3orb  4orb  QM4orb
0  aaaa 0.0280943  aaab  0.0124825  aabc       0  abcd       0
1   NaN       NaN  aaba  0.0124825  abac       0   NaN     NaN
2   NaN       NaN  aabb 0.00704145  abbc       0   NaN     NaN
3   NaN       NaN  abaa  0.0124825  abca       0   NaN     NaN
4   NaN       NaN  abab   0.338194  abcb       0   NaN     NaN
5   NaN       NaN  abba  0.0280943  abcc       0   NaN     NaN
6   NaN       NaN  abbb  0.0124825   NaN     NaN   NaN     NaN

--- haldane: fluctuation_berry_curvature.csv

   1orb      BC1orb  2orb       BC2orb  3orb  BC3orb  4orb  BC4orb
0  aaaa 3.83189e-21  aaab    0.0547984  aabc       0  abcd       0
1   NaN         NaN  aaba    0.0547984  abac       0   NaN     NaN
2   NaN         NaN  aabb -5.56152e-18  abbc       0   NaN     NaN
3   NaN         NaN  abaa    0.0547984  abca       0   NaN     NaN
4   NaN         NaN  abab     0.194303  abcb       0   NaN     NaN
5   NaN         NaN  abba  3.83189e-21  abcc       0   NaN     NaN
6   NaN         NaN  abbb    0.0547984   NaN     NaN   NaN     NaN

--- haldane_4x4: fluctuation_quantum_metric.csv

   1orb  QM1orb  2orb    QM2orb  3orb     QM3orb  4orb   QM4orb
0  aaaa       0  aaab         0  aabc -0.0313683  abcd 0.228632
1   NaN     NaN  aaba         0  abac  0.0284182   NaN      NaN
2   NaN     NaN  aabb 0.0313628  abbc          0   NaN      NaN
3   NaN     NaN  abaa         0  abca          0   NaN      NaN
4   NaN     NaN  abab   0.19726  abcb  0.0284182   NaN      NaN
5   NaN     NaN  abba         0  abcc -0.0313683   NaN      NaN
6   NaN     NaN  abbb         0   NaN        NaN   NaN      NaN

--- haldane_4x4: fluctuation_berry_curvature.csv

   1orb  BC1orb  2orb      BC2orb  3orb      BC3orb  4orb   BC4orb
0  aaaa       0  aaab           0  aabc 2.15141e-06  abcd 0.121749
1   NaN     NaN  aaba           0  abac    0.145872   NaN      NaN
2   NaN     NaN  aabb 3.09247e-21  abbc           0   NaN      NaN
3   NaN     NaN  abaa           0  abca           0   NaN      NaN
4   NaN     NaN  abab 9.36154e-18  abcb    0.145872   NaN      NaN
5   NaN     NaN  abba           0  abcc 2.15141e-06   NaN      NaN
6   NaN     NaN  abbb           0   NaN         NaN   NaN      NaN

--- benzene: fluctuation_quantum_metric.csv

   1orb  QM1orb  2orb    QM2orb  3orb     QM3orb  4orb   QM4orb
0  aaaa       0  aaab         0  aabc -0.0398702  abcd 0.129613
1   NaN     NaN  aaba         0  abac   0.007952   NaN      NaN
2   NaN     NaN  aabb 0.0741154  abbc          0   NaN      NaN
3   NaN     NaN  abaa         0  abca          0   NaN      NaN
4   NaN     NaN  abab  0.193442  abcb   0.007952   NaN      NaN
5   NaN     NaN  abba         0  abcc -0.0398702   NaN      NaN
6   NaN     NaN  abbb         0   NaN        NaN   NaN      NaN

--- benzene: fluctuation_berry_curvature.csv

   1orb  BC1orb  2orb       BC2orb  3orb    BC3orb  4orb     BC4orb
0  aaaa       0  aaab            0  aabc -0.019025  abcd -0.0786807
1   NaN     NaN  aaba            0  abac 0.0583654   NaN        NaN
2   NaN     NaN  aabb -8.34018e-19  abbc         0   NaN        NaN
3   NaN     NaN  abaa            0  abca         0   NaN        NaN
4   NaN     NaN  abab  9.54821e-19  abcb 0.0583654   NaN        NaN
5   NaN     NaN  abba            0  abcc -0.019025   NaN        NaN
6   NaN     NaN  abbb            0   NaN       NaN   NaN        NaN

--- coronene: fluctuation_quantum_metric.csv

   1orb  QM1orb  2orb    QM2orb  3orb     QM3orb  4orb   QM4orb
0  aaaa       0  aaab         0  aabc -0.0236888  abcd 0.235523
1   NaN     NaN  aaba         0  abac  0.0320544   NaN      NaN
2   NaN     NaN  aabb 0.0601954  abbc          0   NaN      NaN
3   NaN     NaN  abaa         0  abca          0   NaN      NaN
4   NaN     NaN  abab  0.223069  abcb  0.0320544   NaN      NaN
5   NaN     NaN  abba         0  abcc -0.0236888   NaN      NaN
6   NaN     NaN  abbb         0   NaN        NaN   NaN      NaN

--- coronene: fluctuation_berry_curvature.csv

   1orb  BC1orb  2orb       BC2orb  3orb     BC3orb  4orb    BC4orb
0  aaaa       0  aaab            0  aabc -0.0168572  abcd -0.158932
1   NaN     NaN  aaba            0  abac   0.096323   NaN       NaN
2   NaN     NaN  aabb -9.00678e-20  abbc          0   NaN       NaN
3   NaN     NaN  abaa            0  abca          0   NaN       NaN
4   NaN     NaN  abab -2.55019e-19  abcb   0.096323   NaN       NaN
5   NaN     NaN  abba            0  abcc -0.0168572   NaN       NaN
6   NaN     NaN  abbb            0   NaN        NaN   NaN       NaN

## Leading loop families (Berry curvature, three-centre partition)

In [9]:
for name in summary.system:
    fam = pd.read_csv(os.path.join(OUT, name, "berry_loop_families.csv"))
    print(f"--- {name}: {len(fam)} families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)")
    display(fam.head(6))

--- haldane: 6630 families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)

,sides_over_a,n_loops,Omega_per_e,C_imag,sum_abs_C,fraction_of_total
0,"1.000, 1.732, 2.000",72,0.177984,0.430436,0.430436,0.430494
1,"1.000, 1.000, 1.732",36,0.143893,0.347992,0.347992,0.348038
2,"1.732, 2.000, 2.646",72,0.0310742,0.0751498,0.0751498,0.0751599
3,"1.000, 1.732, 2.646",72,-0.0251223,-0.0607559,0.0607559,-0.060764
4,"1.732, 1.732, 1.732",24,0,0,0.0555958,0
5,"1.000, 3.464, 3.606",72,0.0190057,0.0459635,0.0459635,0.0459696

--- haldane_4x4: 109 families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)

,sides_over_a,n_loops,Omega_per_e,C_imag,sum_abs_C,fraction_of_total
0,"1.000, 1.732, 2.000",1152,0.177984,0.430436,0.430436,0.431011
1,"1.000, 1.000, 1.732",576,0.143893,0.347992,0.347992,0.348456
2,"1.732, 2.000, 2.646",1152,0.0310742,0.0751498,0.0751498,0.0752502
3,"1.000, 1.732, 2.646",1152,-0.0251223,-0.0607559,0.0607559,-0.060837
4,"1.732, 1.732, 1.732",384,1.15196e-19,2.43945e-19,0.0555958,2.44271e-19
5,"1.000, 3.464, 3.606",1152,0.0190057,0.0459635,0.0459635,0.0460249

--- benzene: 0 families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)

Empty DataFrame
Columns: [sides_over_a, n_loops, Omega_per_e, C_imag, sum_abs_C, fraction_of_total]
Index: []

--- coronene: 73 families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)

,sides_over_a,n_loops,Omega_per_e,C_imag,sum_abs_C,fraction_of_total
0,"1.000, 1.732, 2.000",504,0.105113,3.05046,3.05046,NaN
1,"1.000, 1.000, 1.732",288,0.0913589,2.65131,2.65131,NaN
2,"1.000, 1.732, 2.646",432,-0.0249701,-0.724651,0.724651,NaN
3,"1.732, 2.000, 2.646",360,0.0207445,0.60202,0.60202,NaN
4,"1.000, 4.583, 5.000",144,-0.0198053,-0.574764,0.574764,NaN
5,"1.000, 4.000, 4.583",144,-0.0132076,-0.383294,0.383294,NaN