# Orbital-resolved quantum geometric tensor: 2D Haldane, benzene and coronene ($t'=1.0\,t$)

This is `Quantum_Metric_Wannier.ipynb`, adapted to run on the PythTB models of `bond_index_benzene_chern.ipynb` instead of a Wannier90 model. It keeps the original workflow: hopping table, then `ham_func`, then `TBLR.TBLinearResponse`, then the orbital-resolved QGT.

**Outputs, written to `OUT/<system>/`:**
* `qgt_xx.npy`, `qgt_xy.npy`, `qgt_yx.npy`, `qgt_yy.npy`: the four-index tensors of the original `calc_QM`, with index order `Q[a,b,c,d] = <o|v_ad|u><u|v_bc|o>/(E_u-E_o)^2`, normalized per electron.
* `fluctuation_quantum_metric.csv` and `fluctuation_berry_curvature.csv`: the last cells of `Quantum_Metric_Wannier.ipynb`, with CSV in place of the xlsx. Metric: `qgtxx + qgtyy`. Berry curvature: `i(qgtxy - qgtyx)`, whose total is $-2\,\mathrm{Im}\,\mathcal Q^{xy}$. Patterns label the `qgt[a,b,c,d]` indices, and the real part is kept, as in the original `np.float64` cast.
* `berry_loops.csv` and `berry_loop_families.csv`: the orbital-resolved Berry curvature as three-centre bond loops, as in `bond_index_benzene_chern.ipynb`, with the `einsum` index fix.
* `summary.csv`: totals and cross-checks.

**Changes from the original notebook**
1. 2D only: 2-component k, 2×2 lattice, 2-component hopping vectors, and `Nkp=[nk, nk]`. Molecules use `Nkp=[1, 1]`.
2. `calc_QM` also returns `qgtxy` and `qgtyx`, and uses a central difference for $\partial H/\partial k$, which is still built from `tb.ham`.
3. Fixed the save cell, which wrote `qgtxx` into the `qgtyx` file, and the missing `/` in the file paths.
4. The loops take $\rho(\mathbf R)$ from `tb.solve_1pRDM_kresolved`. The geometry factor uses $(\mathbf r_a-\mathbf r_b)\times(\mathbf r_a-\mathbf r_c)$; the old `einsum("ba,ca->abc", x_ba, …)` read `x_ba` transposed.
5. Loop prefactor: $C$ contribution $=(2\pi/A_{\rm cell})\,(\mathbf r_a-\mathbf r_b)\times(\mathbf r_a-\mathbf r_c)\,\mathrm{Im}\,b_{abc}$, using the honeycomb cell for the molecules too. The old prefactor $2\pi N_{\rm occ}/A_{\rm supercell}$ rescaled molecule loops by 3/4.

**Supercell.** `haldane_4x4` is the same Haldane model on a 4×4 supercell with 32 sites, built with `make_supercell`. Each site is then its own orbital index in the four-index tensor and the fluctuation tables; hops that cross the supercell boundary are still folded onto the 32 indices. Its k mesh is `NK/4`, the same k-point density as the primitive cell, so the totals must agree to mesh accuracy. Its loop table uses `rmax = ceil(RMAX/4)` supercells and writes only loops with |(r_a−r_b)×(r_a−r_c) Im b| > `LOOP_TOL_SC`, and the primitive-cell table uses `LOOP_TOL`. `summary.csv` reports the loop sum both before and after the cut.

**Conventions.** Lengths are in units of the nearest-neighbour bond $a$; energies are in $|t|$. `PHI = -pi/2` is the manuscript convention ($C=+1$); `+pi/2` is the original notebook ($C=-1$). For the 2-orbital Haldane cell, an "orbital" is a sublattice summed over all its lattice images, as in the Wannier workflow. The loop table resolves the images explicitly.

**Note on `TBLR.solve_QGT_kresolved_offD`.** It sums `pref*|Jx|*|Jy|`, which is neither the real nor the imaginary part of $\mathcal Q^{xy}$. It cannot give the Berry curvature, so this notebook does not use it.

In [1]:
#Import everything
import numpy as np, pandas as pd, os, json, itertools
import matplotlib.pyplot as plt
from tqdm import tqdm
from pythtb import Lattice, TBModel
import TBLR2 as TBLR
try:
    import opt_einsum as oe
    contract = oe.contract
except ImportError:                                   # opt_einsum is optional
    contract = lambda *a: np.einsum(*a, optimize=True)

# ---------------- parameters
T1      = -1.0          # nearest-neighbour hopping
T2_MAG  = 1.0          # |t'|/|t|
PHI     = -np.pi/2      # -pi/2: manuscript convention (C=+1); +pi/2: original notebook (C=-1)
DELTA   = 0.0           # sublattice mass
NK      = 100           # periodic model: NK x NK k mesh
RMAX    = 12             # periodic model: lattice-image box for the three-centre loops
MU      = 0.0           # chemical potential (half filling)
BETA    = 1.e2          # Fermi smearing, as in the original notebook
K_STEP  = 1.e-4         # finite-difference step for dH/dk (central difference)
ACC     = 1/np.sqrt(3)  # NN bond in PythTB lattice units -> lengths are reported in units of a
SC      = 4             # Haldane supercell size (SC x SC); its k mesh is NK//SC so it samples the same k-points
LOOP_TOL = 1e-8       # primitive-cell loop table: keep loops with |(r_a-r_b)x(r_a-r_c) Im b| > tol
LOOP_TOL_SC = 1e-5      # supercell loop table: keep loops with |(r_a-r_b)x(r_a-r_c) Im b| > tol (7.8M -> 0.12M rows; full sum still reported)
OUT     = "qgt_orbital_resolved_tprime_1p0"

In [2]:
#Models: same hoppings as bond_index_benzene_chern.ipynb
def build_models(t2mag=T2_MAG, phi=PHI, delta=DELTA, t=T1):
    lat = Lattice([[1, 0], [0.5, np.sqrt(3)/2]], [[1/3, 1/3], [2/3, 2/3]], periodic_dirs=...)
    h = TBModel(lat)
    t2 = t2mag*np.exp(1j*phi); t2c = np.conj(t2)
    h.set_onsite([-delta, delta])
    h.set_hop(t, 0, 1, [0, 0]); h.set_hop(t, 1, 0, [1, 0]); h.set_hop(t, 1, 0, [0, 1])
    h.set_hop(t2, 0, 0, [1, 0]); h.set_hop(t2, 1, 1, [1, -1]); h.set_hop(t2, 1, 1, [0, 1])
    h.set_hop(t2c, 1, 1, [1, 0]); h.set_hop(t2c, 0, 0, [1, -1]); h.set_hop(t2c, 0, 0, [0, 1])
    s1 = h.make_supercell(np.array([[2, 0], [0, 2]]))
    bz = s1.cut_piece(1, 1, glue_edges=False).cut_piece(1, 0, glue_edges=False)
    bz.remove_orb(7); bz.remove_orb(0)
    s2 = h.make_supercell(np.array([[4, 0], [0, 4]]))
    co = s2.cut_piece(1, 1, glue_edges=False).cut_piece(1, 0, glue_edges=False)
    for o in [31, 30, 29, 23, 8, 2, 1, 0]: co.remove_orb(o)
    hsc = h.make_supercell(np.array([[SC, 0], [0, SC]]))          # SC x SC supercell of the periodic model
    return {"haldane": h, f"haldane_{SC}x{SC}": hsc, "benzene": bz, "coronene": co}

def is_molecule(model):
    return not any(np.any(np.asarray(hp.get("lattice_vector", [0, 0])) != 0) for hp in model.hoppings)

In [3]:
#Create array with all hopping information (2D)
def hopping_table(my_model):
    norb = my_model.norb
    H = np.empty((norb, norb), dtype=object)
    for i in range(norb):
        for j in range(norb):
            H[i, j] = []
    orb_pos = np.asarray(my_model.orb_vecs)
    lat = np.asarray(my_model.get_lat_vecs())/ACC          # lengths in units of a
    for hop in my_model.hoppings:
        t = hop['amplitude']
        i = hop['from_orbital']
        j = hop['to_orbital']
        j_image = np.asarray(hop.get('lattice_vector', [0, 0]))
        dist = ((orb_pos[j]+j_image)-orb_pos[i]) @ lat
        H[i, j].append([t, dist[0], dist[1]])
    return H, lat, orb_pos @ lat

#Function that finds hamiltonian from hopping array at specific k-point (2D)
def make_ham_func(H, my_model):
    norb = my_model.norb
    onsite = np.asarray(my_model._site_energies, float)
    def ham_func(k):
        kx, ky = k
        H_res = np.zeros((norb, norb), dtype=complex)
        for i in range(norb):
            for j in range(norb):
                for item in H[i][j]:
                    v = np.round(complex(item[0]), 10)*np.exp(1j*kx*item[1]+1j*ky*item[2])
                    H_res[i][j] += v
                    H_res[j][i] += np.conj(v)
        for i, e in enumerate(onsite):
            H_res[i, i] += np.round(e, 10)
        return H_res
    return ham_func

In [4]:
#Orbital-resolved QGT (original calc_QM, 2D, now with xy and yx), per electron
def Fermi(beta_const, x):
    return 1.0/(1.0 + np.exp(beta_const*x))

def FNM(em, en, beta_const=BETA, delta=1.e-3):
    emn = em - en
    fnm = Fermi(beta_const, en)*(1.0 - Fermi(beta_const, em))
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(np.abs(emn) < delta, 0.0, fnm/(emn**2))

def calc_QM(tb, occ, mu=MU, k_step=K_STEP):
    dkx, dky = np.array([1, 0]), np.array([0, 1])
    e = tb.enUM[:, :, 0].real - mu
    pref = FNM(e[:, np.newaxis, :], e[:, :, np.newaxis])     # pref[k,i,j] = f_i(1-f_j)/(E_j-E_i)^2
    n = tb.norb
    Q = {c: np.zeros((n, n, n, n), complex) for c in ("xx", "xy", "yx", "yy")}
    for i, k in enumerate(tqdm(tb.kSpan, disable=len(tb.kSpan) < 2)):
        um = tb.enUM[i, :, 1:]
        uH = um.conj().T
        dH = {"x": (tb.ham(k + k_step*dkx) - tb.ham(k - k_step*dkx))/(2*k_step),
              "y": (tb.ham(k + k_step*dky) - tb.ham(k - k_step*dky))/(2*k_step)}
        Jv1 = {c: contract("ia,ad,dj->adij", uH, dH[c], um) for c in "xy"}             # <i|v_ad|j>
        Jv2c = {c: np.conj(contract("ic,cb,bj->bcij", uH, dH[c], um)) for c in "xy"}   # <j|v_bc|i>
        for c in Q:
            Q[c] += contract("ij,adij,bcij->abcd", pref[i], Jv1[c[0]], Jv2c[c[1]])
    denom = len(tb.kSpan)*occ
    return {c: Q[c]/denom for c in Q}

In [5]:
#Fluctuation-resolved quantum metric and Berry curvature (last cells of Quantum_Metric_Wannier.ipynb)
import itertools

def canonicalize(combo):
    mapping = {}
    next_label = ord('a')
    result = []
    for x in combo:
        if x not in mapping:
            mapping[x] = chr(next_label)
            next_label += 1
        result.append(mapping[x])
    return ''.join(result)

def find_combo_list(orb_list, num_un):
    patterns = set()
    for combo in itertools.product(orb_list, repeat=4):
        if len(set(combo)) >= num_un:
            patterns.add(canonicalize(combo))
    return sorted(patterns)

def find_atom_metric(atomic_metric, num_un, atoms):
    atomic_metric_ab = atomic_metric.copy()
    for a in range(len(atoms)):
        for b in range(len(atoms)):
            for c in range(len(atoms)):
                indices = [a, b, c][:num_un]
                direct_indices = np.asarray(list(itertools.product(indices, repeat=4)))
                for ind in direct_indices:
                    atomic_metric_ab[ind[0], ind[1], ind[2], ind[3]] = 0
    return atomic_metric_ab

combo_a = find_combo_list(["a"], 1)
combo_ab = find_combo_list(["a", "b"], 2)
combo_abc = find_combo_list(["a", "b", "c"], 3)
combo_abcd = find_combo_list(["a", "b", "c", "d"], 4)

def fluctuation_table(tensor, atoms, label, denom=1):
    """tensor[a,b,c,d] in the qgt index order; returns the 1orb/2orb/3orb/4orb table of the original notebook."""
    atomic = np.zeros((len(atoms),)*4, dtype=complex)
    for i, m in enumerate(atoms):
        for j, n in enumerate(atoms):
            for k, o in enumerate(atoms):
                for l, p in enumerate(atoms):
                    atomic[i, j, k, l] = np.sum(tensor[np.ix_(m, n, o, p)])
    atom_metric_ab = find_atom_metric(atomic, 1, atoms)
    atom_metric_abc = find_atom_metric(atomic, 2, atoms)
    atom_metric_abcd = find_atom_metric(atomic, 3, atoms)
    data = [[], [], [], []]; dropped_imag = 0.0
    sets = [(combo_a, atomic), (np.setdiff1d(combo_ab, combo_a), atom_metric_ab),
            (np.setdiff1d(combo_abc, combo_ab), atom_metric_abc), (np.setdiff1d(combo_abcd, combo_abc), atom_metric_abcd)]
    for n, (combos, arr) in enumerate(sets):
        for combo in combos:
            v = np.einsum(str(combo)+"->", arr)/denom
            dropped_imag = max(dropped_imag, abs(v.imag))
            data[n].append([str(combo), np.float64(v.real)])     # the original keeps the real part (np.float64 cast)
    dfs = [pd.DataFrame(data=np.array(d, dtype=object), columns=[f"{n+1}orb", f"{label}{n+1}orb"]) for n, d in enumerate(data)]
    df = pd.concat(dfs, axis=1)
    for n in range(4):
        df[f"{label}{n+1}orb"] = pd.to_numeric(df[f"{label}{n+1}orb"])
    total = np.real(np.sum(tensor))/denom
    return df, total, dropped_imag

In [6]:
#Three-centre bond loops = orbital-resolved Berry curvature (bond_index_benzene_chern, index fix)
def bond_element_factory(tb, pos, lat, mu=MU):
    """rho_ab(R) = <a,0|P|b,R> from TBLR's k-resolved 1pRDM."""
    Pk = tb.solve_1pRDM_kresolved(mu)
    r0 = pos[np.newaxis, :] - pos[:, np.newaxis]                # r0[a,b] = r_b - r_a
    cache = {}
    def bond_element(R):
        key = (int(R[0]), int(R[1]))
        if key not in cache:
            r = r0 + np.asarray(R) @ lat
            ph = np.exp(-1j*np.einsum("kx,abx->kab", tb.kSpan, r))
            cache[key] = ((Pk*ph).mean(0), r)
        return cache[key]
    return bond_element

def loop_table(tb, model, pos, lat, occ, rmax=RMAX, mu=MU, tol=1e-14):
    mol = is_molecule(model)
    A_cell = 3*np.sqrt(3)/2 if mol else abs(np.linalg.det(lat))    # honeycomb cell in a^2
    bond_element = bond_element_factory(tb, pos, lat, mu)
    R_list = [[0, 0]] if mol else [[i, j] for i in range(-rmax, rmax+1) for j in range(-rmax, rmax+1)]
    cols = ["a", "b", "c", "R1x", "R1y", "R2x", "R2y", "dist_ab_x", "dist_ab_y", "dist_ca_x", "dist_ca_y",
            "oriented_area", "dist_part", "BI_real", "BI_imag", "BI_abs", "Omega_per_e", "C_imag"]
    chunks = {c: [] for c in cols}; W_total = 0.0
    for R1 in tqdm(R_list, disable=mol):
        for R2 in R_list:
            R1, R2 = np.asarray(R1), np.asarray(R2)
            rho_ab, dist_ab = bond_element(R1)            # dist_ab[a,b] = r_b - r_a  (b in cell R1)
            rho_bc, _ = bond_element(R2)
            rho_ca, dist_ca = bond_element(-R1-R2)        # dist_ca[c,a] = r_a - r_c  (c in cell R1+R2)
            BI = np.einsum("ab,bc,ca->abc", rho_ab, rho_bc, rho_ca)
            x_ab, y_ab = -dist_ab[:, :, 0], -dist_ab[:, :, 1]      # [a,b]: r_a - r_b
            x_ac, y_ac = dist_ca[:, :, 0].T, dist_ca[:, :, 1].T    # [a,c]: r_a - r_c
            dist_part = np.einsum("ab,ac->abc", x_ab, y_ac) - np.einsum("ab,ac->abc", y_ab, x_ac)
            W = dist_part*BI.imag
            W_total += W.sum()
            m = np.abs(W) > tol
            if not m.any():
                continue
            ai, bi, ci = np.where(m); nm = len(ai)
            vals = dict(a=ai, b=bi, c=ci, R1x=np.full(nm, R1[0]), R1y=np.full(nm, R1[1]),
                        R2x=np.full(nm, R2[0]), R2y=np.full(nm, R2[1]),
                        dist_ab_x=x_ab[ai, bi], dist_ab_y=y_ab[ai, bi], dist_ca_x=x_ac[ai, ci], dist_ca_y=y_ac[ai, ci],
                        oriented_area=0.5*dist_part[m], dist_part=dist_part[m],
                        BI_real=BI.real[m], BI_imag=BI.imag[m], BI_abs=np.abs(BI[m]),
                        Omega_per_e=W[m]/occ,                     # contribution to Omega^xy per electron (a^2)
                        C_imag=2*np.pi/A_cell*W[m])               # contribution to C (bulk) / Fig. 4 loop weight (molecules)
            for c in cols:
                chunks[c].append(vals[c])
    df = pd.DataFrame({c: (np.concatenate(chunks[c]) if chunks[c] else np.array([])) for c in cols})
    df.attrs["C_all_loops"] = float(2*np.pi/A_cell*W_total)      # before the tol cut
    return df, A_cell, bond_element

def loop_families(dfl):
    if not len(dfl):
        return pd.DataFrame(columns=["sides_over_a", "n_loops", "Omega_per_e", "C_imag", "sum_abs_C", "fraction_of_total"])
    ab = np.hypot(dfl.dist_ab_x, dfl.dist_ab_y); ca = np.hypot(dfl.dist_ca_x, dfl.dist_ca_y)
    bc = np.hypot(dfl.dist_ab_x-dfl.dist_ca_x, dfl.dist_ab_y-dfl.dist_ca_y)
    key = [", ".join(f"{x:.3f}" for x in sorted(t)) for t in zip(ab, bc, ca)]
    g = dfl.assign(sides_over_a=key).groupby("sides_over_a").agg(
        n_loops=("C_imag", "size"), Omega_per_e=("Omega_per_e", "sum"),
        C_imag=("C_imag", "sum"), sum_abs_C=("C_imag", lambda s: s.abs().sum()))
    tot = dfl.C_imag.sum()
    g["fraction_of_total"] = g.C_imag/tot if abs(tot) > 1e-8 else np.nan
    return g.reindex(g.sum_abs_C.sort_values(ascending=False).index).reset_index()

def g_bond(bond_element, pos, lat, occ, mol, rmax=RMAX):
    """two-centre check, Eq. 1: Tr g = 1/(2 Ne) sum |rho_ab(R)|^2 |r_b + R - r_a|^2"""
    Rs = [[0, 0]] if mol else [[i, j] for i in range(-2*rmax, 2*rmax+1) for j in range(-2*rmax, 2*rmax+1)]
    return sum((np.abs(r)**2*(d**2).sum(-1)).sum() for r, d in (bond_element(R) for R in Rs))/(2*occ)

In [7]:
#Run: TBLR object per model, QGT tensors, loops, and write everything
summary = []
import time
for name, my_model in build_models().items():
    t0 = time.time()
    mol = is_molecule(my_model)
    H, lat, pos = hopping_table(my_model)
    ham_func = make_ham_func(H, my_model)
    sc = name.startswith("haldane_")
    nk = 1 if mol else (NK//SC if sc else NK)
    rmax = int(np.ceil(RMAX/SC)) if sc else RMAX
    tb = TBLR.TBLinearResponse(ham_func, Lar=np.array(lat),
                               Nkp=[nk, nk],
                               prestr=f"{name}_tp{T2_MAG}",
                               save_all=False,
                               kpath=['G', 'X', 'M', 'G', 'Y', 'M'])
    occ = int(np.sum(tb.enUM[0, :, 0].real <= MU))
    print(f"{name}: norb={tb.norb}  occ={occ}  k-points={len(tb.kSpan)}")

    qgt = calc_QM(tb, occ)
    atoms = [[i] for i in range(tb.norb)]       # one orbital per site (Haldane cell: the two sublattices)
    QM_tensor = qgt["xx"] + qgt["yy"]            # metric trace, as in the original cell
    BC_tensor = 1j*(qgt["xy"] - qgt["yx"])       # Berry curvature Omega^xy; its total is -2 Im Q^xy
    df_qm, tot_qm, im_qm = fluctuation_table(QM_tensor, atoms, "QM")
    df_bc, tot_bc, im_bc = fluctuation_table(BC_tensor, atoms, "BC")
    dfl, A_cell, bond_element = loop_table(tb, my_model, pos, lat, occ, rmax=rmax, tol=LOOP_TOL_SC if sc else (LOOP_TOL if not mol else 1e-14))

    d = os.path.join(OUT, name); os.makedirs(d, exist_ok=True)
    for c in qgt:
        np.save(os.path.join(d, f"qgt_{c}.npy"), qgt[c])
    df_qm.to_csv(os.path.join(d, "fluctuation_quantum_metric.csv"), index=False)
    df_bc.to_csv(os.path.join(d, "fluctuation_berry_curvature.csv"), index=False)
    dfl.to_csv(os.path.join(d, "berry_loops.csv"), index=False)
    loop_families(dfl).to_csv(os.path.join(d, "berry_loop_families.csv"), index=False)

    # cross-checks: TBLR's own k-resolved metric, the two-centre bond formula, and the two Berry partitions
    gxx_tblr = np.sum(tb.solve_QGT_kresolved(mu=MU, dkx=np.array([1, 0]), k_step=K_STEP)).real/(len(tb.kSpan)*occ)
    gyy_tblr = np.sum(tb.solve_QGT_kresolved(mu=MU, dkx=np.array([0, 1]), k_step=K_STEP)).real/(len(tb.kSpan)*occ)
    Om4 = tot_bc
    print(f"   {name} done in {time.time()-t0:.0f} s", flush=True)
    summary.append(dict(system=name, norb=tb.norb, N_e=occ, k_points=len(tb.kSpan), molecule=mol,
        Tr_g_4index=tot_qm, QM_fluct_sum=sum(df_qm[f"QM{n}orb"].sum() for n in range(1, 5)),
        BC_fluct_sum=sum(df_bc[f"BC{n}orb"].sum() for n in range(1, 5)), max_dropped_imag=max(im_qm, im_bc), Tr_g_TBLR=gxx_tblr+gyy_tblr,
        Tr_g_bond_Eq1=g_bond(bond_element, pos, lat, occ, mol, rmax=rmax),
        Omega_4index=Om4, Omega_loops=float(dfl.Omega_per_e.sum()) if len(dfl) else 0.0,
        C_4index=0.0 if mol else 2*np.pi*occ/A_cell*Om4,
        C_loops=float(dfl.C_imag.sum()) if len(dfl) else 0.0, C_loops_before_cut=dfl.attrs.get("C_all_loops", 0.0),
        sum_abs_C_loops=float(dfl.C_imag.abs().sum()) if len(dfl) else 0.0,
        n_loop_rows=len(dfl), rmax=None if mol else rmax))
summary = pd.DataFrame(summary)
summary.to_csv(os.path.join(OUT, "summary.csv"), index=False)
json.dump(dict(T1=T1, T2_MAG=T2_MAG, PHI=PHI, DELTA=DELTA, NK=NK, RMAX=RMAX, MU=MU, BETA=BETA, K_STEP=K_STEP,
               length_unit="a (NN bond)", energy_unit="|t|",
               qgt_index_order="Q[a,b,c,d] = <o|v_ad|u><u|v_bc|o>/(E_u-E_o)^2, per electron"),
          open(os.path.join(OUT, "parameters.json"), "w"), indent=2)
pd.set_option("display.float_format", lambda x: f"{x:.6g}")
summary

haldane: norb=2  occ=1  k-points=10000

  0%|          | 0/10000 [00:00<?, ?it/s]

  1%|          | 64/10000 [00:00<00:15, 639.74it/s]

  1%|▏         | 132/10000 [00:00<00:14, 660.71it/s]

  2%|▏         | 199/10000 [00:00<00:18, 517.25it/s]

  3%|▎         | 268/10000 [00:00<00:16, 573.68it/s]

  3%|▎         | 331/10000 [00:00<00:16, 590.31it/s]

  4%|▍         | 396/10000 [00:00<00:15, 606.26it/s]

  5%|▍         | 459/10000 [00:00<00:15, 600.42it/s]

  5%|▌         | 524/10000 [00:00<00:15, 615.00it/s]

  6%|▌         | 589/10000 [00:00<00:15, 624.22it/s]

  7%|▋         | 654/10000 [00:01<00:14, 631.15it/s]

  7%|▋         | 718/10000 [00:01<00:14, 629.93it/s]

  8%|▊         | 783/10000 [00:01<00:14, 633.80it/s]

  8%|▊         | 849/10000 [00:01<00:14, 640.95it/s]

  9%|▉         | 918/10000 [00:01<00:13, 654.75it/s]

 10%|▉         | 985/10000 [00:01<00:13, 658.86it/s]

 11%|█         | 1052/10000 [00:01<00:13, 661.84it/s]

 11%|█         | 1119/10000 [00:01<00:13, 663.23it/s]

 12%|█▏        | 1188/10000 [00:01<00:13, 671.21it/s]

 13%|█▎        | 1256/10000 [00:01<00:13, 666.90it/s]

 13%|█▎        | 1324/10000 [00:02<00:12, 668.23it/s]

 14%|█▍        | 1391/10000 [00:02<00:13, 657.45it/s]

 15%|█▍        | 1457/10000 [00:02<00:13, 645.31it/s]

 15%|█▌        | 1522/10000 [00:02<00:13, 639.65it/s]

 16%|█▌        | 1587/10000 [00:02<00:13, 640.09it/s]

 17%|█▋        | 1653/10000 [00:02<00:12, 644.80it/s]

 17%|█▋        | 1718/10000 [00:02<00:13, 633.87it/s]

 18%|█▊        | 1784/10000 [00:02<00:12, 640.02it/s]

 18%|█▊        | 1849/10000 [00:02<00:12, 629.05it/s]

 19%|█▉        | 1917/10000 [00:03<00:12, 641.65it/s]

 20%|█▉        | 1986/10000 [00:03<00:12, 653.31it/s]

 21%|██        | 2054/10000 [00:03<00:12, 660.27it/s]

 21%|██        | 2124/10000 [00:03<00:11, 669.96it/s]

 22%|██▏       | 2194/10000 [00:03<00:11, 676.18it/s]

 23%|██▎       | 2264/10000 [00:03<00:11, 681.29it/s]

 23%|██▎       | 2334/10000 [00:03<00:11, 685.01it/s]

 24%|██▍       | 2403/10000 [00:03<00:11, 685.70it/s]

 25%|██▍       | 2473/10000 [00:03<00:10, 689.53it/s]

 25%|██▌       | 2544/10000 [00:03<00:10, 694.40it/s]

 26%|██▌       | 2614/10000 [00:04<00:14, 520.50it/s]

 27%|██▋       | 2673/10000 [00:04<00:16, 446.49it/s]

 27%|██▋       | 2724/10000 [00:04<00:17, 408.14it/s]

 28%|██▊       | 2770/10000 [00:04<00:19, 378.87it/s]

 28%|██▊       | 2811/10000 [00:04<00:19, 361.18it/s]

 28%|██▊       | 2849/10000 [00:04<00:21, 327.69it/s]

 29%|██▉       | 2884/10000 [00:05<00:22, 323.29it/s]

 29%|██▉       | 2918/10000 [00:05<00:22, 321.87it/s]

 30%|██▉       | 2951/10000 [00:05<00:22, 315.85it/s]

 30%|██▉       | 2983/10000 [00:05<00:22, 313.65it/s]

 30%|███       | 3036/10000 [00:05<00:18, 366.93it/s]

 31%|███       | 3074/10000 [00:05<00:20, 343.35it/s]

 31%|███▏      | 3131/10000 [00:05<00:17, 403.39it/s]

 32%|███▏      | 3198/10000 [00:05<00:14, 475.98it/s]

 33%|███▎      | 3266/10000 [00:05<00:12, 532.39it/s]

 33%|███▎      | 3333/10000 [00:05<00:11, 571.55it/s]

 34%|███▍      | 3400/10000 [00:06<00:11, 598.05it/s]

 35%|███▍      | 3467/10000 [00:06<00:10, 618.63it/s]

 35%|███▌      | 3532/10000 [00:06<00:10, 626.24it/s]

 36%|███▌      | 3598/10000 [00:06<00:10, 634.92it/s]

 37%|███▋      | 3662/10000 [00:06<00:09, 634.24it/s]

 37%|███▋      | 3728/10000 [00:06<00:09, 639.64it/s]

 38%|███▊      | 3796/10000 [00:06<00:09, 649.19it/s]

 39%|███▊      | 3864/10000 [00:06<00:09, 657.21it/s]

 39%|███▉      | 3931/10000 [00:06<00:09, 659.34it/s]

 40%|███▉      | 3998/10000 [00:06<00:09, 661.54it/s]

 41%|████      | 4065/10000 [00:07<00:08, 659.74it/s]

 41%|████▏     | 4132/10000 [00:07<00:09, 645.68it/s]

 42%|████▏     | 4197/10000 [00:07<00:09, 631.34it/s]

 43%|████▎     | 4262/10000 [00:07<00:09, 635.47it/s]

 43%|████▎     | 4326/10000 [00:07<00:09, 620.27it/s]

 44%|████▍     | 4389/10000 [00:07<00:09, 622.58it/s]

 45%|████▍     | 4458/10000 [00:07<00:08, 641.14it/s]

 45%|████▌     | 4527/10000 [00:07<00:08, 654.32it/s]

 46%|████▌     | 4597/10000 [00:07<00:08, 664.52it/s]

 47%|████▋     | 4664/10000 [00:08<00:08, 633.45it/s]

 47%|████▋     | 4733/10000 [00:08<00:08, 648.87it/s]

 48%|████▊     | 4800/10000 [00:08<00:07, 653.05it/s]

 49%|████▊     | 4869/10000 [00:08<00:07, 663.26it/s]

 49%|████▉     | 4938/10000 [00:08<00:07, 669.70it/s]

 50%|█████     | 5008/10000 [00:08<00:07, 678.25it/s]

 51%|█████     | 5077/10000 [00:08<00:07, 680.80it/s]

 51%|█████▏    | 5146/10000 [00:08<00:07, 675.12it/s]

 52%|█████▏    | 5214/10000 [00:08<00:07, 671.54it/s]

 53%|█████▎    | 5282/10000 [00:08<00:07, 668.14it/s]

 53%|█████▎    | 5349/10000 [00:09<00:07, 660.22it/s]

 54%|█████▍    | 5416/10000 [00:09<00:06, 662.48it/s]

 55%|█████▍    | 5483/10000 [00:09<00:06, 658.53it/s]

 55%|█████▌    | 5549/10000 [00:09<00:06, 648.85it/s]

 56%|█████▌    | 5614/10000 [00:09<00:06, 645.65it/s]

 57%|█████▋    | 5679/10000 [00:09<00:06, 640.06it/s]

 57%|█████▋    | 5749/10000 [00:09<00:06, 655.03it/s]

 58%|█████▊    | 5818/10000 [00:09<00:06, 663.36it/s]

 59%|█████▉    | 5887/10000 [00:09<00:06, 669.65it/s]

 60%|█████▉    | 5954/10000 [00:09<00:06, 658.39it/s]

 60%|██████    | 6020/10000 [00:10<00:06, 652.29it/s]

 61%|██████    | 6086/10000 [00:10<00:06, 612.88it/s]

 62%|██████▏   | 6150/10000 [00:10<00:06, 617.97it/s]

 62%|██████▏   | 6216/10000 [00:10<00:06, 628.52it/s]

 63%|██████▎   | 6283/10000 [00:10<00:05, 640.45it/s]

 64%|██████▎   | 6352/10000 [00:10<00:05, 653.85it/s]

 64%|██████▍   | 6418/10000 [00:10<00:05, 653.60it/s]

 65%|██████▍   | 6485/10000 [00:10<00:05, 657.80it/s]

 66%|██████▌   | 6551/10000 [00:10<00:05, 646.35it/s]

 66%|██████▌   | 6616/10000 [00:11<00:05, 646.31it/s]

 67%|██████▋   | 6681/10000 [00:11<00:05, 642.99it/s]

 67%|██████▋   | 6746/10000 [00:11<00:05, 638.01it/s]

 68%|██████▊   | 6810/10000 [00:11<00:05, 625.36it/s]

 69%|██████▉   | 6880/10000 [00:11<00:04, 645.12it/s]

 69%|██████▉   | 6945/10000 [00:11<00:04, 626.09it/s]

 70%|███████   | 7011/10000 [00:11<00:04, 633.97it/s]

 71%|███████   | 7079/10000 [00:11<00:04, 645.00it/s]

 71%|███████▏  | 7144/10000 [00:11<00:05, 531.14it/s]

 72%|███████▏  | 7201/10000 [00:12<00:05, 477.03it/s]

 73%|███████▎  | 7252/10000 [00:12<00:06, 442.87it/s]

 73%|███████▎  | 7299/10000 [00:12<00:06, 428.05it/s]

 74%|███████▎  | 7352/10000 [00:12<00:05, 451.22it/s]

 74%|███████▍  | 7399/10000 [00:12<00:05, 437.76it/s]

 74%|███████▍  | 7444/10000 [00:12<00:06, 422.01it/s]

 75%|███████▍  | 7487/10000 [00:12<00:06, 405.09it/s]

 75%|███████▌  | 7531/10000 [00:12<00:05, 412.22it/s]

 76%|███████▌  | 7573/10000 [00:12<00:06, 403.49it/s]

 76%|███████▌  | 7614/10000 [00:13<00:06, 391.26it/s]

 77%|███████▋  | 7654/10000 [00:13<00:06, 389.72it/s]

 77%|███████▋  | 7702/10000 [00:13<00:05, 414.59it/s]

 77%|███████▋  | 7744/10000 [00:13<00:05, 406.39it/s]

 78%|███████▊  | 7794/10000 [00:13<00:05, 432.61it/s]

 78%|███████▊  | 7843/10000 [00:13<00:04, 446.75it/s]

 79%|███████▉  | 7895/10000 [00:13<00:04, 464.59it/s]

 79%|███████▉  | 7942/10000 [00:13<00:04, 450.25it/s]

 80%|███████▉  | 7991/10000 [00:13<00:04, 458.35it/s]

 80%|████████  | 8041/10000 [00:14<00:04, 469.06it/s]

 81%|████████  | 8089/10000 [00:14<00:04, 457.28it/s]

 81%|████████▏ | 8140/10000 [00:14<00:03, 471.77it/s]

 82%|████████▏ | 8188/10000 [00:14<00:04, 450.59it/s]

 82%|████████▏ | 8239/10000 [00:14<00:03, 466.81it/s]

 83%|████████▎ | 8291/10000 [00:14<00:03, 478.16it/s]

 83%|████████▎ | 8341/10000 [00:14<00:03, 481.56it/s]

 84%|████████▍ | 8399/10000 [00:14<00:03, 507.89it/s]

 84%|████████▍ | 8450/10000 [00:14<00:03, 434.94it/s]

 85%|████████▍ | 8496/10000 [00:15<00:03, 424.99it/s]

 85%|████████▌ | 8549/10000 [00:15<00:03, 452.68it/s]

 86%|████████▌ | 8596/10000 [00:15<00:03, 434.36it/s]

 86%|████████▋ | 8648/10000 [00:15<00:02, 455.70it/s]

 87%|████████▋ | 8699/10000 [00:15<00:02, 467.27it/s]

 87%|████████▋ | 8747/10000 [00:15<00:02, 457.12it/s]

 88%|████████▊ | 8794/10000 [00:15<00:02, 454.25it/s]

 88%|████████▊ | 8842/10000 [00:15<00:02, 459.71it/s]

 89%|████████▉ | 8909/10000 [00:15<00:02, 519.67it/s]

 90%|████████▉ | 8962/10000 [00:16<00:02, 498.83it/s]

 90%|█████████ | 9013/10000 [00:16<00:02, 458.73it/s]

 91%|█████████ | 9060/10000 [00:16<00:02, 434.33it/s]

 91%|█████████ | 9105/10000 [00:16<00:02, 425.85it/s]

 91%|█████████▏| 9149/10000 [00:16<00:02, 419.51it/s]

 92%|█████████▏| 9192/10000 [00:16<00:01, 418.32it/s]

 92%|█████████▏| 9235/10000 [00:16<00:01, 418.79it/s]

 93%|█████████▎| 9297/10000 [00:16<00:01, 474.20it/s]

 93%|█████████▎| 9345/10000 [00:16<00:01, 474.80it/s]

 94%|█████████▍| 9399/10000 [00:16<00:01, 493.43it/s]

 95%|█████████▍| 9451/10000 [00:17<00:01, 500.61it/s]

 95%|█████████▌| 9506/10000 [00:17<00:00, 512.85it/s]

 96%|█████████▌| 9558/10000 [00:17<00:00, 512.64it/s]

 96%|█████████▌| 9611/10000 [00:17<00:00, 514.87it/s]

 97%|█████████▋| 9663/10000 [00:17<00:00, 511.05it/s]

 97%|█████████▋| 9720/10000 [00:17<00:00, 527.30it/s]

 98%|█████████▊| 9774/10000 [00:17<00:00, 528.69it/s]

 98%|█████████▊| 9827/10000 [00:17<00:00, 506.05it/s]

 99%|█████████▉| 9884/10000 [00:17<00:00, 523.36it/s]

 99%|█████████▉| 9937/10000 [00:18<00:00, 484.79it/s]

100%|█████████▉| 9987/10000 [00:18<00:00, 448.14it/s]

100%|██████████| 10000/10000 [00:18<00:00, 548.75it/s]

  0%|          | 0/625 [00:00<?, ?it/s]

  0%|          | 1/625 [00:01<20:05,  1.93s/it]

  1%|          | 4/625 [00:02<04:04,  2.53it/s]

  1%|▏         | 8/625 [00:02<01:47,  5.73it/s]

  2%|▏         | 11/625 [00:02<01:13,  8.40it/s]

  2%|▏         | 14/625 [00:02<00:56, 10.87it/s]

  3%|▎         | 17/625 [00:02<00:49, 12.27it/s]

  3%|▎         | 20/625 [00:02<00:48, 12.56it/s]

  4%|▎         | 22/625 [00:02<00:46, 12.95it/s]

  4%|▍         | 24/625 [00:03<00:43, 13.71it/s]

  4%|▍         | 27/625 [00:03<00:35, 16.92it/s]

  6%|▌         | 35/625 [00:03<00:19, 30.81it/s]

  7%|▋         | 41/625 [00:03<00:15, 36.79it/s]

  7%|▋         | 46/625 [00:03<00:15, 38.50it/s]

  8%|▊         | 51/625 [00:03<00:14, 39.85it/s]

  9%|▉         | 59/625 [00:03<00:11, 49.38it/s]

 10%|█         | 65/625 [00:03<00:11, 48.36it/s]

 11%|█▏        | 71/625 [00:04<00:12, 45.31it/s]

 12%|█▏        | 76/625 [00:04<00:12, 44.48it/s]

 13%|█▎        | 84/625 [00:04<00:10, 53.11it/s]

 14%|█▍        | 90/625 [00:04<00:10, 52.07it/s]

 15%|█▌        | 96/625 [00:04<00:10, 48.90it/s]

 16%|█▋        | 102/625 [00:04<00:10, 47.69it/s]

 18%|█▊        | 110/625 [00:04<00:09, 54.55it/s]

 19%|█▊        | 116/625 [00:04<00:09, 52.14it/s]

 20%|█▉        | 122/625 [00:05<00:10, 46.86it/s]

 20%|██        | 127/625 [00:05<00:11, 42.21it/s]

 21%|██▏       | 133/625 [00:05<00:11, 43.63it/s]

 22%|██▏       | 138/625 [00:05<00:11, 42.15it/s]

 23%|██▎       | 143/625 [00:05<00:11, 42.93it/s]

 24%|██▎       | 148/625 [00:05<00:12, 38.91it/s]

 24%|██▍       | 152/625 [00:05<00:12, 38.19it/s]

 25%|██▌       | 159/625 [00:05<00:10, 45.27it/s]

 26%|██▌       | 164/625 [00:06<00:10, 46.02it/s]

 27%|██▋       | 169/625 [00:06<00:10, 45.59it/s]

 28%|██▊       | 174/625 [00:06<00:10, 44.71it/s]

 29%|██▊       | 179/625 [00:06<00:09, 45.91it/s]

 30%|██▉       | 185/625 [00:06<00:09, 47.76it/s]

 30%|███       | 190/625 [00:06<00:09, 46.82it/s]

 31%|███       | 195/625 [00:06<00:09, 44.69it/s]

 32%|███▏      | 201/625 [00:06<00:09, 45.88it/s]

 33%|███▎      | 207/625 [00:06<00:08, 49.54it/s]

 34%|███▍      | 213/625 [00:07<00:08, 46.42it/s]

 35%|███▍      | 218/625 [00:07<00:09, 43.26it/s]

 36%|███▌      | 223/625 [00:07<00:09, 43.29it/s]

 36%|███▋      | 228/625 [00:07<00:09, 43.29it/s]

 37%|███▋      | 234/625 [00:07<00:08, 46.01it/s]

 38%|███▊      | 239/625 [00:07<00:08, 44.55it/s]

 39%|███▉      | 244/625 [00:07<00:08, 42.72it/s]

 40%|███▉      | 249/625 [00:07<00:08, 43.12it/s]

 41%|████      | 254/625 [00:08<00:08, 42.49it/s]

 41%|████▏     | 259/625 [00:08<00:08, 43.34it/s]

 42%|████▏     | 264/625 [00:08<00:08, 42.51it/s]

 43%|████▎     | 269/625 [00:08<00:08, 41.30it/s]

 44%|████▍     | 274/625 [00:08<00:08, 42.51it/s]

 45%|████▍     | 279/625 [00:08<00:08, 43.12it/s]

 45%|████▌     | 284/625 [00:08<00:07, 44.08it/s]

 46%|████▌     | 289/625 [00:08<00:07, 42.30it/s]

 47%|████▋     | 294/625 [00:08<00:08, 41.29it/s]

 48%|████▊     | 299/625 [00:09<00:07, 42.19it/s]

 49%|████▊     | 304/625 [00:09<00:07, 42.77it/s]

 49%|████▉     | 309/625 [00:09<00:07, 42.56it/s]

 50%|█████     | 314/625 [00:09<00:08, 38.48it/s]

 51%|█████     | 318/625 [00:09<00:08, 37.26it/s]

 52%|█████▏    | 322/625 [00:09<00:08, 36.17it/s]

 52%|█████▏    | 326/625 [00:09<00:08, 35.52it/s]

 53%|█████▎    | 331/625 [00:09<00:07, 38.27it/s]

 54%|█████▍    | 336/625 [00:10<00:07, 39.02it/s]

 54%|█████▍    | 340/625 [00:10<00:07, 38.74it/s]

 55%|█████▌    | 345/625 [00:10<00:07, 39.52it/s]

 56%|█████▌    | 350/625 [00:10<00:06, 41.64it/s]

 57%|█████▋    | 355/625 [00:10<00:06, 39.19it/s]

 58%|█████▊    | 360/625 [00:10<00:06, 39.72it/s]

 58%|█████▊    | 365/625 [00:10<00:06, 38.99it/s]

 59%|█████▉    | 369/625 [00:10<00:06, 39.14it/s]

 60%|██████    | 375/625 [00:11<00:05, 43.20it/s]

 61%|██████    | 380/625 [00:11<00:06, 40.54it/s]

 62%|██████▏   | 385/625 [00:11<00:05, 40.65it/s]

 62%|██████▏   | 390/625 [00:11<00:05, 39.30it/s]

 63%|██████▎   | 394/625 [00:11<00:06, 37.23it/s]

 64%|██████▍   | 399/625 [00:11<00:05, 39.81it/s]

 65%|██████▍   | 404/625 [00:11<00:05, 38.49it/s]

 65%|██████▌   | 409/625 [00:11<00:05, 39.15it/s]

 66%|██████▌   | 414/625 [00:12<00:05, 38.89it/s]

 67%|██████▋   | 419/625 [00:12<00:05, 39.94it/s]

 68%|██████▊   | 425/625 [00:12<00:04, 44.99it/s]

 69%|██████▉   | 430/625 [00:12<00:04, 42.23it/s]

 70%|██████▉   | 435/625 [00:12<00:04, 42.07it/s]

 70%|███████   | 440/625 [00:12<00:04, 41.46it/s]

 71%|███████▏  | 446/625 [00:12<00:03, 45.01it/s]

 72%|███████▏  | 451/625 [00:12<00:03, 44.86it/s]

 73%|███████▎  | 456/625 [00:12<00:03, 45.00it/s]

 74%|███████▍  | 461/625 [00:13<00:03, 42.99it/s]

 75%|███████▍  | 466/625 [00:13<00:03, 42.42it/s]

 76%|███████▌  | 472/625 [00:13<00:03, 46.48it/s]

 76%|███████▋  | 477/625 [00:13<00:03, 44.76it/s]

 77%|███████▋  | 482/625 [00:13<00:03, 44.25it/s]

 78%|███████▊  | 487/625 [00:13<00:03, 42.55it/s]

 79%|███████▊  | 492/625 [00:13<00:03, 43.72it/s]

 80%|███████▉  | 499/625 [00:13<00:02, 49.45it/s]

 81%|████████  | 504/625 [00:14<00:02, 44.31it/s]

 81%|████████▏ | 509/625 [00:14<00:02, 45.00it/s]

 82%|████████▏ | 514/625 [00:14<00:02, 44.82it/s]

 83%|████████▎ | 519/625 [00:14<00:02, 45.79it/s]

 84%|████████▍ | 526/625 [00:14<00:02, 45.57it/s]

 85%|████████▍ | 531/625 [00:14<00:02, 43.57it/s]

 86%|████████▌ | 536/625 [00:14<00:01, 44.50it/s]

 87%|████████▋ | 541/625 [00:14<00:01, 45.51it/s]

 88%|████████▊ | 548/625 [00:14<00:01, 51.13it/s]

 89%|████████▊ | 554/625 [00:15<00:01, 45.24it/s]

 89%|████████▉ | 559/625 [00:15<00:01, 44.92it/s]

 90%|█████████ | 564/625 [00:15<00:01, 44.83it/s]

 91%|█████████▏| 571/625 [00:15<00:01, 50.41it/s]

 92%|█████████▏| 577/625 [00:15<00:01, 47.85it/s]

 93%|█████████▎| 582/625 [00:15<00:00, 46.99it/s]

 94%|█████████▍| 587/625 [00:15<00:00, 47.23it/s]

 95%|█████████▍| 593/625 [00:15<00:00, 50.26it/s]

 96%|█████████▌| 600/625 [00:16<00:00, 55.22it/s]

 97%|█████████▋| 606/625 [00:16<00:00, 42.95it/s]

 98%|█████████▊| 612/625 [00:16<00:00, 45.29it/s]

 99%|█████████▉| 618/625 [00:16<00:00, 48.15it/s]

100%|██████████| 625/625 [00:16<00:00, 37.69it/s]

/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: divide by zero encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))
/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: invalid value encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))

   haldane done in 58 s

haldane_4x4: norb=32  occ=16  k-points=625

  0%|          | 0/625 [00:00<?, ?it/s]

  0%|          | 1/625 [00:00<06:36,  1.57it/s]

  0%|          | 2/625 [00:01<06:20,  1.64it/s]

  0%|          | 3/625 [00:01<06:14,  1.66it/s]

  1%|          | 4/625 [00:02<06:06,  1.69it/s]

  1%|          | 5/625 [00:02<06:05,  1.70it/s]

  1%|          | 6/625 [00:03<06:03,  1.70it/s]

  1%|          | 7/625 [00:04<06:00,  1.72it/s]

  1%|▏         | 8/625 [00:04<06:02,  1.70it/s]

  1%|▏         | 9/625 [00:05<05:58,  1.72it/s]

  2%|▏         | 10/625 [00:05<05:56,  1.73it/s]

  2%|▏         | 11/625 [00:06<05:57,  1.72it/s]

  2%|▏         | 12/625 [00:07<06:01,  1.70it/s]

  2%|▏         | 13/625 [00:07<05:59,  1.70it/s]

  2%|▏         | 14/625 [00:08<06:00,  1.69it/s]

  2%|▏         | 15/625 [00:08<05:58,  1.70it/s]

  3%|▎         | 16/625 [00:09<06:00,  1.69it/s]

  3%|▎         | 17/625 [00:10<05:57,  1.70it/s]

  3%|▎         | 18/625 [00:10<05:55,  1.71it/s]

  3%|▎         | 19/625 [00:11<05:52,  1.72it/s]

  3%|▎         | 20/625 [00:11<06:02,  1.67it/s]

  3%|▎         | 21/625 [00:12<06:00,  1.68it/s]

  4%|▎         | 22/625 [00:12<05:56,  1.69it/s]

  4%|▎         | 23/625 [00:13<05:56,  1.69it/s]

  4%|▍         | 24/625 [00:14<05:59,  1.67it/s]

  4%|▍         | 25/625 [00:14<05:56,  1.68it/s]

  4%|▍         | 26/625 [00:15<05:56,  1.68it/s]

  4%|▍         | 27/625 [00:15<05:53,  1.69it/s]

  4%|▍         | 28/625 [00:16<05:57,  1.67it/s]

  5%|▍         | 29/625 [00:17<05:53,  1.69it/s]

  5%|▍         | 30/625 [00:17<05:52,  1.69it/s]

  5%|▍         | 31/625 [00:18<05:50,  1.69it/s]

  5%|▌         | 32/625 [00:18<05:55,  1.67it/s]

  5%|▌         | 33/625 [00:19<05:50,  1.69it/s]

  5%|▌         | 34/625 [00:20<05:46,  1.71it/s]

  6%|▌         | 35/625 [00:20<05:45,  1.71it/s]

  6%|▌         | 36/625 [00:21<05:47,  1.69it/s]

  6%|▌         | 37/625 [00:21<05:46,  1.70it/s]

  6%|▌         | 38/625 [00:22<05:49,  1.68it/s]

  6%|▌         | 39/625 [00:23<05:47,  1.69it/s]

  6%|▋         | 40/625 [00:23<05:49,  1.68it/s]

  7%|▋         | 41/625 [00:24<05:44,  1.70it/s]

  7%|▋         | 42/625 [00:24<05:42,  1.70it/s]

  7%|▋         | 43/625 [00:25<05:38,  1.72it/s]

  7%|▋         | 44/625 [00:25<05:39,  1.71it/s]

  7%|▋         | 45/625 [00:26<05:45,  1.68it/s]

  7%|▋         | 46/625 [00:27<05:43,  1.68it/s]

  8%|▊         | 47/625 [00:27<05:45,  1.67it/s]

  8%|▊         | 48/625 [00:28<05:47,  1.66it/s]

  8%|▊         | 49/625 [00:28<05:44,  1.67it/s]

  8%|▊         | 50/625 [00:29<05:45,  1.66it/s]

  8%|▊         | 51/625 [00:30<05:41,  1.68it/s]

  8%|▊         | 52/625 [00:30<05:43,  1.67it/s]

  8%|▊         | 53/625 [00:31<05:44,  1.66it/s]

  9%|▊         | 54/625 [00:31<05:42,  1.67it/s]

  9%|▉         | 55/625 [00:32<05:36,  1.69it/s]

  9%|▉         | 56/625 [00:33<05:38,  1.68it/s]

  9%|▉         | 57/625 [00:33<05:39,  1.67it/s]

  9%|▉         | 58/625 [00:34<05:38,  1.68it/s]

  9%|▉         | 59/625 [00:34<05:39,  1.67it/s]

 10%|▉         | 60/625 [00:35<05:47,  1.62it/s]

 10%|▉         | 61/625 [00:36<05:44,  1.63it/s]

 10%|▉         | 62/625 [00:36<05:43,  1.64it/s]

 10%|█         | 63/625 [00:37<05:38,  1.66it/s]

 10%|█         | 64/625 [00:38<05:43,  1.63it/s]

 10%|█         | 65/625 [00:38<05:41,  1.64it/s]

 11%|█         | 66/625 [00:39<05:37,  1.65it/s]

 11%|█         | 67/625 [00:39<05:33,  1.67it/s]

 11%|█         | 68/625 [00:40<05:45,  1.61it/s]

 11%|█         | 69/625 [00:41<05:40,  1.63it/s]

 11%|█         | 70/625 [00:41<05:37,  1.64it/s]

 11%|█▏        | 71/625 [00:42<05:34,  1.65it/s]

 12%|█▏        | 72/625 [00:42<05:34,  1.65it/s]

 12%|█▏        | 73/625 [00:43<05:29,  1.68it/s]

 12%|█▏        | 74/625 [00:44<05:30,  1.67it/s]

 12%|█▏        | 75/625 [00:44<05:27,  1.68it/s]

 12%|█▏        | 76/625 [00:45<05:28,  1.67it/s]

 12%|█▏        | 77/625 [00:45<05:25,  1.68it/s]

 12%|█▏        | 78/625 [00:46<05:29,  1.66it/s]

 13%|█▎        | 79/625 [00:47<05:25,  1.68it/s]

 13%|█▎        | 80/625 [00:47<05:26,  1.67it/s]

 13%|█▎        | 81/625 [00:48<05:22,  1.69it/s]

 13%|█▎        | 82/625 [00:48<05:20,  1.69it/s]

 13%|█▎        | 83/625 [00:49<05:18,  1.70it/s]

 13%|█▎        | 84/625 [00:50<05:20,  1.69it/s]

 14%|█▎        | 85/625 [00:50<05:17,  1.70it/s]

 14%|█▍        | 86/625 [00:51<05:18,  1.69it/s]

 14%|█▍        | 87/625 [00:51<05:18,  1.69it/s]

 14%|█▍        | 88/625 [00:52<05:19,  1.68it/s]

 14%|█▍        | 89/625 [00:52<05:15,  1.70it/s]

 14%|█▍        | 90/625 [00:53<05:14,  1.70it/s]

 15%|█▍        | 91/625 [00:54<05:13,  1.70it/s]

 15%|█▍        | 92/625 [00:54<05:20,  1.67it/s]

 15%|█▍        | 93/625 [00:55<05:19,  1.66it/s]

 15%|█▌        | 94/625 [00:55<05:16,  1.68it/s]

 15%|█▌        | 95/625 [00:56<05:23,  1.64it/s]

 15%|█▌        | 96/625 [00:57<05:26,  1.62it/s]

 16%|█▌        | 97/625 [00:57<05:22,  1.64it/s]

 16%|█▌        | 98/625 [00:58<05:27,  1.61it/s]

 16%|█▌        | 99/625 [00:59<05:23,  1.63it/s]

 16%|█▌        | 100/625 [00:59<05:28,  1.60it/s]

 16%|█▌        | 101/625 [01:00<05:21,  1.63it/s]

 16%|█▋        | 102/625 [01:00<05:18,  1.64it/s]

 16%|█▋        | 103/625 [01:01<05:18,  1.64it/s]

 17%|█▋        | 104/625 [01:02<05:21,  1.62it/s]

 17%|█▋        | 105/625 [01:02<05:16,  1.64it/s]

 17%|█▋        | 106/625 [01:03<05:11,  1.67it/s]

 17%|█▋        | 107/625 [01:03<05:09,  1.67it/s]

 17%|█▋        | 108/625 [01:04<05:09,  1.67it/s]

 17%|█▋        | 109/625 [01:05<05:12,  1.65it/s]

 18%|█▊        | 110/625 [01:05<05:14,  1.64it/s]

 18%|█▊        | 111/625 [01:06<05:18,  1.62it/s]

 18%|█▊        | 112/625 [01:07<05:19,  1.61it/s]

 18%|█▊        | 113/625 [01:07<05:12,  1.64it/s]

 18%|█▊        | 114/625 [01:08<05:07,  1.66it/s]

 18%|█▊        | 115/625 [01:08<05:02,  1.68it/s]

 19%|█▊        | 116/625 [01:09<05:06,  1.66it/s]

 19%|█▊        | 117/625 [01:09<05:05,  1.67it/s]

 19%|█▉        | 118/625 [01:10<05:02,  1.67it/s]

 19%|█▉        | 119/625 [01:11<05:02,  1.67it/s]

 19%|█▉        | 120/625 [01:11<05:07,  1.64it/s]

 19%|█▉        | 121/625 [01:12<05:07,  1.64it/s]

 20%|█▉        | 122/625 [01:13<05:08,  1.63it/s]

 20%|█▉        | 123/625 [01:13<05:13,  1.60it/s]

 20%|█▉        | 124/625 [01:14<05:15,  1.59it/s]

 20%|██        | 125/625 [01:14<05:07,  1.62it/s]

 20%|██        | 126/625 [01:15<05:06,  1.63it/s]

 20%|██        | 127/625 [01:16<05:04,  1.64it/s]

 20%|██        | 128/625 [01:16<05:07,  1.62it/s]

 21%|██        | 129/625 [01:17<05:03,  1.63it/s]

 21%|██        | 130/625 [01:17<05:01,  1.64it/s]

 21%|██        | 131/625 [01:18<05:02,  1.63it/s]

 21%|██        | 132/625 [01:19<05:04,  1.62it/s]

 21%|██▏       | 133/625 [01:19<05:00,  1.64it/s]

 21%|██▏       | 134/625 [01:20<05:01,  1.63it/s]

 22%|██▏       | 135/625 [01:21<05:03,  1.61it/s]

 22%|██▏       | 136/625 [01:21<05:05,  1.60it/s]

 22%|██▏       | 137/625 [01:22<05:00,  1.63it/s]

 22%|██▏       | 138/625 [01:22<04:57,  1.64it/s]

 22%|██▏       | 139/625 [01:23<04:52,  1.66it/s]

 22%|██▏       | 140/625 [01:24<04:55,  1.64it/s]

 23%|██▎       | 141/625 [01:24<04:59,  1.62it/s]

 23%|██▎       | 142/625 [01:25<04:57,  1.62it/s]

 23%|██▎       | 143/625 [01:25<04:58,  1.62it/s]

 23%|██▎       | 144/625 [01:26<05:02,  1.59it/s]

 23%|██▎       | 145/625 [01:27<04:59,  1.60it/s]

 23%|██▎       | 146/625 [01:27<04:58,  1.60it/s]

 24%|██▎       | 147/625 [01:28<04:55,  1.62it/s]

 24%|██▎       | 148/625 [01:29<04:53,  1.62it/s]

 24%|██▍       | 149/625 [01:29<04:54,  1.62it/s]

 24%|██▍       | 150/625 [01:30<04:49,  1.64it/s]

 24%|██▍       | 151/625 [01:30<04:43,  1.67it/s]

 24%|██▍       | 152/625 [01:31<04:45,  1.66it/s]

 24%|██▍       | 153/625 [01:32<04:48,  1.64it/s]

 25%|██▍       | 154/625 [01:32<04:43,  1.66it/s]

 25%|██▍       | 155/625 [01:33<04:43,  1.66it/s]

 25%|██▍       | 156/625 [01:33<04:45,  1.64it/s]

 25%|██▌       | 157/625 [01:34<04:45,  1.64it/s]

 25%|██▌       | 158/625 [01:35<04:45,  1.63it/s]

 25%|██▌       | 159/625 [01:35<04:43,  1.64it/s]

 26%|██▌       | 160/625 [01:36<04:47,  1.62it/s]

 26%|██▌       | 161/625 [01:36<04:44,  1.63it/s]

 26%|██▌       | 162/625 [01:37<04:44,  1.63it/s]

 26%|██▌       | 163/625 [01:38<04:43,  1.63it/s]

 26%|██▌       | 164/625 [01:38<04:47,  1.61it/s]

 26%|██▋       | 165/625 [01:39<04:44,  1.61it/s]

 27%|██▋       | 166/625 [01:40<04:41,  1.63it/s]

 27%|██▋       | 167/625 [01:40<04:39,  1.64it/s]

 27%|██▋       | 168/625 [01:41<04:43,  1.61it/s]

 27%|██▋       | 169/625 [01:41<04:39,  1.63it/s]

 27%|██▋       | 170/625 [01:42<04:37,  1.64it/s]

 27%|██▋       | 171/625 [01:43<04:33,  1.66it/s]

 28%|██▊       | 172/625 [01:43<04:34,  1.65it/s]

 28%|██▊       | 173/625 [01:44<04:29,  1.68it/s]

 28%|██▊       | 174/625 [01:44<04:26,  1.69it/s]

 28%|██▊       | 175/625 [01:45<04:22,  1.71it/s]

 28%|██▊       | 176/625 [01:46<04:25,  1.69it/s]

 28%|██▊       | 177/625 [01:46<04:22,  1.70it/s]

 28%|██▊       | 178/625 [01:47<04:18,  1.73it/s]

 29%|██▊       | 179/625 [01:47<04:18,  1.72it/s]

 29%|██▉       | 180/625 [01:48<04:20,  1.71it/s]

 29%|██▉       | 181/625 [01:48<04:18,  1.72it/s]

 29%|██▉       | 182/625 [01:49<04:20,  1.70it/s]

 29%|██▉       | 183/625 [01:50<04:18,  1.71it/s]

 29%|██▉       | 184/625 [01:50<04:20,  1.70it/s]

 30%|██▉       | 185/625 [01:51<04:20,  1.69it/s]

 30%|██▉       | 186/625 [01:51<04:22,  1.67it/s]

 30%|██▉       | 187/625 [01:52<04:21,  1.67it/s]

 30%|███       | 188/625 [01:53<04:25,  1.65it/s]

 30%|███       | 189/625 [01:53<04:24,  1.65it/s]

 30%|███       | 190/625 [01:54<04:22,  1.66it/s]

 31%|███       | 191/625 [01:54<04:21,  1.66it/s]

 31%|███       | 192/625 [01:55<04:23,  1.65it/s]

 31%|███       | 193/625 [01:56<04:21,  1.65it/s]

 31%|███       | 194/625 [01:56<04:31,  1.59it/s]

 31%|███       | 195/625 [01:57<04:39,  1.54it/s]

 31%|███▏      | 196/625 [01:58<04:48,  1.49it/s]

 32%|███▏      | 197/625 [01:58<04:42,  1.51it/s]

 32%|███▏      | 198/625 [01:59<04:32,  1.56it/s]

 32%|███▏      | 199/625 [02:00<04:25,  1.61it/s]

 32%|███▏      | 200/625 [02:00<04:23,  1.61it/s]

 32%|███▏      | 201/625 [02:01<04:21,  1.62it/s]

 32%|███▏      | 202/625 [02:01<04:16,  1.65it/s]

 32%|███▏      | 203/625 [02:02<04:14,  1.66it/s]

 33%|███▎      | 204/625 [02:03<04:13,  1.66it/s]

 33%|███▎      | 205/625 [02:03<04:10,  1.67it/s]

 33%|███▎      | 206/625 [02:04<04:10,  1.67it/s]

 33%|███▎      | 207/625 [02:04<04:08,  1.69it/s]

 33%|███▎      | 208/625 [02:05<04:09,  1.67it/s]

 33%|███▎      | 209/625 [02:06<04:08,  1.67it/s]

 34%|███▎      | 210/625 [02:06<04:07,  1.68it/s]

 34%|███▍      | 211/625 [02:07<04:05,  1.68it/s]

 34%|███▍      | 212/625 [02:07<04:07,  1.67it/s]

 34%|███▍      | 213/625 [02:08<04:06,  1.67it/s]

 34%|███▍      | 214/625 [02:09<04:03,  1.69it/s]

 34%|███▍      | 215/625 [02:09<04:02,  1.69it/s]

 35%|███▍      | 216/625 [02:10<04:05,  1.67it/s]

 35%|███▍      | 217/625 [02:10<04:05,  1.66it/s]

 35%|███▍      | 218/625 [02:11<04:05,  1.65it/s]

 35%|███▌      | 219/625 [02:12<04:03,  1.67it/s]

 35%|███▌      | 220/625 [02:12<04:03,  1.66it/s]

 35%|███▌      | 221/625 [02:13<04:00,  1.68it/s]

 36%|███▌      | 222/625 [02:13<03:58,  1.69it/s]

 36%|███▌      | 223/625 [02:14<03:56,  1.70it/s]

 36%|███▌      | 224/625 [02:15<03:59,  1.68it/s]

 36%|███▌      | 225/625 [02:15<03:58,  1.68it/s]

 36%|███▌      | 226/625 [02:16<03:55,  1.70it/s]

 36%|███▋      | 227/625 [02:16<03:58,  1.67it/s]

 36%|███▋      | 228/625 [02:17<04:00,  1.65it/s]

 37%|███▋      | 229/625 [02:18<03:58,  1.66it/s]

 37%|███▋      | 230/625 [02:18<03:59,  1.65it/s]

 37%|███▋      | 231/625 [02:19<03:57,  1.66it/s]

 37%|███▋      | 232/625 [02:19<03:58,  1.65it/s]

 37%|███▋      | 233/625 [02:20<03:59,  1.64it/s]

 37%|███▋      | 234/625 [02:21<04:06,  1.59it/s]

 38%|███▊      | 235/625 [02:21<04:01,  1.62it/s]

 38%|███▊      | 236/625 [02:22<04:00,  1.62it/s]

 38%|███▊      | 237/625 [02:22<03:56,  1.64it/s]

 38%|███▊      | 238/625 [02:23<03:52,  1.67it/s]

 38%|███▊      | 239/625 [02:24<03:51,  1.67it/s]

 38%|███▊      | 240/625 [02:24<03:53,  1.65it/s]

 39%|███▊      | 241/625 [02:25<03:50,  1.66it/s]

 39%|███▊      | 242/625 [02:25<03:49,  1.67it/s]

 39%|███▉      | 243/625 [02:26<03:47,  1.68it/s]

 39%|███▉      | 244/625 [02:27<03:48,  1.67it/s]

 39%|███▉      | 245/625 [02:27<03:45,  1.68it/s]

 39%|███▉      | 246/625 [02:28<03:44,  1.69it/s]

 40%|███▉      | 247/625 [02:28<03:42,  1.70it/s]

 40%|███▉      | 248/625 [02:29<03:43,  1.68it/s]

 40%|███▉      | 249/625 [02:30<03:45,  1.67it/s]

 40%|████      | 250/625 [02:30<03:42,  1.68it/s]

 40%|████      | 251/625 [02:31<03:42,  1.68it/s]

 40%|████      | 252/625 [02:31<03:47,  1.64it/s]

 40%|████      | 253/625 [02:32<03:45,  1.65it/s]

 41%|████      | 254/625 [02:33<03:46,  1.63it/s]

 41%|████      | 255/625 [02:33<03:44,  1.65it/s]

 41%|████      | 256/625 [02:34<03:46,  1.63it/s]

 41%|████      | 257/625 [02:34<03:42,  1.65it/s]

 41%|████▏     | 258/625 [02:35<03:40,  1.66it/s]

 41%|████▏     | 259/625 [02:36<03:36,  1.69it/s]

 42%|████▏     | 260/625 [02:36<03:39,  1.66it/s]

 42%|████▏     | 261/625 [02:37<03:38,  1.67it/s]

 42%|████▏     | 262/625 [02:37<03:34,  1.69it/s]

 42%|████▏     | 263/625 [02:38<03:33,  1.70it/s]

 42%|████▏     | 264/625 [02:39<03:35,  1.68it/s]

 42%|████▏     | 265/625 [02:39<03:32,  1.69it/s]

 43%|████▎     | 266/625 [02:40<03:33,  1.68it/s]

 43%|████▎     | 267/625 [02:40<03:32,  1.68it/s]

 43%|████▎     | 268/625 [02:41<03:33,  1.67it/s]

 43%|████▎     | 269/625 [02:42<03:31,  1.69it/s]

 43%|████▎     | 270/625 [02:42<03:29,  1.69it/s]

 43%|████▎     | 271/625 [02:43<03:28,  1.70it/s]

 44%|████▎     | 272/625 [02:43<03:31,  1.67it/s]

 44%|████▎     | 273/625 [02:44<03:30,  1.67it/s]

 44%|████▍     | 274/625 [02:45<03:27,  1.69it/s]

 44%|████▍     | 275/625 [02:45<03:27,  1.69it/s]

 44%|████▍     | 276/625 [02:46<03:27,  1.68it/s]

 44%|████▍     | 277/625 [02:46<03:28,  1.67it/s]

 44%|████▍     | 278/625 [02:47<03:31,  1.64it/s]

 45%|████▍     | 279/625 [02:48<03:30,  1.64it/s]

 45%|████▍     | 280/625 [02:48<03:32,  1.62it/s]

 45%|████▍     | 281/625 [02:49<03:32,  1.62it/s]

 45%|████▌     | 282/625 [02:49<03:30,  1.63it/s]

 45%|████▌     | 283/625 [02:50<03:32,  1.61it/s]

 45%|████▌     | 284/625 [02:51<03:36,  1.58it/s]

 46%|████▌     | 285/625 [02:51<03:32,  1.60it/s]

 46%|████▌     | 286/625 [02:52<03:26,  1.64it/s]

 46%|████▌     | 287/625 [02:52<03:25,  1.65it/s]

 46%|████▌     | 288/625 [02:53<03:26,  1.63it/s]

 46%|████▌     | 289/625 [02:54<03:24,  1.64it/s]

 46%|████▋     | 290/625 [02:54<03:25,  1.63it/s]

 47%|████▋     | 291/625 [02:55<03:26,  1.61it/s]

 47%|████▋     | 292/625 [02:56<03:29,  1.59it/s]

 47%|████▋     | 293/625 [02:56<03:28,  1.59it/s]

 47%|████▋     | 294/625 [02:57<03:29,  1.58it/s]

 47%|████▋     | 295/625 [02:58<03:26,  1.60it/s]

 47%|████▋     | 296/625 [02:58<03:27,  1.59it/s]

 48%|████▊     | 297/625 [02:59<03:24,  1.60it/s]

 48%|████▊     | 298/625 [02:59<03:20,  1.63it/s]

 48%|████▊     | 299/625 [03:00<03:16,  1.66it/s]

 48%|████▊     | 300/625 [03:01<03:16,  1.66it/s]

 48%|████▊     | 301/625 [03:01<03:17,  1.64it/s]

 48%|████▊     | 302/625 [03:02<03:19,  1.62it/s]

 48%|████▊     | 303/625 [03:02<03:19,  1.62it/s]

 49%|████▊     | 304/625 [03:03<03:20,  1.60it/s]

 49%|████▉     | 305/625 [03:04<03:16,  1.63it/s]

 49%|████▉     | 306/625 [03:04<03:14,  1.64it/s]

 49%|████▉     | 307/625 [03:05<03:13,  1.65it/s]

 49%|████▉     | 308/625 [03:05<03:13,  1.63it/s]

 49%|████▉     | 309/625 [03:06<03:11,  1.65it/s]

 50%|████▉     | 310/625 [03:07<03:08,  1.67it/s]

 50%|████▉     | 311/625 [03:07<03:07,  1.67it/s]

 50%|████▉     | 312/625 [03:08<03:08,  1.66it/s]

 50%|█████     | 313/625 [03:08<03:07,  1.66it/s]

 50%|█████     | 314/625 [03:09<03:06,  1.66it/s]

 50%|█████     | 315/625 [03:10<03:05,  1.67it/s]

 51%|█████     | 316/625 [03:10<03:07,  1.64it/s]

 51%|█████     | 317/625 [03:11<03:05,  1.66it/s]

 51%|█████     | 318/625 [03:11<03:06,  1.65it/s]

 51%|█████     | 319/625 [03:12<03:03,  1.67it/s]

 51%|█████     | 320/625 [03:13<03:02,  1.67it/s]

 51%|█████▏    | 321/625 [03:13<03:01,  1.68it/s]

 52%|█████▏    | 322/625 [03:14<02:58,  1.70it/s]

 52%|█████▏    | 323/625 [03:14<02:58,  1.69it/s]

 52%|█████▏    | 324/625 [03:15<02:59,  1.67it/s]

 52%|█████▏    | 325/625 [03:16<02:59,  1.67it/s]

 52%|█████▏    | 326/625 [03:16<03:00,  1.65it/s]

 52%|█████▏    | 327/625 [03:17<02:57,  1.68it/s]

 52%|█████▏    | 328/625 [03:17<02:57,  1.67it/s]

 53%|█████▎    | 329/625 [03:18<02:56,  1.68it/s]

 53%|█████▎    | 330/625 [03:19<02:55,  1.68it/s]

 53%|█████▎    | 331/625 [03:19<02:53,  1.70it/s]

 53%|█████▎    | 332/625 [03:20<02:54,  1.68it/s]

 53%|█████▎    | 333/625 [03:20<02:52,  1.69it/s]

 53%|█████▎    | 334/625 [03:21<02:51,  1.69it/s]

 54%|█████▎    | 335/625 [03:22<02:52,  1.68it/s]

 54%|█████▍    | 336/625 [03:22<02:55,  1.65it/s]

 54%|█████▍    | 337/625 [03:23<02:53,  1.66it/s]

 54%|█████▍    | 338/625 [03:23<02:53,  1.65it/s]

 54%|█████▍    | 339/625 [03:24<02:51,  1.67it/s]

 54%|█████▍    | 340/625 [03:25<02:53,  1.64it/s]

 55%|█████▍    | 341/625 [03:25<02:50,  1.67it/s]

 55%|█████▍    | 342/625 [03:26<02:48,  1.68it/s]

 55%|█████▍    | 343/625 [03:26<02:46,  1.69it/s]

 55%|█████▌    | 344/625 [03:27<02:48,  1.67it/s]

 55%|█████▌    | 345/625 [03:28<02:47,  1.67it/s]

 55%|█████▌    | 346/625 [03:28<02:46,  1.67it/s]

 56%|█████▌    | 347/625 [03:29<02:46,  1.67it/s]

 56%|█████▌    | 348/625 [03:29<02:47,  1.65it/s]

 56%|█████▌    | 349/625 [03:30<02:45,  1.67it/s]

 56%|█████▌    | 350/625 [03:31<02:45,  1.66it/s]

 56%|█████▌    | 351/625 [03:31<02:44,  1.66it/s]

 56%|█████▋    | 352/625 [03:32<02:45,  1.65it/s]

 56%|█████▋    | 353/625 [03:32<02:42,  1.67it/s]

 57%|█████▋    | 354/625 [03:33<02:39,  1.69it/s]

 57%|█████▋    | 355/625 [03:34<02:37,  1.71it/s]

 57%|█████▋    | 356/625 [03:34<02:40,  1.67it/s]

 57%|█████▋    | 357/625 [03:35<02:38,  1.69it/s]

 57%|█████▋    | 358/625 [03:35<02:36,  1.71it/s]

 57%|█████▋    | 359/625 [03:36<02:36,  1.69it/s]

 58%|█████▊    | 360/625 [03:37<02:37,  1.68it/s]

 58%|█████▊    | 361/625 [03:37<02:37,  1.68it/s]

 58%|█████▊    | 362/625 [03:38<02:37,  1.66it/s]

 58%|█████▊    | 363/625 [03:38<02:36,  1.67it/s]

 58%|█████▊    | 364/625 [03:39<02:38,  1.65it/s]

 58%|█████▊    | 365/625 [03:40<02:38,  1.64it/s]

 59%|█████▊    | 366/625 [03:40<02:37,  1.65it/s]

 59%|█████▊    | 367/625 [03:41<02:35,  1.66it/s]

 59%|█████▉    | 368/625 [03:41<02:39,  1.61it/s]

 59%|█████▉    | 369/625 [03:42<02:38,  1.62it/s]

 59%|█████▉    | 370/625 [03:43<02:35,  1.64it/s]

 59%|█████▉    | 371/625 [03:43<02:34,  1.65it/s]

 60%|█████▉    | 372/625 [03:44<02:34,  1.64it/s]

 60%|█████▉    | 373/625 [03:44<02:31,  1.66it/s]

 60%|█████▉    | 374/625 [03:45<02:32,  1.65it/s]

 60%|██████    | 375/625 [03:46<02:31,  1.65it/s]

 60%|██████    | 376/625 [03:46<02:34,  1.61it/s]

 60%|██████    | 377/625 [03:47<02:34,  1.60it/s]

 60%|██████    | 378/625 [03:48<02:33,  1.61it/s]

 61%|██████    | 379/625 [03:48<02:31,  1.63it/s]

 61%|██████    | 380/625 [03:49<02:32,  1.60it/s]

 61%|██████    | 381/625 [03:49<02:32,  1.60it/s]

 61%|██████    | 382/625 [03:50<02:30,  1.61it/s]

 61%|██████▏   | 383/625 [03:51<02:30,  1.60it/s]

 61%|██████▏   | 384/625 [03:51<02:31,  1.59it/s]

 62%|██████▏   | 385/625 [03:52<02:28,  1.62it/s]

 62%|██████▏   | 386/625 [03:53<02:27,  1.62it/s]

 62%|██████▏   | 387/625 [03:53<02:25,  1.64it/s]

 62%|██████▏   | 388/625 [03:54<02:26,  1.62it/s]

 62%|██████▏   | 389/625 [03:54<02:24,  1.64it/s]

 62%|██████▏   | 390/625 [03:55<02:23,  1.64it/s]

 63%|██████▎   | 391/625 [03:56<02:21,  1.66it/s]

 63%|██████▎   | 392/625 [03:56<02:22,  1.63it/s]

 63%|██████▎   | 393/625 [03:57<02:21,  1.63it/s]

 63%|██████▎   | 394/625 [03:57<02:20,  1.65it/s]

 63%|██████▎   | 395/625 [03:58<02:19,  1.65it/s]

 63%|██████▎   | 396/625 [03:59<02:20,  1.63it/s]

 64%|██████▎   | 397/625 [03:59<02:18,  1.64it/s]

 64%|██████▎   | 398/625 [04:00<02:18,  1.64it/s]

 64%|██████▍   | 399/625 [04:00<02:16,  1.66it/s]

 64%|██████▍   | 400/625 [04:01<02:16,  1.65it/s]

 64%|██████▍   | 401/625 [04:02<02:13,  1.67it/s]

 64%|██████▍   | 402/625 [04:02<02:12,  1.69it/s]

 64%|██████▍   | 403/625 [04:03<02:11,  1.69it/s]

 65%|██████▍   | 404/625 [04:03<02:14,  1.64it/s]

 65%|██████▍   | 405/625 [04:04<02:13,  1.65it/s]

 65%|██████▍   | 406/625 [04:05<02:10,  1.68it/s]

 65%|██████▌   | 407/625 [04:05<02:12,  1.64it/s]

 65%|██████▌   | 408/625 [04:06<02:14,  1.62it/s]

 65%|██████▌   | 409/625 [04:06<02:12,  1.63it/s]

 66%|██████▌   | 410/625 [04:07<02:12,  1.62it/s]

 66%|██████▌   | 411/625 [04:08<02:10,  1.64it/s]

 66%|██████▌   | 412/625 [04:08<02:10,  1.63it/s]

 66%|██████▌   | 413/625 [04:09<02:08,  1.65it/s]

 66%|██████▌   | 414/625 [04:09<02:06,  1.67it/s]

 66%|██████▋   | 415/625 [04:10<02:04,  1.68it/s]

 67%|██████▋   | 416/625 [04:11<02:06,  1.65it/s]

 67%|██████▋   | 417/625 [04:11<02:08,  1.62it/s]

 67%|██████▋   | 418/625 [04:12<02:07,  1.63it/s]

 67%|██████▋   | 419/625 [04:13<02:07,  1.61it/s]

 67%|██████▋   | 420/625 [04:13<02:09,  1.59it/s]

 67%|██████▋   | 421/625 [04:14<02:08,  1.59it/s]

 68%|██████▊   | 422/625 [04:15<02:08,  1.58it/s]

 68%|██████▊   | 423/625 [04:15<02:05,  1.61it/s]

 68%|██████▊   | 424/625 [04:16<02:05,  1.60it/s]

 68%|██████▊   | 425/625 [04:16<02:04,  1.61it/s]

 68%|██████▊   | 426/625 [04:17<02:02,  1.62it/s]

 68%|██████▊   | 427/625 [04:18<02:04,  1.60it/s]

 68%|██████▊   | 428/625 [04:18<02:04,  1.58it/s]

 69%|██████▊   | 429/625 [04:19<02:01,  1.61it/s]

 69%|██████▉   | 430/625 [04:19<01:59,  1.64it/s]

 69%|██████▉   | 431/625 [04:20<01:57,  1.65it/s]

 69%|██████▉   | 432/625 [04:21<01:57,  1.64it/s]

 69%|██████▉   | 433/625 [04:21<01:56,  1.65it/s]

 69%|██████▉   | 434/625 [04:22<01:56,  1.64it/s]

 70%|██████▉   | 435/625 [04:22<01:55,  1.65it/s]

 70%|██████▉   | 436/625 [04:23<01:55,  1.63it/s]

 70%|██████▉   | 437/625 [04:24<01:53,  1.65it/s]

 70%|███████   | 438/625 [04:24<01:53,  1.65it/s]

 70%|███████   | 439/625 [04:25<01:51,  1.67it/s]

 70%|███████   | 440/625 [04:25<01:52,  1.65it/s]

 71%|███████   | 441/625 [04:26<01:51,  1.64it/s]

 71%|███████   | 442/625 [04:27<01:50,  1.65it/s]

 71%|███████   | 443/625 [04:27<01:50,  1.65it/s]

 71%|███████   | 444/625 [04:28<01:54,  1.58it/s]

 71%|███████   | 445/625 [04:29<01:52,  1.59it/s]

 71%|███████▏  | 446/625 [04:29<01:51,  1.60it/s]

 72%|███████▏  | 447/625 [04:30<01:49,  1.63it/s]

 72%|███████▏  | 448/625 [04:30<01:48,  1.63it/s]

 72%|███████▏  | 449/625 [04:31<01:46,  1.65it/s]

 72%|███████▏  | 450/625 [04:32<01:45,  1.67it/s]

 72%|███████▏  | 451/625 [04:32<01:43,  1.69it/s]

 72%|███████▏  | 452/625 [04:33<01:44,  1.66it/s]

 72%|███████▏  | 453/625 [04:33<01:42,  1.67it/s]

 73%|███████▎  | 454/625 [04:34<01:41,  1.69it/s]

 73%|███████▎  | 455/625 [04:35<01:40,  1.69it/s]

 73%|███████▎  | 456/625 [04:35<01:41,  1.66it/s]

 73%|███████▎  | 457/625 [04:36<01:40,  1.68it/s]

 73%|███████▎  | 458/625 [04:36<01:41,  1.64it/s]

 73%|███████▎  | 459/625 [04:37<01:39,  1.66it/s]

 74%|███████▎  | 460/625 [04:38<01:39,  1.65it/s]

 74%|███████▍  | 461/625 [04:38<01:38,  1.67it/s]

 74%|███████▍  | 462/625 [04:39<01:37,  1.67it/s]

 74%|███████▍  | 463/625 [04:39<01:38,  1.64it/s]

 74%|███████▍  | 464/625 [04:40<01:39,  1.62it/s]

 74%|███████▍  | 465/625 [04:41<01:38,  1.63it/s]

 75%|███████▍  | 466/625 [04:41<01:36,  1.65it/s]

 75%|███████▍  | 467/625 [04:42<01:34,  1.66it/s]

 75%|███████▍  | 468/625 [04:42<01:35,  1.64it/s]

 75%|███████▌  | 469/625 [04:43<01:34,  1.65it/s]

 75%|███████▌  | 470/625 [04:44<01:34,  1.65it/s]

 75%|███████▌  | 471/625 [04:44<01:33,  1.65it/s]

 76%|███████▌  | 472/625 [04:45<01:33,  1.64it/s]

 76%|███████▌  | 473/625 [04:45<01:31,  1.65it/s]

 76%|███████▌  | 474/625 [04:46<01:31,  1.65it/s]

 76%|███████▌  | 475/625 [04:47<01:30,  1.66it/s]

 76%|███████▌  | 476/625 [04:47<01:31,  1.62it/s]

 76%|███████▋  | 477/625 [04:48<01:30,  1.64it/s]

 76%|███████▋  | 478/625 [04:49<01:28,  1.66it/s]

 77%|███████▋  | 479/625 [04:49<01:28,  1.65it/s]

 77%|███████▋  | 480/625 [04:50<01:29,  1.63it/s]

 77%|███████▋  | 481/625 [04:50<01:28,  1.62it/s]

 77%|███████▋  | 482/625 [04:51<01:28,  1.62it/s]

 77%|███████▋  | 483/625 [04:52<01:26,  1.64it/s]

 77%|███████▋  | 484/625 [04:52<01:25,  1.64it/s]

 78%|███████▊  | 485/625 [04:53<01:25,  1.64it/s]

 78%|███████▊  | 486/625 [04:53<01:24,  1.65it/s]

 78%|███████▊  | 487/625 [04:54<01:21,  1.68it/s]

 78%|███████▊  | 488/625 [04:55<01:21,  1.68it/s]

 78%|███████▊  | 489/625 [04:55<01:20,  1.70it/s]

 78%|███████▊  | 490/625 [04:56<01:18,  1.72it/s]

 79%|███████▊  | 491/625 [04:56<01:18,  1.70it/s]

 79%|███████▊  | 492/625 [04:57<01:20,  1.65it/s]

 79%|███████▉  | 493/625 [04:58<01:20,  1.63it/s]

 79%|███████▉  | 494/625 [04:58<01:22,  1.59it/s]

 79%|███████▉  | 495/625 [04:59<01:22,  1.58it/s]

 79%|███████▉  | 496/625 [05:00<01:22,  1.56it/s]

 80%|███████▉  | 497/625 [05:00<01:19,  1.61it/s]

 80%|███████▉  | 498/625 [05:01<01:17,  1.63it/s]

 80%|███████▉  | 499/625 [05:01<01:16,  1.65it/s]

 80%|████████  | 500/625 [05:02<01:16,  1.63it/s]

 80%|████████  | 501/625 [05:03<01:15,  1.65it/s]

 80%|████████  | 502/625 [05:03<01:13,  1.67it/s]

 80%|████████  | 503/625 [05:04<01:12,  1.68it/s]

 81%|████████  | 504/625 [05:04<01:12,  1.67it/s]

 81%|████████  | 505/625 [05:05<01:10,  1.69it/s]

 81%|████████  | 506/625 [05:06<01:10,  1.68it/s]

 81%|████████  | 507/625 [05:06<01:09,  1.69it/s]

 81%|████████▏ | 508/625 [05:07<01:10,  1.65it/s]

 81%|████████▏ | 509/625 [05:07<01:09,  1.68it/s]

 82%|████████▏ | 510/625 [05:08<01:08,  1.69it/s]

 82%|████████▏ | 511/625 [05:08<01:06,  1.70it/s]

 82%|████████▏ | 512/625 [05:09<01:07,  1.68it/s]

 82%|████████▏ | 513/625 [05:10<01:06,  1.67it/s]

 82%|████████▏ | 514/625 [05:10<01:06,  1.67it/s]

 82%|████████▏ | 515/625 [05:11<01:06,  1.65it/s]

 83%|████████▎ | 516/625 [05:12<01:07,  1.61it/s]

 83%|████████▎ | 517/625 [05:12<01:07,  1.61it/s]

 83%|████████▎ | 518/625 [05:13<01:06,  1.60it/s]

 83%|████████▎ | 519/625 [05:13<01:05,  1.62it/s]

 83%|████████▎ | 520/625 [05:14<01:05,  1.61it/s]

 83%|████████▎ | 521/625 [05:15<01:04,  1.62it/s]

 84%|████████▎ | 522/625 [05:15<01:03,  1.61it/s]

 84%|████████▎ | 523/625 [05:16<01:01,  1.65it/s]

 84%|████████▍ | 524/625 [05:16<01:01,  1.64it/s]

 84%|████████▍ | 525/625 [05:17<01:00,  1.66it/s]

 84%|████████▍ | 526/625 [05:18<00:59,  1.66it/s]

 84%|████████▍ | 527/625 [05:18<00:58,  1.66it/s]

 84%|████████▍ | 528/625 [05:19<00:59,  1.64it/s]

 85%|████████▍ | 529/625 [05:19<00:58,  1.65it/s]

 85%|████████▍ | 530/625 [05:20<00:57,  1.65it/s]

 85%|████████▍ | 531/625 [05:21<00:56,  1.65it/s]

 85%|████████▌ | 532/625 [05:21<00:57,  1.63it/s]

 85%|████████▌ | 533/625 [05:22<00:55,  1.65it/s]

 85%|████████▌ | 534/625 [05:23<00:54,  1.66it/s]

 86%|████████▌ | 535/625 [05:23<00:53,  1.68it/s]

 86%|████████▌ | 536/625 [05:24<00:53,  1.67it/s]

 86%|████████▌ | 537/625 [05:24<00:52,  1.69it/s]

 86%|████████▌ | 538/625 [05:25<00:50,  1.71it/s]

 86%|████████▌ | 539/625 [05:25<00:50,  1.71it/s]

 86%|████████▋ | 540/625 [05:26<00:50,  1.67it/s]

 87%|████████▋ | 541/625 [05:27<00:50,  1.66it/s]

 87%|████████▋ | 542/625 [05:27<00:50,  1.65it/s]

 87%|████████▋ | 543/625 [05:28<00:49,  1.65it/s]

 87%|████████▋ | 544/625 [05:29<00:50,  1.62it/s]

 87%|████████▋ | 545/625 [05:29<00:48,  1.64it/s]

 87%|████████▋ | 546/625 [05:30<00:47,  1.65it/s]

 88%|████████▊ | 547/625 [05:30<00:46,  1.67it/s]

 88%|████████▊ | 548/625 [05:31<00:46,  1.64it/s]

 88%|████████▊ | 549/625 [05:32<00:45,  1.66it/s]

 88%|████████▊ | 550/625 [05:32<00:44,  1.68it/s]

 88%|████████▊ | 551/625 [05:33<00:43,  1.68it/s]

 88%|████████▊ | 552/625 [05:33<00:43,  1.67it/s]

 88%|████████▊ | 553/625 [05:34<00:42,  1.68it/s]

 89%|████████▊ | 554/625 [05:34<00:42,  1.68it/s]

 89%|████████▉ | 555/625 [05:35<00:41,  1.69it/s]

 89%|████████▉ | 556/625 [05:36<00:41,  1.67it/s]

 89%|████████▉ | 557/625 [05:36<00:40,  1.69it/s]

 89%|████████▉ | 558/625 [05:37<00:39,  1.69it/s]

 89%|████████▉ | 559/625 [05:37<00:38,  1.70it/s]

 90%|████████▉ | 560/625 [05:38<00:38,  1.68it/s]

 90%|████████▉ | 561/625 [05:39<00:38,  1.68it/s]

 90%|████████▉ | 562/625 [05:39<00:37,  1.70it/s]

 90%|█████████ | 563/625 [05:40<00:36,  1.70it/s]

 90%|█████████ | 564/625 [05:40<00:36,  1.66it/s]

 90%|█████████ | 565/625 [05:41<00:35,  1.67it/s]

 91%|█████████ | 566/625 [05:42<00:35,  1.66it/s]

 91%|█████████ | 567/625 [05:42<00:34,  1.67it/s]

 91%|█████████ | 568/625 [05:43<00:35,  1.62it/s]

 91%|█████████ | 569/625 [05:44<00:34,  1.61it/s]

 91%|█████████ | 570/625 [05:44<00:34,  1.62it/s]

 91%|█████████▏| 571/625 [05:45<00:33,  1.62it/s]

 92%|█████████▏| 572/625 [05:45<00:32,  1.61it/s]

 92%|█████████▏| 573/625 [05:46<00:32,  1.62it/s]

 92%|█████████▏| 574/625 [05:47<00:31,  1.61it/s]

 92%|█████████▏| 575/625 [05:47<00:31,  1.60it/s]

 92%|█████████▏| 576/625 [05:48<00:30,  1.61it/s]

 92%|█████████▏| 577/625 [05:48<00:29,  1.62it/s]

 92%|█████████▏| 578/625 [05:49<00:28,  1.62it/s]

 93%|█████████▎| 579/625 [05:50<00:28,  1.64it/s]

 93%|█████████▎| 580/625 [05:50<00:27,  1.63it/s]

 93%|█████████▎| 581/625 [05:51<00:26,  1.66it/s]

 93%|█████████▎| 582/625 [05:51<00:25,  1.67it/s]

 93%|█████████▎| 583/625 [05:52<00:24,  1.70it/s]

 93%|█████████▎| 584/625 [05:53<00:24,  1.68it/s]

 94%|█████████▎| 585/625 [05:53<00:23,  1.69it/s]

 94%|█████████▍| 586/625 [05:54<00:23,  1.69it/s]

 94%|█████████▍| 587/625 [05:54<00:22,  1.69it/s]

 94%|█████████▍| 588/625 [05:55<00:22,  1.66it/s]

 94%|█████████▍| 589/625 [05:56<00:21,  1.66it/s]

 94%|█████████▍| 590/625 [05:56<00:21,  1.65it/s]

 95%|█████████▍| 591/625 [05:57<00:20,  1.65it/s]

 95%|█████████▍| 592/625 [05:57<00:20,  1.64it/s]

 95%|█████████▍| 593/625 [05:58<00:19,  1.64it/s]

 95%|█████████▌| 594/625 [05:59<00:18,  1.64it/s]

 95%|█████████▌| 595/625 [05:59<00:17,  1.67it/s]

 95%|█████████▌| 596/625 [06:00<00:17,  1.67it/s]

 96%|█████████▌| 597/625 [06:00<00:16,  1.67it/s]

 96%|█████████▌| 598/625 [06:01<00:16,  1.67it/s]

 96%|█████████▌| 599/625 [06:02<00:15,  1.66it/s]

 96%|█████████▌| 600/625 [06:02<00:15,  1.65it/s]

 96%|█████████▌| 601/625 [06:03<00:14,  1.65it/s]

 96%|█████████▋| 602/625 [06:04<00:14,  1.64it/s]

 96%|█████████▋| 603/625 [06:04<00:13,  1.66it/s]

 97%|█████████▋| 604/625 [06:05<00:12,  1.65it/s]

 97%|█████████▋| 605/625 [06:05<00:11,  1.67it/s]

 97%|█████████▋| 606/625 [06:06<00:11,  1.68it/s]

 97%|█████████▋| 607/625 [06:06<00:10,  1.68it/s]

 97%|█████████▋| 608/625 [06:07<00:10,  1.64it/s]

 97%|█████████▋| 609/625 [06:08<00:09,  1.64it/s]

 98%|█████████▊| 610/625 [06:08<00:09,  1.67it/s]

 98%|█████████▊| 611/625 [06:09<00:08,  1.67it/s]

 98%|█████████▊| 612/625 [06:10<00:07,  1.64it/s]

 98%|█████████▊| 613/625 [06:10<00:07,  1.65it/s]

 98%|█████████▊| 614/625 [06:11<00:06,  1.63it/s]

 98%|█████████▊| 615/625 [06:11<00:06,  1.65it/s]

 99%|█████████▊| 616/625 [06:12<00:05,  1.64it/s]

 99%|█████████▊| 617/625 [06:13<00:04,  1.66it/s]

 99%|█████████▉| 618/625 [06:13<00:04,  1.67it/s]

 99%|█████████▉| 619/625 [06:14<00:03,  1.68it/s]

 99%|█████████▉| 620/625 [06:14<00:03,  1.65it/s]

 99%|█████████▉| 621/625 [06:15<00:02,  1.65it/s]

100%|█████████▉| 622/625 [06:16<00:01,  1.67it/s]

100%|█████████▉| 623/625 [06:16<00:01,  1.67it/s]

100%|█████████▉| 624/625 [06:17<00:00,  1.64it/s]

100%|██████████| 625/625 [06:17<00:00,  1.64it/s]

100%|██████████| 625/625 [06:17<00:00,  1.65it/s]

  0%|          | 0/49 [00:00<?, ?it/s]

  2%|▏         | 1/49 [00:01<01:20,  1.67s/it]

  6%|▌         | 3/49 [00:01<00:22,  2.04it/s]

 10%|█         | 5/49 [00:02<00:13,  3.34it/s]

 12%|█▏        | 6/49 [00:02<00:11,  3.82it/s]

 14%|█▍        | 7/49 [00:02<00:09,  4.27it/s]

 20%|██        | 10/49 [00:02<00:04,  7.82it/s]

 29%|██▊       | 14/49 [00:02<00:02, 12.44it/s]

 35%|███▍      | 17/49 [00:02<00:02, 15.16it/s]

 41%|████      | 20/49 [00:02<00:01, 17.76it/s]

 47%|████▋     | 23/49 [00:03<00:01, 18.93it/s]

 53%|█████▎    | 26/49 [00:03<00:01, 21.36it/s]

 59%|█████▉    | 29/49 [00:03<00:01, 17.28it/s]

 65%|██████▌   | 32/49 [00:03<00:00, 18.38it/s]

 71%|███████▏  | 35/49 [00:03<00:00, 19.12it/s]

 78%|███████▊  | 38/49 [00:03<00:00, 16.30it/s]

 84%|████████▎ | 41/49 [00:03<00:00, 18.33it/s]

 90%|████████▉ | 44/49 [00:04<00:00, 15.98it/s]

 96%|█████████▌| 47/49 [00:04<00:00, 18.06it/s]

100%|██████████| 49/49 [00:04<00:00, 11.05it/s]

/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: divide by zero encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))
/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: invalid value encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))

   haldane_4x4 done in 422 s

benzene: norb=6  occ=3  k-points=1
   benzene done in 0 s

coronene: norb=24  occ=12  k-points=1

/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: divide by zero encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))
/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: invalid value encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))

   coronene done in 11 s

/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: divide by zero encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))
/home/claude/qgt_tblr/TBLR2.py:839: RuntimeWarning: invalid value encountered in divide
  result = np.where(np.abs(emn) < delta, 0, fnm / (emn**2))

,system,norb,N_e,k_points,molecule,Tr_g_4index,QM_fluct_sum,BC_fluct_sum,max_dropped_imag,Tr_g_TBLR,Tr_g_bond_Eq1,Omega_4index,Omega_loops,C_4index,C_loops,C_loops_before_cut,sum_abs_C_loops,n_loop_rows,rmax
0,haldane,2,1,10000,False,0.860094,0.860094,0.413497,1.12537e-14,0.860094,0.860085,0.413497,0.412463,1,0.997501,0.997785,2.6368,660852,12
1,haldane_4x4,32,16,625,False,0.860094,0.860094,0.413497,1.55786e-17,0.860094,0.860089,0.413497,0.375305,1,0.907636,0.99876,2.06316,170688,3
2,benzene,6,3,1,True,0.666667,0.666667,-1.44341e-09,8.03958e-15,0.666667,0.666667,-1.44341e-09,-1.19262e-16,0,-8.25728e-16,-8.72613e-16,4.8368,120,NaN
3,coronene,24,12,1,True,0.690657,0.690657,1.87781e-10,3.03413e-15,0.690657,0.690657,1.87781e-10,-1.94289e-16,0,-6.05072e-15,-6.10829e-15,23.5269,10848,NaN

## Fluctuation-resolved quantum metric and Berry curvature

In [8]:
for name in summary.system:
    for f in ("fluctuation_quantum_metric.csv", "fluctuation_berry_curvature.csv"):
        print(f"--- {name}: {f}")
        display(pd.read_csv(os.path.join(OUT, name, f)))

--- haldane: fluctuation_quantum_metric.csv

   1orb   QM1orb  2orb      QM2orb  3orb  QM3orb  4orb  QM4orb
0  aaaa 0.345667  aaab   0.0192802  aabc       0  abcd       0
1   NaN      NaN  aaba   0.0192802  abac       0   NaN     NaN
2   NaN      NaN  aabb -0.00239612  abbc       0   NaN     NaN
3   NaN      NaN  abaa   0.0192802  abca       0   NaN     NaN
4   NaN      NaN  abab   0.0940366  abcb       0   NaN     NaN
5   NaN      NaN  abba    0.345667  abcc       0   NaN     NaN
6   NaN      NaN  abbb   0.0192802   NaN     NaN   NaN     NaN

--- haldane: fluctuation_berry_curvature.csv

   1orb     BC1orb  2orb       BC2orb  3orb  BC3orb  4orb  BC4orb
0  aaaa -6.298e-20  aaab    0.0946035  aabc       0  abcd       0
1   NaN        NaN  aaba    0.0946035  abac       0   NaN     NaN
2   NaN        NaN  aabb -2.20657e-19  abbc       0   NaN     NaN
3   NaN        NaN  abaa    0.0946035  abca       0   NaN     NaN
4   NaN        NaN  abab    0.0350828  abcb       0   NaN     NaN
5   NaN        NaN  abba   -6.298e-20  abcc       0   NaN     NaN
6   NaN        NaN  abbb    0.0946035   NaN     NaN   NaN     NaN

--- haldane_4x4: fluctuation_quantum_metric.csv

   1orb  QM1orb  2orb    QM2orb  3orb     QM3orb  4orb   QM4orb
0  aaaa       0  aaab         0  aabc -0.0266875  abcd 0.404166
1   NaN     NaN  aaba         0  abac  0.0511449   NaN      NaN
2   NaN     NaN  aabb 0.0243453  abbc          0   NaN      NaN
3   NaN     NaN  abaa         0  abca          0   NaN      NaN
4   NaN     NaN  abab  0.382669  abcb  0.0511449   NaN      NaN
5   NaN     NaN  abba         0  abcc -0.0266875   NaN      NaN
6   NaN     NaN  abbb         0   NaN        NaN   NaN      NaN

--- haldane_4x4: fluctuation_berry_curvature.csv

   1orb  BC1orb  2orb       BC2orb  3orb     BC3orb  4orb   BC4orb
0  aaaa       0  aaab            0  aabc 0.00187878  abcd 0.135976
1   NaN     NaN  aaba            0  abac   0.136881   NaN      NaN
2   NaN     NaN  aabb -3.58031e-20  abbc          0   NaN      NaN
3   NaN     NaN  abaa            0  abca          0   NaN      NaN
4   NaN     NaN  abab -2.76684e-17  abcb   0.136881   NaN      NaN
5   NaN     NaN  abba            0  abcc 0.00187878   NaN      NaN
6   NaN     NaN  abbb            0   NaN        NaN   NaN      NaN

--- benzene: fluctuation_quantum_metric.csv

   1orb  QM1orb  2orb   QM2orb  3orb    QM3orb  4orb   QM4orb
0  aaaa       0  aaab        0  aabc 0.0380103  abcd 0.111111
1   NaN     NaN  aaba        0  abac -0.110446   NaN      NaN
2   NaN     NaN  aabb 0.217569  abbc         0   NaN      NaN
3   NaN     NaN  abaa        0  abca         0   NaN      NaN
4   NaN     NaN  abab 0.482859  abcb -0.110446   NaN      NaN
5   NaN     NaN  abba        0  abcc 0.0380103   NaN      NaN
6   NaN     NaN  abbb        0   NaN       NaN   NaN      NaN

--- benzene: fluctuation_berry_curvature.csv

   1orb  BC1orb  2orb      BC2orb  3orb     BC3orb  4orb   BC4orb
0  aaaa       0  aaab           0  aabc  -0.104336  abcd 0.240563
1   NaN     NaN  aaba           0  abac -0.0159452   NaN      NaN
2   NaN     NaN  aabb 4.90322e-18  abbc          0   NaN      NaN
3   NaN     NaN  abaa           0  abca          0   NaN      NaN
4   NaN     NaN  abab 7.51682e-18  abcb -0.0159452   NaN      NaN
5   NaN     NaN  abba           0  abcc  -0.104336   NaN      NaN
6   NaN     NaN  abbb           0   NaN        NaN   NaN      NaN

--- coronene: fluctuation_quantum_metric.csv

   1orb  QM1orb  2orb    QM2orb  3orb     QM3orb  4orb   QM4orb
0  aaaa       0  aaab         0  aabc 0.00875815  abcd 0.148243
1   NaN     NaN  aaba         0  abac  0.0286081   NaN      NaN
2   NaN     NaN  aabb 0.0622914  abbc          0   NaN      NaN
3   NaN     NaN  abaa         0  abca          0   NaN      NaN
4   NaN     NaN  abab   0.40539  abcb  0.0286081   NaN      NaN
5   NaN     NaN  abba         0  abcc 0.00875815   NaN      NaN
6   NaN     NaN  abbb         0   NaN        NaN   NaN      NaN

--- coronene: fluctuation_berry_curvature.csv

   1orb  BC1orb  2orb       BC2orb  3orb    BC3orb  4orb    BC4orb
0  aaaa       0  aaab            0  aabc 0.0010339  abcd -0.111581
1   NaN     NaN  aaba            0  abac 0.0547564   NaN       NaN
2   NaN     NaN  aabb   4.2338e-19  abbc         0   NaN       NaN
3   NaN     NaN  abaa            0  abca         0   NaN       NaN
4   NaN     NaN  abab -2.00147e-19  abcb 0.0547564   NaN       NaN
5   NaN     NaN  abba            0  abcc 0.0010339   NaN       NaN
6   NaN     NaN  abbb            0   NaN       NaN   NaN       NaN

## Leading loop families (Berry curvature, three-centre partition)

In [9]:
for name in summary.system:
    fam = pd.read_csv(os.path.join(OUT, name, "berry_loop_families.csv"))
    print(f"--- {name}: {len(fam)} families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)")
    display(fam.head(6))

--- haldane: 8896 families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)

,sides_over_a,n_loops,Omega_per_e,C_imag,sum_abs_C,fraction_of_total
0,"1.000, 1.000, 1.732",36,0.172256,0.416585,0.416585,0.417628
1,"1.732, 1.732, 1.732",24,0,0,0.387968,0
2,"1.000, 1.732, 2.000",72,0.0528811,0.127888,0.127888,0.128208
3,"1.732, 3.464, 4.583",144,0,0,0.107461,0
4,"1.732, 4.000, 4.359",72,0.0334254,0.080836,0.080836,0.0810385
5,"1.732, 4.583, 5.196",144,0,0,0.0650503,0

--- haldane_4x4: 131 families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)

,sides_over_a,n_loops,Omega_per_e,C_imag,sum_abs_C,fraction_of_total
0,"1.000, 1.000, 1.732",576,0.172256,0.416585,0.416585,0.458977
1,"1.732, 1.732, 1.732",384,-4.33681e-19,-1.0842e-18,0.387968,-1.19453e-18
2,"1.000, 1.732, 2.000",1152,0.0528811,0.127888,0.127888,0.140902
3,"1.732, 3.464, 4.583",2304,4.06576e-20,2.71051e-20,0.107461,2.98633e-20
4,"1.732, 4.000, 4.359",1152,0.0334254,0.080836,0.080836,0.0890621
5,"1.732, 4.583, 5.196",2304,3.89635e-20,1.25361e-19,0.0650503,1.38118e-19

--- benzene: 3 families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)

,sides_over_a,n_loops,Omega_per_e,C_imag,sum_abs_C,fraction_of_total
0,"1.000, 1.732, 2.000",72,-0.333333,-2.4184,2.4184,NaN
1,"1.732, 1.732, 1.732",12,0.25,1.8138,1.8138,NaN
2,"1.000, 1.000, 1.732",36,0.0833333,0.6046,0.6046,NaN

--- coronene: 73 families  (n_loops counts ordered terms: 3 anchors x 2 orientations per triangle)

,sides_over_a,n_loops,Omega_per_e,C_imag,sum_abs_C,fraction_of_total
0,"1.000, 1.000, 1.732",288,0.158806,4.60869,4.60869,NaN
1,"1.732, 1.732, 1.732",156,-0.0265766,-0.771275,3.99888,NaN
2,"1.000, 1.732, 2.000",504,-0.0292953,-0.850173,2.32938,NaN
3,"1.000, 1.732, 2.646",432,-0.0456225,-1.324,1.324,NaN
4,"1.732, 3.464, 4.583",288,-0.00965161,-0.280097,0.934131,NaN
5,"1.732, 1.732, 3.000",288,0.00115155,0.0334189,0.804197,NaN